math: sign function
vlang/v pull request #10014
Opened 2021-05-05 07:24 UTC by cabralski

This PR adds a new function to `math.v` called `sign(n f64)`, it's a simple function but really essential when constructing other mathematical functions.

A minimalist test `test_sign` was added alongside with the function.

2021-05-05 11:17 UTC, medvednikov commented
Go decided no to implement this: https://github.com/golang/go/issues/3743

This SO answer explaining why: https://stackoverflow.com/questions/1986152/why-doesnt-python-have-a-sign-function

But Java does have it.

I think it's fine, can you also add a `copysign()` function please?

2021-05-05 15:04 UTC, cabralski commented
> I think it's fine, can you also add a `copysign()` function please?

There's already a `copysign` at `math.v`, do you mean that I should use `abs(x) * sign(x)` then?

```v
// copysign returns a value with the magnitude of x and the sign of y
pub fn copysign(x f64, y f64) f64 {
	return f64_from_bits((f64_bits(x) & ~sign_mask) | (f64_bits(y) & sign_mask))
}
```

2021-05-05 15:19 UTC, Gladear commented on vlib/math/math.v
> +	if n > 0 {
For a more efficient implementation, you can implementation `sign` as suggested in @medvednikov's link
```suggestion
	return copysign(1, n)
```

2021-05-05 15:24 UTC, cabralski commented
Oh, I get it now @Gladear! Added your changes.

2021-05-05 15:26 UTC, Gladear commented
Yeah, huu, I failed my multi-line suggestion apparently 😅 I only changed one line, sorry about that

2021-05-05 15:27 UTC, cabralski commented
No problem! Just fixed it.

2021-05-05 18:54 UTC, medvednikov commented
```
vlib/math/math.v:119:9: error: cannot use `f64` as type `int` in return argument
  117 | // sign returns the corresponding sign [-1, 0, 1] of the provided number.
  118 | pub fn sign(n f64) int {
  119 |     return copysign(1, n)
      |            ~~~~~~~~~~~~~~
  120 | }
```

2021-05-06 15:12 UTC, hungrybluedev reviewed
Seems fine to me. The unit tests for `sign()` could do with more variety. Like random digit-mashed floats.

2021-05-06 15:20 UTC, ulises-jeremias commented
I think we need to add a test for `math.sign(nan())`. In languages with `nan` and `-nan`, it is possible to think that it will return `1` and `-1` respectively. If I am not wrong, we don't have `-nan`, so we should return `nan` for `math.sign(nan())`, so it is the extra edge case that we have to test (and document properly).

2021-05-06 15:21 UTC, ulises-jeremias reviewed
I think we need to add a test case for `math.sign(nan())`. In languages with `nan` and `-nan`, it is possible to think that it will return `1` and `-1` respectively. If I am not wrong, we don't have `-nan`, so we should return `nan` for `math.sign(nan())`, so it is the extra edge case that we have to test (and document properly).

In that case we need to change `math.sign` to 

```v
pub fn sign(n f64) f64
```

2021-05-06 15:29 UTC, ulises-jeremias commented
Anyway, we could have another function with the actual implementation that just returns an int, knoing that `int(math.copysign(math.nan())) == 1`. That function could be

```v
pub fn signi(n f64) int
```

2021-05-06 15:30 UTC, ulises-jeremias commented
So in that case we contemplate both common cases, sign that handle math.nan() and returns nan, and a function that just returns an int. What do you think guys?

2021-05-07 14:13 UTC, cabralski reviewed
I think `sign` is good to go!

2021-05-07 17:01 UTC, spytheman commented
> Seems fine to me. The unit tests for `sign()` could do with more variety. Like random digit-mashed floats.

done

2021-05-07 17:03 UTC, spytheman commented
> ```v
> signi
> ```

done

2021-05-07 20:14 UTC, ulises-jeremias requested changes

2021-05-07 20:14 UTC, ulises-jeremias commented on vlib/math/math.v
> +	return copysign(1.0, n)
we need to add a validation here. 

```v
[inline]
pub fn sign(n f64) f64 {
    if is_nan(n) {
        return nan()
    }
	return copysign(1.0, n)
}
```

2021-05-07 20:14 UTC, ulises-jeremias commented on vlib/math/math.v
> +	return copysign(1.0, n)
and also a test for that case

2021-05-08 11:27 UTC, spytheman commented on vlib/math/math.v
> +	return copysign(1.0, n)
done

2021-05-08 11:32 UTC, merged