os: add glob() function
vlang/v pull request #10497
Opened 2021-06-17 18:02 UTC by bstnbuck

This PR adds a globbing functionality like in Go or Python.
-add function `os.glob()` for unix and windows.
-add test for `os.glob()`

The Cross-CI bug can be fixed if the necessary header file is included in the cross-compile package:
- [ ] add `glob.h` to cross-compile package

2021-06-18 07:37 UTC, Gladear requested changes
Good work 👍 
I just require one minor modification

2021-06-18 07:37 UTC, Gladear commented on vlib/os/os_nix.c.v
> +		arr := [&char(''.str), &char(''.str)]
```suggestion
		arr := [&char(c''), &char(c'')]
```

2021-06-18 15:08 UTC, bstnbuck commented on vlib/os/os_nix.c.v
> +		arr := [&char(''.str), &char(''.str)]
Thanks for the review! I fixed it.

2021-06-18 15:38 UTC, Gladear approved these changes

2021-06-19 18:33 UTC, spytheman commented
@medvednikov we need the `glob.h` file added to the macos -> linux cross compilation archive of header files.

2021-06-19 19:19 UTC, bstnbuck commented
Exactly. `utime.h` for https://github.com/vlang/v/pull/9796 and `ptrace.h` for https://github.com/vlang/v/pull/10257 too.

2021-06-25 02:18 UTC, shadowninja55 requested changes
in `vlib/os/os_windows.c.v` the `println` should be changed to `eprintln`
```v
$if debug {
  eprintln('os.glob() does not have all the features on Windows as it has on Unix operating systems')
}
```

2021-06-25 04:47 UTC, bstnbuck commented
> in `vlib/os/os_windows.c.v` the `println` should be changed to `eprintln`
> ```v
> $if debug {
>   eprintln('os.glob() does not have all the features on Windows as it has on Unix operating systems')
> }
> ```

No, I don't think it should be like that. `eprintln` changes the exit code to an error. But the debug messages should only output a supporting message. `os.file_size()` or in `ftp.v` also act like this.

2021-06-25 08:59 UTC, Gladear commented
`eprintln` doesn't change the exit code, it just prints to stderr instead of stdout
I think @shadowninja55 is right, printing this as an error instead of a standard output is the right thing to do here

2021-06-29 10:27 UTC, spytheman commented on vlib/os/os_nix.c.v
> +fn C.glob(&char, int, int, voidptr) int
the 3rd parameter is a function, not an int; make it a voidptr

2021-06-29 10:32 UTC, spytheman commented on vlib/os/os_nix.c.v
> +		arr := [&char(c''), &char(c'')]
Why is this `arr` needed?
According to the man page of `glob`, `glob` will allocate itself the memory that will be pointed to by gl_pathv.

2021-06-29 10:48 UTC, bstnbuck commented on vlib/os/os_nix.c.v
> +		arr := [&char(c''), &char(c'')]
If no such initialization takes place, a C error (not initialized) occurs. See issue #10461

2021-06-29 16:52 UTC, bstnbuck commented on vlib/os/glob_test.v
> +	matches := os.glob('vlib/v/*/*.v') or { panic(err) }
`FindFirstFile` and `FindNextFile` on Windows are not comparable to the Linux version `glob()`. Such globbing feature is not supported.

2021-06-30 05:30 UTC, merged

2021-06-30 09:21 UTC, dumblob commented on vlib/os/os_nix.c.v
> +	if patterns.len == 0 {
Could this be moved to the top to make it a fast path (i.e. before `matches` gets allocated)?