gen: disallow empty .sort() body for some types
vlang/v pull request #10550
Opened 2021-06-23 16:31 UTC by shadowninja55

some types like structs raise a c error when .sort()-ed without a body. this pr disallows that behavior. closes #10069

2021-06-23 16:48 UTC, Delta456 commented
A checker error would be way better than `cgen` error.

2021-06-23 19:07 UTC, shadowninja55 commented
> A checker error would be way better than `cgen` error.

alright ill transition it over

2021-06-24 03:43 UTC, Delta456 commented
Please add tests 🙂

2021-06-24 16:45 UTC, shadowninja55 commented
> Please add tests slightly_smiling_face

alrighty i'll do that now, thanks

2021-06-24 20:34 UTC, JalonSolov commented on vlib/v/checker/checker.v
> +			c.error('a default comparison function for `.sort()` cannot be generated for type `${c.table.type_to_str(elem_typ)}`',
Suggest changing the error message to

'custom sorting condition must be supplied for type `${c.table.type_to_str(elem_typ)}`'

It is shorter, and tells what needs to be done to fix it.

2021-06-25 08:53 UTC, Gladear requested changes

2021-06-25 08:53 UTC, Gladear commented on vlib/v/checker/checker.v
> +		] {
`.sort()` can also be auto-generated if the type has overloaded `<` if I remember correctly.
If not, the compiler probably should be able to

2021-06-25 14:23 UTC, shadowninja55 commented on vlib/v/checker/checker.v
> +		] {
idk how i forgot abt this, thanks. this actually simplifies the logic, i can check for < overloaded, and i can check for the remaining few types in addition.

2021-06-26 07:28 UTC, Gladear approved these changes

2021-06-27 14:17 UTC, merged