vweb: require explicit route attribute for vweb app methods
vlang/v pull request #10639
Opened 2021-07-01 17:04 UTC by shadowninja55

this pr requires explicitly stating a vweb method's route via attribute. this change was made to avoid exposing functions by default, to allow helper functions returning `vweb.Result` to be made, and to make the decision to create an endpoint more explicit.

2021-07-01 17:22 UTC, mcastorina requested changes

2021-07-01 17:22 UTC, mcastorina commented on vlib/vweb/vweb.v
> +			if method.attrs.filter(it.starts_with('/')).len == 0 {
`!method.attrs.any(it.starts_with('/'))` would be more performant since it doesn't allocate a new array.

2021-07-01 17:22 UTC, mcastorina commented on vlib/vweb/vweb.v
> +			if method.attrs.filter(it.starts_with('/')).len == 0 {
Also, I think the logic may be wrong here? We are iterating through the methods defined on `App` to see if the path matches it. I think this could cause a server to always respond with 404 if a method without a path attribute happens to be first in the for loop.

2021-07-01 17:31 UTC, shadowninja55 commented on vlib/vweb/vweb.v
> +			if method.attrs.filter(it.starts_with('/')).len == 0 {
> Also, I think the logic may be wrong here? We are iterating through the methods defined on `App` to see if the path matches it. I think this could cause a server to always respond with 404 if a method without a path attribute happens to be first in the for loop.

true, i can fix this a bit later when i get back to it. i'll do the other change too.

2021-07-06 16:23 UTC, JalonSolov commented on vlib/vweb/vweb.v
> +				continue
Bug in V?  This is being reported as not in a loop.  It is, it is just a comptime loop instead of a regular loop.

2021-07-06 16:24 UTC, JalonSolov commented
Need to update blog.v in the tutorial, and run `v fmt` on checker.v.

2021-07-06 18:30 UTC, medvednikov commented on vlib/vweb/vweb.v
> +				continue
`continue` is not supported in $for yet

2021-07-06 19:21 UTC, JalonSolov commented
Also need to update the example(s) in the README file in the blog tutorial.  MD check is failing because it won't compile.  checker.v still needs `v fmt` run.

2021-07-07 17:57 UTC, JalonSolov commented on vlib/vweb/vweb.v
> +		'.html': 'text/html; charset=utf-8' '.jpg':  'image/jpeg' '.js':   'application/javascript'
Why are these 3 on one line, now?

2021-07-07 19:29 UTC, shadowninja55 commented on vlib/vweb/vweb.v
> +		'.html': 'text/html; charset=utf-8' '.jpg':  'image/jpeg' '.js':   'application/javascript'
i don't think i changed it, maybe something v fmt did? i just fmt'ed vweb again so maybe it changed.

2021-07-07 19:43 UTC, JalonSolov commented on vlib/vweb/vweb.v
> +		'.html': 'text/html; charset=utf-8' '.jpg':  'image/jpeg' '.js':   'application/javascript'
Back to normal now.

2021-07-08 02:16 UTC, medvednikov commented
No, this isn't what vweb is about. Implicit routes are one of the main featuers.

2021-07-08 03:54 UTC, JalonSolov commented
The problems with implicit routes are a) you can wind up making a route available that you didn't mean to make available, which leads to b) it is a _HUGE_ security hole - you could be exposing something to completely bypass authentication, allowing people to access personal data for other users, etc.  All accidentally, or at least unintentionally.

Making the routes explicit means there can't be any such accidents.  If you add the route attribute, it is exposed.  If you don't, it isn't.  Period.  Now if you screw up and allow access to something in a route you _did_ expose, that's your own fault.  At least vweb won't be helping with that.

2021-07-09 01:26 UTC, mcastorina approved these changes
lgtm, nice job!

@medvednikov I think routes should be explicit to make intention obvious. It is reasonable for a developer to create a method that will unify a response, such as the example in https://github.com/vlang/v/issues/10442. Plus, requiring a route path makes the code more readable and is very easy to add.

2021-07-10 02:35 UTC, medvednikov commented
It's impossible to have security issues, since the method needs to public and return a `vweb.Result`.

Doing hundreds of repeated 

```
['/foo]
pub fn foo() {}
```

is against vweb's philosophy, which is similar to Rails. Convention over configuration.

2021-07-10 03:26 UTC, mcastorina commented
Any reasonable app will not have hundreds of base endpoints. They will most likely be grouped in sections (e.g. `/admin/foo`, `/admin/bar`), in which case devs will have to specify the route anyway.

Rails is slightly different in that the default is configured using the basic CRUD methods / routes but can be overwritten in a config file. vweb does not provide this.

2021-07-19 08:24 UTC, medvednikov commented
`/admin/foo` will also be handled like in Rails, without the need for explicit routes. I'm working on it right now.

2021-07-19 08:24 UTC, closed without merging