array: fix autofree of fn returning array slice (fix #10420)
vlang/v pull request #11036
Opened 2021-08-03 09:29 UTC by yuyi98

This PR fix autofree of fn returning array slice (fix #10420).

- Fix autofree of fn returning array slice.
- Add test.

```vlang
fn take_slice1(s []int) []int {
	return s[..1]
}

fn take_slice2(s []int) []int {
	return s[1..]
}

fn main() {
	a := [1, 2]

	b1 := take_slice1(a)
	println(b1)
	assert b1 == [1]

	b2 := take_slice2(a)
	println(b2)
	assert b2 == [2]
}

PS D:\Test\v\tt1> v -autofree run .
[1]
[2]
```

2021-08-03 18:29 UTC, UweKrueger commented
@yuyi98 I'm afraid this is not a general solution since the real problem is somewhat more complex. Try this:
```v
fn get_slice() []int {
    a := []int{len: 10000000, init: 7}
    b := a[9999998..]
    return b
}

fn main() {
    x := get_slice()
    println(x)
}
```
With `-gc boehm` (or without memory management) this prints `[7, 7]` but with `-autofree` you get
```
xyz.tmp.c:1795: at indent_Array_int_str: RUNTIME ERROR: invalid memory access
```
because the array memory is freed when the "original" `a` goes out of scope.

In V there is no difference between "array" and "slice" &ndash; there is none the language description and so there should be none in the implementation.

This is one of the cases where reference counting has to be used when no full-blown garbage collection done.

2021-08-03 18:30 UTC, UweKrueger requested changes
@yuyi98 I'm afraid this is not a general solution since the real problem is somewhat more complex. Try this:
```v
fn get_slice() []int {
    a := []int{len: 10000000, init: 7}
    b := a[9999998..]
    return b
}

fn main() {
    x := get_slice()
    println(x)
}
```
With `-gc boehm` (or without memory management) this prints `[7, 7]` but with `-autofree` you get
```
xyz.tmp.c:1795: at indent_Array_int_str: RUNTIME ERROR: invalid memory access
```
because the array memory is freed when the "original" `a` goes out of scope.

In V there is no difference between "array" and "slice" &ndash; there is none the language description and so there should be none in the implementation.

This is one of the cases where reference counting has to be used when no full-blown garbage collection done.

2021-08-03 22:46 UTC, yuyi98 commented
I think that's two different things. This PR is to prevent duplicate free. 
`slice` is for efficient processing, It should not change size, We should prevent this from happening in the example including slice expansion.
```vlang
fn get_slice() []int {
    a := []int{len: 10000000, init: 7}
    b := a[9999998..]
    return b
}
```
We should be able to check that this is illegal.

2021-08-04 07:31 UTC, UweKrueger commented
> `slice` is for efficient processing, It should not change size, We should prevent this from happening in the example including slice expansion.

From the [docs](https://github.com/vlang/v/blob/master/doc/docs.md#array-slices):
_In V slices are arrays themselves (they are no distinct types). As a result all array operations may be performed on them._

In Go slices can change in size, too. (V's arrays are essentially what Go's slices are, however in Go there is a distinct (underleying) `array` type which is usually not used directly.)

It's an important design decision for V *not* to have two variable size array-like types. This make the language simpler.

2021-08-04 07:50 UTC, yuyi98 commented
I don't agree with Golang's rules for slice handling, that can lead to some unexpected problems.
I think that we should use arr[..2].clone() if we want to use slice like array, It is not a new array type, it just to mark that slice is dependent on host array.

2021-08-04 08:08 UTC, UweKrueger commented
> I don't agree with Golang's rules for slice handling, that can lead to some unexpected problems.

I don't agrees with Go's slice handling either, that's why I've introduces *copy on growth* in #10219. This does not solve *all* possible problems but it can ensure that an array that's a slice from a parent array may grow without changing the parent.

2021-08-04 08:18 UTC, UweKrueger commented
Anyway, even if slices and arrays were different types this code still would not work if `a` is freed:

```v
fn get_array_part(n int) []int {
    a := get_large_array()
    return a[..n]
}
```
Forbidding patterns like this would be a huge restriction.

2021-08-04 08:22 UTC, yuyi98 commented
We can determine whether the parent array that returns slice is a temporary array variable.

2021-08-04 09:13 UTC, UweKrueger commented
> We can determine whether the parent array that returns slice is a temporary array variable.

Yes, this would be possible. And if a reference to the array data is leaving the scope it is not freed by `-autofree`.

The detection could be done similar to the *auto-heap* mechanism for references. (#9873, #10033, #10528, #10529 and #10830)

The array will however never be freed if it's data leaves the scope. But if we detect this, we could handle it with reference counting. So in the runtime array struct there would be an atomic `refcount u32.` Instead of `is_slice` a boolean field element `is_ref_counted` would be used.  It could be added to `ast.Array` (and not the run-time struct) since this handling can be done at compile time. And the distinction would not be `slice` vs. `array` but
- array of which no reference to the data leaves the scope &ndash; freed by `-autofree`, `refcount` is ignored
- array of which any reference to the array data leaves the scope (the array struct itself, a slice or a reference to an element) &ndash; memory managed by reference counting.

Implementing reference counting is of cause the second step and out of the scope of this PR. The first step(s) will be detecting (at compile time) cases where array data is referenced and suppressing the call to `array.free()` for these.

2021-08-05 02:47 UTC, closed without merging