net.http.Server: Closed the TcpListener in the close method
vlang/v pull request #11248
Opened 2021-08-19 17:23 UTC by fabriciopashaj

2021-08-19 17:29 UTC, mcastorina commented
Nice job, thanks for fixing this!

It would be much simpler to add

```v
defer { l.close() or {} }
```

after

```v
mut l := net.listen_tcp(.ip6, ':$s.port') ?
```

This way, `Server` does not need to store the connection object :)

2021-08-20 12:27 UTC, medvednikov commented
` FAIL  [ 80/634]   223.056 ms vlib/net/http/server_test.v`

2021-08-20 13:38 UTC, fabriciopashaj commented
@mcastorina I did it this way because the listener was still open, even if I were to stop the server, because the loop would be stuck, waiting for a connection.

2021-08-20 13:39 UTC, fabriciopashaj commented
Also, does anyone know why the CI fails?

2021-08-20 13:58 UTC, fabriciopashaj commented
Yes, but the port may be used before the accept times out

2021-08-20 13:59 UTC, fabriciopashaj commented
And if it doesn't break from the loop, the defer won't be executed

2021-08-20 14:02 UTC, fabriciopashaj commented
I tried doing what you said, and my program failed because I opened another server on the same port after closing the first one, because the first server was still waiting for connections

2021-08-20 14:03 UTC, mcastorina commented
`stop()` is used to signal to the server to stop executing when it can, not "stop right now." That means the port will still be in use until the server finishes and it exits the loop.

2021-08-20 14:06 UTC, fabriciopashaj commented
The port will be wasted if you don't close the listener immediatly, the server is not going to do anything after all

2021-08-20 14:07 UTC, JalonSolov commented
The server isn't going to be doing anything _new_, but it may still be doing things from the last request.

If you need an immediate, drop-everything-in-the-middle stop, a `panic` may be better.

2021-08-20 14:08 UTC, mcastorina commented
```v
import net.http

server := &http.Server{}
t := go server.listen_and_serve()
server.stop()
t.wait() ?
// now you can use the port again

server.listen_and_serve() ?
```

2021-08-20 14:08 UTC, fabriciopashaj commented
What you are saying doesn't seem flexible

2021-08-20 14:10 UTC, fabriciopashaj commented
Well what if  don't want to/can't wait for the timeout

2021-08-20 14:10 UTC, mcastorina commented
Consider this: do you want to close the connection in the middle of the server writing a response to a client? You have no clue what state it is in when you call `stop()`, so the server will exit when it safely can.

2021-08-20 14:12 UTC, fabriciopashaj commented
Well, a crash method would be more suited to close the listener no matter what

2021-08-20 15:00 UTC, fabriciopashaj commented
@spytheman Do you know why the CI fails?

2021-08-20 15:02 UTC, fabriciopashaj commented
I'm going to implement a crash method so I might as well fix the problems with the CI

2021-08-20 15:19 UTC, mcastorina commented
I see no use case for a crash method. imo it should not be implemented.

2021-08-20 15:50 UTC, JalonSolov commented
Crash == bad.  Graceful shutdown == good.  Immediate shutdown without crashing == better than crash.

2021-08-20 18:01 UTC, fabriciopashaj commented
That's what I mean by crash. Any better name then?
`force_close` or something I guess?

2021-08-20 20:01 UTC, JalonSolov commented
How about `graceful_stop` and `full_stop` for the 2 different actions?

2021-08-20 21:07 UTC, Le0Developer commented
CI is failing because you forgot to add `mut` to the test [here](https://github.com/vlang/v/blob/3d123c1752a7055d8a5ec4f6cb1b0d5572d6598b/vlib/net/http/server_test.v#L6).

Also run vfmt (`v fmt -w vlib/net/http/server.v`)

2021-08-20 21:17 UTC, fabriciopashaj commented
Yeah, I ran the test and saw those. I think that instead of `full_stop`, it would be better something like `close`, and `stop` instead of `graceful_stop`.
Btw how do I generate the V docs. I added doc comments to `stop` and `close`

2021-08-20 21:23 UTC, Le0Developer commented
Go into the V directory and execute `./v doc -m -f html vlib/` and then start a webserver or open the html in your browser.

(If you have python installed, you can do `python3 -m http.server` for example)

2021-08-21 03:07 UTC, mcastorina commented
The names should be similar to give the impression that one or the other should be used, not that both need to be used. That being said, I like @JalonSolov's suggestion or `stop` and `stop_immediate`.

I still see no use case for `stop_immediate` though, can someone please enlighten me? What operation is so critical / time sensitive to require this? If there is one, I would argue a custom server is more suitable. Providing this functionality will promote poor coding style and unnecessarily complicates `http.Server` code.

2021-08-21 03:16 UTC, JalonSolov commented
Even venerable old Apache has "graceful restart".  I can only see `stop_immediate` being useful in a couple of cases.  For instance, if someone stole a password and was downloading all your files, you might want to stop them immediately, instead of waiting until they downloaded a full ISO of your system.  :-\

2021-08-21 09:20 UTC, Le0Developer commented on vlib/net/http/server.v
> +	return ServerStatus(s.stop_signal)
```suggestion
	return s.stop_signal
```
`s.stop_signal` is already a ServerStatus enum

2021-08-21 13:40 UTC, JalonSolov commented on vlib/net/http/server.v
> +	server_stoped
server_stop**p**ed

2021-08-21 14:22 UTC, spytheman commented
You need to format your code.
```
Failed command 1:    "/home/runner/work/v/v/v" -silent  fmt -verify "/home/runner/work/v/v/vlib/net/http/server.v"
Failed command 2:    "/home/runner/work/v/v/v" -silent  fmt -verify "/home/runner/work/v/v/vlib/net/http/server_test.v"
```

2021-08-21 14:26 UTC, spytheman commented on vlib/net/http/server.v
> +// close immediatly closes the port and signals the server that it has been crashed
crash has a specific meaning, please do not use that term here

2021-08-21 14:54 UTC, fabriciopashaj commented
Should be ok now.
Sorry for all the complications. This is my first (real) pull request

2021-08-22 08:06 UTC, fabriciopashaj commented
@spytheman or @JalonSolov can you run the CI checks?

2021-08-22 08:57 UTC, Le0Developer commented on vlib/net/http/server_test.v
> +	assert server.status() == .server_stoped
```suggestion
	assert server.status() == .server_stopped
```

2021-08-22 13:56 UTC, mcastorina requested changes

2021-08-22 13:56 UTC, mcastorina commented on vlib/net/http/server.v
> +	stop_signal ServerStatus = .server_closed
This will need to be `shared` because it may be accessed / modified from multiple threads.

2021-08-22 13:56 UTC, mcastorina commented on vlib/net/http/server.v
> +	}
```suggestion
	if s.status() == .server_stopped {
	    s.close()
	}
```

2021-08-22 13:56 UTC, mcastorina commented on vlib/net/http/server.v
> +	listener    net.TcpListener
`listener` should be `shared` now too because it may be modified from multiple threads.

2021-08-22 15:04 UTC, fabriciopashaj commented on vlib/net/http/server.v
> +	stop_signal ServerStatus = .server_closed
Soooo, it should be `shared ServerStatus`?

2021-08-22 17:53 UTC, fabriciopashaj commented on vlib/net/http/server.v
> +	stop_signal ServerStatus = .server_closed
I tried it, only structs, maps anx arrays can be shared.

2021-08-22 17:57 UTC, fabriciopashaj commented on vlib/net/http/server.v
> +	listener    net.TcpListener
I don't think there will be problems with close, as it waits for the server to finish the lattest connection. The developer can use close at his own risk

2021-08-23 01:58 UTC, mcastorina commented on vlib/net/http/server.v
> +	stop_signal ServerStatus = .server_closed
Hmm.. maybe a lock is needed then?

2021-08-23 07:47 UTC, fabriciopashaj commented on vlib/net/http/server.v
> +	stop_signal ServerStatus = .server_closed
What kind of lock you are saying? Locks are used when accessing shared structs/arrays/maps. I wanted to see if I could do something with `atomic`s, but they aren't fully implemented

2021-08-23 12:30 UTC, spytheman commented on vlib/net/http/server.v
> +		if s.status() != .server_running {
Why call a function here? You can check the boolean directly.

2021-08-23 12:30 UTC, spytheman commented on vlib/net/http/server.v
> +	stop_signal ServerStatus = .server_closed
This is not a signal (change/edge) anymore, it acts more like a current state. Imho it should be renamed.

2021-08-23 12:31 UTC, spytheman commented on vlib/net/http/server.v
> +	if s.status() == .server_stopped {
No need of calling a method here, the boolean can be checked directly imho.

2021-08-23 13:21 UTC, fabriciopashaj commented on vlib/net/http/server.v
> +		if s.status() != .server_running {
It doesn't really matter, as the function that is getting called will be inlined

2021-08-23 13:24 UTC, JalonSolov commented on vlib/net/http/server.v
> +		if s.status() != .server_running {
Can you guarantee it will always be inlined?

2021-08-23 13:28 UTC, fabriciopashaj commented on vlib/net/http/server.v
> +		if s.status() != .server_running {
Isn't `[inline]` enough?

2021-08-23 13:37 UTC, fabriciopashaj commented on vlib/net/http/server.v
> +	stop_signal ServerStatus = .server_closed
Maybe name the field `status` and the function `state`

2021-08-23 14:32 UTC, mcastorina commented on vlib/net/http/server.v
> +	stop_signal ServerStatus = .server_closed
You can add a `sync.RwMutex` to the `Server` struct to do manual locking.

https://modules.vlang.io/sync.html#RwMutex

2021-08-23 15:20 UTC, JalonSolov commented on vlib/net/http/server.v
> +		if s.status() != .server_running {
No, because the C compiler is free to ignore it if it doesn't think it needs to be inlined.  And if it does think it can be inlined, it will do it without you adding the attribute.

There is no way to absolutely guarantee it will be inlined with any modern C compiler (though small routines _almost_ always will be).

2021-08-24 14:32 UTC, fabriciopashaj commented on vlib/net/http/server.v
> +	stop_signal ServerStatus = .server_closed
Nah, I don't think it will be an issue and if there is, someone will probably report it

2021-08-24 14:34 UTC, fabriciopashaj commented
Sooo, uummm, when will the branch get merged to master?

2021-08-24 15:12 UTC, mcastorina commented on vlib/net/http/server.v
> +	stop_signal ServerStatus = .server_closed
Sorry, that's not how code reviews work. This issue has not been resolved. Either prove it will not cause a race condition or fix the race condition. "Nah" is not acceptable.

2021-08-24 15:59 UTC, spytheman commented on vlib/net/http/server.v
> +	stop_signal ServerStatus = .server_closed
In this case, I agree that the race condition for this use case is very unlikely. If we can make a failing test for it, then we can merge that improvement later. Imho the PR is good to merge as it is.

2021-08-24 16:07 UTC, spytheman commented
> Sooo, uummm, when will the branch get merged to master?

When all the tests pass, *and all requested changes* are done, or at least addressed adequately, and the answers reviewed again.

2021-08-24 16:21 UTC, merged