v: add unsigned shift operators (^>^ and ^>^=)
vlang/v pull request #11536
Opened 2021-09-18 12:22 UTC by ChAoSUnItY

## **How it works**
### Expression
```v
i64(-5) ^>^ 1
```

Compiler will lower expression above with the procedure:
1. detect left expression type
2. cast left expression's type to its relative unsigned type
3. replace `^>^` with `>>`

By following the procedure above, compiler will lower the above code into the following one:
```v
u64(i64(-5)) >> 1
```
### Assignment
```v
x := i64(-5)
x ^>^= 1
```
Follows expression's lowering procedure, this will lower to the following one:
```v
x = u64(x) ^>^ 1
```

This resolves #11507

2021-09-18 15:43 UTC, spytheman commented on vlib/v/checker/checker.v
> +				13
I think it should be `ast.u32_type_idx` instead of 13 .

2021-09-18 15:45 UTC, spytheman commented on vlib/v/checker/checker.v
> +				left_type.idx() + 5
`ast.u32_type_idx - ast.int_type_idx` instead of 5 will be more robust to adding future types imho

2021-09-18 15:47 UTC, spytheman commented on vlib/v/checker/checker.v
> +					13
`ast.u32_type_idx`

2021-09-18 15:47 UTC, spytheman commented on vlib/v/checker/checker.v
> +					left_type.idx() + 5
`5` -> `ast.u32_type_idx - ast.int_type_idx`

2021-09-18 15:57 UTC, spytheman requested changes
Good work. I hope, that we can come up with a better name for this operator.

2021-09-18 15:58 UTC, spytheman commented
The suggestions so far are (please vote):

2021-09-18 15:58 UTC, spytheman commented
`+>>`

2021-09-18 15:58 UTC, spytheman commented
`->>`

2021-09-18 15:58 UTC, spytheman commented
`~>>`

2021-09-18 15:59 UTC, spytheman commented
`!>>`

2021-09-18 17:10 UTC, ChAoSUnItY commented
probably will not need vote due to #11540?

2021-09-18 18:33 UTC, spytheman commented
> probably will not need vote due to #11540?

I also hope so.

2021-09-20 11:10 UTC, ChAoSUnItY commented
Seems that multi-level generic fix PR still cannot make `>>>` possible to implement based on my knowledge of lexing. We might take the highest vote of operator candidate (possibly `+>>`) as our final version of unsigned right shift operator. I'll later update it in scanner files.

2021-09-20 20:34 UTC, SleepyRoy commented
@ChAoSUnItY Good work! With my PR the lex of `>>>`, `>>>=` should not be too hard. Feel free to read comments I left you under my PR. Good luck!

2021-09-21 11:02 UTC, merged