strconv: fix bitwise format with ~ operator with -ve sign
vlang/v pull request #12669
Opened 2021-12-03 12:40 UTC by windson

This is to fix https://github.com/vlang/v/issues/12665.
Details below:
I see formatting problem with bitwise ~ operator when there is a -ve sign.

**V doctor:**
```
OS: windows, Microsoft Windows 10 Enterprise v17763 64-bit
Processor: 8 cpus, 64bit, little endian, Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.

 cmd: cc --version

getwd: C:\sources\vv
vmodules: C:\Users\navulep\.vmodules
vroot: C:\v
vexe: C:\v\v.exe
vexe mtime: 2021-12-03 07:22:53
is vroot writable: true
is vmodules writable: true
V full version: V 0.2.4 be5446b

Git version: git version 2.33.0.windows.2
Git vroot status: weekly.2021.48-4-gbe5446bf
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 0f5168cd
```

**What did you do?**
`v -g -o vdbg cmd/v && vdbg bitbet.v`
```v
a := 6
println(~a) // -7
println("${~a:b}") // -111
println("${a:08b}") // 00000110
println("${~a:08b}") // 0000-111 <-- wrongly formatted

```

**What did you expect to see?**

```
-00000111
```

**What did you see instead?**
```
0000-111
```

2021-12-03 18:22 UTC, spytheman commented
I think there is a problem with this:
```v
a := -77
println("${a: 20}")  // '                 -77'
println("${a: 20b}") // '-             1001101'
println("${a: 20x}") // '-                  4d'
```

2021-12-03 18:39 UTC, andrew-ld requested changes

2021-12-03 18:39 UTC, andrew-ld commented on vlib/builtin/string_interpolation.v
> +					if d < 0 {
wrong

2021-12-03 22:46 UTC, penguindark commented
Then what behaviour do we need to follow?
I mimicked the previous system behaviour , errors included ;) , to keep compatibility as we decided before the switch.
The change is not a big problem from the source code point of view but it will be a breking change.

2021-12-03 23:14 UTC, penguindark commented
this code in `string_interpolation.v` from the line *254* can solve the bug:
```v
} else {
	// binary, we use 3 for binary
	if base == 3 {
		base = 2
	}
	if d < 0 && pad_ch != ` ` {
		d = -d
		mut hx := strconv.format_int(d, base)
		if upper_case {
			tmp := hx
			hx = hx.to_upper()
			tmp.free()
		}
		sb.write_b(`-`)
		if width == 0 {
			sb.write_string(hx)
		} else {
			strconv.format_str_sb(hx, bf, mut sb)
		}
		hx.free()
	} else {
		mut hx := strconv.format_int(d, base)
		if upper_case {
			tmp := hx
			hx = hx.to_upper()
			tmp.free()
		}
		if width == 0 {
			sb.write_string(hx)
		} else {
			strconv.format_str_sb(hx, bf, mut sb)
		}
		hx.free()
	}
}
```

2021-12-04 00:16 UTC, JalonSolov commented
That is correct.  The sign must be the first non-whitespace character immediately before the number, however long the number may be.  If the number is padded with leading zeroes, those still count as part of the number, so the sign goes before the padding.

2021-12-04 03:22 UTC, penguindark commented on vlib/builtin/string_interpolation.v
> +						hx = hx.replace('-', '')
Using replace here will slow a lot the function.

2021-12-04 10:03 UTC, spytheman commented
> '                 -77'
> '            -1001101'
> '                 -4d'
> '-0000000000000000077'
> '-00000000000001001101'
> '-0000000000000000004d'
imho in the last 2 cases, the width of the padding is 1 character more than needed

2021-12-04 11:12 UTC, spytheman commented
I have a fix, based on what @penguindark proposed, for all the test cases I tried. I'll push it soon.

2021-12-04 11:17 UTC, spytheman commented
Fixed in d59aa14.

2021-12-04 12:52 UTC, closed without merging

2021-12-04 14:50 UTC, penguindark commented
@spytheman good :)

2021-12-06 09:05 UTC, windson commented
@spytheman Thank you for fix.