cgen: check call argument on methods
vlang/v pull request #12965
Opened 2021-12-25 20:53 UTC by trufae

Fixes this crash:

```
$ cat a.v
fn JS.Foo.bar() bool

JS.Foo.bar(123)
$
$ v a.v
V panic: array.get: index out of range (i == 0, a.len == 0)
v hash: 3528239
0   v                                   0x000000010ddc2f4c array_get + 252
1   v                                   0x000000010deb05d2 v__checker__Checker_fn_call + 16498
2   v                                   0x000000010dea6f17 v__checker__Checker_call_expr + 119
3   v                                   0x000000010de821a5 v__checker__Checker_expr + 3685
4   v                                   0x000000010de96852 v__checker__Checker_stmt + 2130
5   v                                   0x000000010dea6d71 v__checker__Checker_stmts_ending_with_expression + 289
6   v                                   0x000000010debbe26 v__checker__Checker_stmts + 86
7   v                                   0x000000010debf0e1 v__checker__Checker_fn_decl + 12961
8   v                                   0x000000010de96aa8 v__checker__Checker_stmt + 2728
9   v                                   0x000000010de95ef7 v__checker__Checker_check + 2103
10  v                                   0x000000010de9784a v__checker__Checker_check_files + 378
11  v                                   0x000000010e0234ae v__builder__Builder_middle_stages + 222
12  v                                   0x000000010e025473 v__builder__Builder_front_and_middle_stages + 147
13  v                                   0x000000010e03d622 v__builder__cbuilder__gen_c + 66
14  v                                   0x000000010e03d466 v__builder__cbuilder__build_c + 342
15  v                                   0x000000010e03d2fe v__builder__cbuilder__compile_c + 526
16  v                                   0x000000010e036afe v__builder__compile + 446
17  v                                   0x000000010e03ed72 main__main + 5618
18  v                                   0x000000010e042c2a main + 42
19  v                                   0x000000010ddbeb64 start + 52
$
```

2021-12-25 20:55 UTC, trufae commented
The JS statments shouldnt be allowed with the cgen, so maybe this patch should cut the path earlier. but still this loop had a bug accessing index -1 when the function definition have 0 arguments, which is fine with the js backend. 

With this patch, the a.v compiles as expected in all the js backends, but fails with the cgen with a proper v-level error

2021-12-25 21:01 UTC, medvednikov commented
> `if !is_js_backend`

This is already checked in non JS backends, isn't it?

```
error: expected 0 arguments, but got 1
    1 | fn foo() {}
    2 |
    3 | foo(1)
      |     ^
    4 |
    5 |
/tmp $ cat a.v
fn foo() {}

foo(1)
```

2021-12-26 00:55 UTC, trufae commented
Note the `JS.` prefix in the function signature

2021-12-26 03:51 UTC, playXE requested changes

2021-12-26 03:51 UTC, playXE commented on vlib/v/checker/fn.v
> +	is_js_backend := match c.pref.backend {
there is `.is_js()` method for Backend type. Use it.

2021-12-26 09:53 UTC, merged