os: add font module, move from gg
vlang/v pull request #13144
Opened 2022-01-12 12:45 UTC by Larpon

As discussed on [Discord](<https://discord.com/channels/592103645835821068/592320321995014154/930791812514328576>) this PR will move a few font related functions out in it's own module under `os.font`.

One of the reasons is that fonts and font paths aren't always solely needed for graphical apps - so importing `gg` everytime you need to get a default font is not good in systems that doesn't need (or even have) graphics available.

A relevant example is currently if you want to get a default font for your `vlang/sdl` app you'll need to import all of `gg` as well - although we only need `sdl`.

2022-01-12 12:54 UTC, Larpon commented
V UI fixes <https://github.com/vlang/ui/pull/411>

2022-01-12 13:10 UTC, spytheman commented on examples/hot_reload/graph.v
> +		font_path: font.system_path()
actually this can be removed entirely - that example does not draw text

2022-01-12 13:10 UTC, spytheman commented on examples/gg/worker_thread.v
> +		font_path: font.system_path()
can be removed, since the default is fine

2022-01-12 13:11 UTC, spytheman commented on examples/hot_reload/bounce.v
>  	)
can be removed too

2022-01-12 13:12 UTC, spytheman requested changes
Good work.

2022-01-12 13:26 UTC, Larpon commented on examples/hot_reload/graph.v
> +		font_path: font.system_path()
Oh - good point

2022-01-12 13:37 UTC, JalonSolov commented on vlib/os/font/font.v
> +pub fn system_path() string {
Would it be simpler to have `path` instead of `system_path`?  It just "feels" awkward to have `system_path`, since you know it has to be be a path accessible on the system... of course, what if it's out on the 'net somewhere?

2022-01-12 13:39 UTC, Larpon commented on vlib/os/font/font.v
> +pub fn system_path() string {
Yeah it's a little tricky to find the right names (same with the get_path_variant)

2022-01-12 13:50 UTC, Larpon commented on vlib/os/font/font.v
> +pub fn system_path() string {
I've added documentation to at least make more clear what the function does in c6f58cb

2022-01-12 15:09 UTC, JalonSolov commented on vlib/os/font/font.v
> +pub fn system_path() string {
Maybe `font_path`, then?  Or even `path_to_font`?

2022-01-12 16:32 UTC, spytheman commented on vlib/os/font/font.v
> +pub fn system_path() string {
`font.default()` ?

2022-01-12 16:42 UTC, JalonSolov commented on vlib/os/font/font.v
> +pub fn system_path() string {
:shrug:

2022-01-12 18:22 UTC, Larpon commented on vlib/os/font/font.v
> +pub fn system_path() string {
`font.default()` makes sense to me.

 Q: How do I get the system default font?
A: Use `os.font.default()`

2022-01-12 18:23 UTC, Larpon commented on vlib/os/font/font.v
> +pub fn system_path() string {
Although it says nothing about it being an absolite path to a .ttf 😅

2022-01-12 19:57 UTC, JalonSolov commented on vlib/os/font/font.v
> +pub fn system_path() string {
That'll be fine when it supports .otf, .woff, etc.  :-)

2022-01-13 08:17 UTC, Larpon commented on vlib/os/font/font.v
> +pub fn system_path() string {
Right, done in c07fa48 :)

2022-01-13 08:17 UTC, Larpon commented on vlib/os/font/font.v
> +pub fn system_path() string {
V UI patch PR is also updated

2022-01-13 10:16 UTC, merged