checker: check if the generics value has the same types
vlang/v pull request #13718
Opened 2022-03-11 19:29 UTC by vincenzopalazzo

Fixes https://github.com/vlang/v/issues/13486

This was fun :) I will give a run with the CI and after that, I will check the comments style.

In addition, I would like to keep the commits explanation here because can be a very difficult drive in the type checking with the code that keeps changing.

Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>

2022-03-11 20:07 UTC, vincenzopalazzo commented
Now this introduces this regression

```
==================
/tmp/v/test_session_272222748866/generics_fn_called_variadic_arg_mismatch.9008882186794056887.tmp.c:11340: error: cannot convert 'struct array' to 'int'
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
============

diff: 
--- /home/runner/.cache/01FXX7PEG83GEF8N4F5TJA46JH/449386083435.expected.txt	2022-03-11 19:36:10.497493099 +0000
+++ /home/runner/.cache/01FXX7PEG83GEF8N4F5TJA46JH/449386083435.found.txt	2022-03-11 19:36:10.497493099 +0000
@@ -1,7 +1,15 @@
-vlib/v/checker/tests/generics_fn_called_variadic_arg_mismatch.vv:12:16: error: cannot use `[]int` as `int` in argument 1 to `max`
-   10 |
-   11 | fn main() {
-   12 |     b := max<int>([1, 2, 3, 4])
-      |                   ~~~~~~~~~~~~
-   13 |     println(b)
-   14 | }
\ No newline at end of file
```

I will look into it later, and try to make this solution safe

2022-03-17 21:53 UTC, vincenzopalazzo commented
This PR introduces the fix on the checker, where the compiler is comparing two generics with a concrete type with a generics without a concrete type.

We can not avoid this check, because we need to make some comparison between types like `Type<T> vs &Type<T>`

In addition, this shows that maybe we need to store somewhere the type of the node also if it has no generic type, but this required future research.

2022-03-21 19:23 UTC, spytheman commented on vlib/v/ast/types.v
> +		embed_name = embed_name.split('<')[0]
```suggestion
		embed_name = embed_name.all_before('<')
```

2022-03-21 19:24 UTC, spytheman commented on vlib/v/ast/types.v
> +	return result.split('<')[0]
```suggestion
	return result.all_before('<')
```

2022-03-21 19:26 UTC, spytheman commented on vlib/v/checker/fn.v
> +				*/
that is not needed

2022-03-21 19:30 UTC, spytheman commented
The `vls` build is failing with errors like these:
```
server/window.v:29:12: error: cannot use 
`NotificationMessage<lsp.ShowMessageRequestParams>` as
`jsonrpc.NotificationMessage<>`
 in argument 1 to `server.Vls.notify`
   27 | 
   28 | fn (mut ls Vls) show_message_request(message string, 
actions []lsp.MessageActionItem, typ lsp.MessageType) {
   29 |     ls.notify(jsonrpc.NotificationMessage<lsp.ShowMessageRequestParams>{
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   30 |         method: 'window/showMessageRequest'
   31 |         params: lsp.ShowMessageRequestParams{
```

I think these should be allowed.

`NotificationMessage<lsp.ShowMessageRequestParams>` is clearly a specific instance of the more general
`jsonrpc.NotificationMessage<>` type.

2022-03-21 19:34 UTC, spytheman commented
1. `&Type<T> != Type<T>`

2. `Type<Specific> == Type<T>`

I think the problem is that this PR tries to check for 1 (which is good), but in addition disallows 2 (which is a problem, since real projects use it).

2022-03-21 19:36 UTC, spytheman requested changes
The VLS code should not be broken - the error messages there are a symptom that the check is too strict.

2022-03-21 23:20 UTC, vincenzopalazzo commented
>I think the problem is that this PR tries to check for 1 (which is good), but in addition disallows 2 (which is a problem, since real projects use it).

IMHO, in this case, I think that the problem is a different one, In particular, in the AST we don't have any way to store the root generics type and we need to get this type from the `type_to_str` function.
In this case return two different type `NotificationMessage<lsp.ShowMessageRequestParams>`  and `jsonrpc.NotificationMessage<>`.

So the strict check that we have (point 2), we are checking that only the type name without generics type, so in this case, we have two the correct check, but we have the wrong type string, and I'm not able to catch this error, maybe it is another unrelated bug?

```
        got_typ_sym := c.table.sym(got)
        // 1. received -> NotificationMessage<lsp.ShowMessageRequestParams>
	got_typ_str := c.table.type_to_str(got.clear_flag(.variadic))
	expected_typ_sym := c.table.sym(expected_)
        // 2. received -> jsonrpc.NotificationMessage<>
	expected_typ_str := c.table.type_to_str(expected.clear_flag(.variadic))

        // got_typ_str != expected_typ_str different but equal root type
	if got_typ_sym.symbol_name_except_generic() == expected_typ_sym.symbol_name_except_generic() {
		// Check if we are making a comparison between two different types of
		// the same type like `Type<int> and &Type<>`
		clean_got_typ := c.table.clean_generics_type_str(got.clear_flag(.variadic))
		clean_expected_typ := c.table.clean_generics_type_str(expected.clear_flag(.variadic))
		if (got.is_ptr() != expected.is_ptr()) || (clean_got_typ != clean_expected_typ) {
			return error('cannot use `$got_typ_str` as `$expected_typ_str`')
		}
		return
	}
```

With the second check removed there is this check missing

```
FAIL  [354/732]  2191.294 ms vlib/v/checker/tests/generics_fn_called_variadic_arg_mismatch.vv
============
failed cmd: '/home/vincent/Github/vlang/v/v' -prod 'vlib/v/checker/tests/generics_fn_called_variadic_arg_mismatch.vv'
expected_out_path: vlib/v/checker/tests/generics_fn_called_variadic_arg_mismatch.out
============
expected:
vlib/v/checker/tests/generics_fn_called_variadic_arg_mismatch.vv:12:16: error: cannot use `[]int` as `int` in argument 1 to `max`
   10 |
   11 | fn main() {
   12 |     b := max<int>([1, 2, 3, 4])
      |                   ~~~~~~~~~~~~
   13 |     println(b)
   14 | }
============
found:
==================
/tmp/v/test_session_36316921911651/generics_fn_called_variadic_arg_mismatch.13504068623266582714.tmp.c: In function ‘main__main’:
/tmp/v/test_session_36316921911651/generics_fn_called_variadic_arg_mismatch.13504068623266582714.tmp.c:11357:82: error: incompatible types when initializing type ‘int’ using type ‘array’ {aka ‘struct array’}
11357 |  int b = main__max_T_int(new_array_from_c_array(1, 1, sizeof(int), _MOV((int[1]){new_array_from_c_array(4, 4, sizeof(int), _MOV((int[4]){1, 2, 3, 4}))})));
      |                                                                                  ^~~~~~~~~~~~~~~~~~~~~~
...
==================
(Use `v -cg` to print the entire error message)

builder error:
==================
C error. This should never happen.

This is a compiler bug, please report it using `v bug file.v`.

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang

```
	

We could separate the check between method_call and function_call but IMHO this is not a solution, because it is a type check leak, so my suggestion is to try to retrieve the root generics type and check it.
it 
ping @spytheman @yuyi98

2022-03-23 06:02 UTC, spytheman commented on vlib/v/checker/tests/generic_parameter_on_method.vv
> +struct ConatinerType<T> {
```suggestion
struct ContainerType<T> {
```

2022-03-23 06:03 UTC, spytheman commented on vlib/v/checker/tests/generic_parameter_on_method.vv
> +fn (instance &ConatinerType<T>) contains(typ Type<T>) {
```suggestion
fn (instance &ContainerType<T>) contains(typ Type<T>) {
```

2022-03-23 06:03 UTC, spytheman commented on vlib/v/checker/tests/generic_parameter_on_method.vv
> +	con := ConatinerType<int>{typ: &Type<int>{0}}
```suggestion
	con := ContainerType<int>{typ: &Type<int>{0}}
```

2022-03-23 06:04 UTC, spytheman commented on vlib/v/checker/tests/generic_parameter_on_method.out
> +vlib/v/checker/tests/generic_parameter_on_method.vv:15:15: error: cannot use `&Type<int>` as `Type<>` in argument 1 to `ConatinerType<int>.contains`
```suggestion
vlib/v/checker/tests/generic_parameter_on_method.vv:15:15: error: cannot use `&Type<int>` as `Type<>` in argument 1 to `ContainerType<int>.contains`
```

2022-03-23 06:04 UTC, spytheman commented on vlib/v/checker/tests/generic_parameter_on_method.out
> +   14 |     con := ConatinerType<int>{typ: &Type<int>{0}}
```suggestion
   14 |     con := ContainerType<int>{typ: &Type<int>{0}}
```

2022-03-23 07:13 UTC, merged