time: add test to reproduce the issue #13828
vlang/v pull request #13861
Opened 2022-03-29 18:54 UTC by vincenzopalazzo

Fixes https://github.com/vlang/v/issues/13828

On a Linux machine, the local call adds 2 hours each call to the now() result.

I'm adding this test right now because I need to discovered where is the leak

Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>

2022-03-29 21:04 UTC, vincenzopalazzo commented on vlib/time/time_nix.c.v
> +fn C.localtime_r(t &C.time_t, &C.tm)
pushed thanks, I was reintroducing it because we use this function in other place I noted

2022-03-29 21:07 UTC, vincenzopalazzo commented
OK, I rebased and fixed the commits, we need to see what happens on windows inside the CI!

2022-03-29 22:59 UTC, spytheman requested changes
Do use `localtime_r`, `localtime` is not re-entrant.
https://linux.die.net/man/3/localtime_r

> The  four functions asctime(), ctime(), gmtime(), and localtime() return a pointer to static data and hence are not thread-safe.  The  thread-safe  versions,  asctime_r(), ctime_r(), gmtime_r(), and localtime_r(), are specified by SUSv2.

Also see this:
> According  to  POSIX.1-2001, localtime() is required to behave as though tzset(3) was called, while localtime_r() does not  have  this  requirement.   For  portable  code, tzset(3) should be called before localtime_r(). 

... where:
`       void tzset (void);`

https://pubs.opengroup.org/onlinepubs/9699919799/functions/localtime.html
> APPLICATION USAGE
>    The localtime_r() function is thread-safe and returns values in a user-supplied buffer instead of possibly using a static data area that may be overwritten by each call.

2022-03-29 23:04 UTC, spytheman commented on vlib/time/time_windows.c.v
> +		millisecond: u16(t.microsecond / 1000)
```suggestion
		millisecond: u16(t.millisecond)
```

2022-03-30 07:35 UTC, vincenzopalazzo commented on vlib/time/time_nix.c.v
> +// localtime instead of localtime_r
Damn, I didn't think about thread-safe. Sorry about that. 

BTW, good catch

2022-03-31 16:43 UTC, spytheman commented on vlib/time/time.c.v
> +fn convert_ctime(t C.tm, microsecond int, is_local bool) Time {
All usages of `convert_ctime` are with true as the last argument. Will there be a situation, where someone wants to pass false there?

2022-03-31 16:44 UTC, spytheman commented on vlib/time/time.c.v
> +fn convert_ctime(t C.tm, microsecond int, is_local bool) Time {
btw, `vlib/time/time_solaris.c.v:13:return convert_ctime(loc_tm, int(ts.tv_nsec / 1000))`
^ this is not changed.

2022-03-31 16:47 UTC, spytheman requested changes
Please restore the 2 argument version of `convert_ctime`.

2022-03-31 16:49 UTC, vincenzopalazzo commented on vlib/time/time.c.v
> +fn convert_ctime(t C.tm, microsecond int, is_local bool) Time {
mh I think yes, like in this case

```
// local returns t with the location set to local time.
pub fn (t Time) utc() Time {
	loc_tm := C.tm{}
	C.gmtime_r(voidptr(&t.unix), &loc_tm)
	return convert_ctime(loc_tm, t.microsecond, false)
}
```

2022-03-31 16:53 UTC, vincenzopalazzo commented on vlib/time/time.v
> +	// call to `time.now().local().local()`
I agree now when I know what local does, but I think having a couple of comment line make the code more user friendly, if there no strong opinion, I would like to keep it

2022-03-31 16:58 UTC, vincenzopalazzo commented
Review applied and I think more back to two-argument it is a good choice!

Trivail rebase on master

2022-03-31 21:11 UTC, merged