time: implement Time.strftime(fmt string) as a wrapper for strftime(3)
vlang/v pull request #13898
Opened 2022-04-01 20:12 UTC by CRKatri

I have not tested this on Windows, so if the CI fails I will have to do that. It should work though, as it is entirely POSIX.

2022-04-01 21:19 UTC, vincenzopalazzo requested changes
looks like that this function exist also in Windows https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l?view=msvc-170

but I need to check better

2022-04-01 21:19 UTC, vincenzopalazzo commented on vlib/time/time.c.v
>  fn C.localtime(t &C.time_t) &C.tm
```suggestion
```

We can remove it and use only `localtime_r` it is thread safe

2022-04-01 21:24 UTC, vincenzopalazzo commented on vlib/time/time.c.v
>  fn C.localtime(t &C.time_t) &C.tm
In addition, you may want to move the function also in https://github.com/vlang/v/blob/master/vlib/time/time_windows.c.v for a better separation of concerns?

2022-04-02 02:58 UTC, CRKatri commented on vlib/time/time.c.v
>  fn C.localtime(t &C.time_t) &C.tm
`localtime_r()` isn't available on windows, only `localtime()` and `localtime_s()`

2022-04-02 15:33 UTC, spytheman approved these changes
Good work.

2022-04-02 15:33 UTC, merged