checker: disallow confusing expression: smaller unsigned type == signed
vlang/v pull request #13967
Opened 2022-04-07 18:17 UTC by ntrel

Otherwise C will evaluate `u16(-1) == -1` as false due to promoting u16 -> int. 
<, > etc will be checked in a separate pull.
Also disallow unsigned == negative literal. This was already disallowed for <, >, <=, >=.

Fixes https://github.com/vlang/v/issues/13955.

2022-04-07 19:53 UTC, JalonSolov commented
`u16(-1) == -1` _should_ be false, as an unsigned value can never be negative.

2022-04-07 21:34 UTC, Larpon commented on vlib/toml/scanner/scanner.v
> +pub fn (s &Scanner) peek(n int) u32 {
This function can return `-1` (`end_of_file` constant) - I that's why `int` is used.

2022-04-08 12:42 UTC, vincenzopalazzo requested changes
I don't like the idea of promotion type, this is exactly what C does, "You dive the wrong type, and I will give a random number that is wrong"

What I would like to expect here is a checker error, that tell the user "Hey this is a invalid type"

2022-04-08 12:42 UTC, vincenzopalazzo commented on vlib/toml/scanner/scanner.v
> +pub fn (s &Scanner) peek(n int) u32 {
+1

2022-04-08 12:42 UTC, vincenzopalazzo commented on vlib/v/checker/checker.v
> +					// prevent e.g. `u16(-1) == int(-1)` which is false in C
```suggestion
					// prevent e.g. `u16(-1) == int(-1)` which is false in C
```

This is always false, not only in C

2022-04-08 12:48 UTC, vincenzopalazzo commented
failure test seems unrelated, this looks like a wrong comparison in the ttf vlib.

```
 FAIL  [942/942]   263.661 ms vlib/x/ttf/ttf_test.v
vlib/x/ttf/render_bmp.v:781:12: error: `int` cannot be compared with `u16`
  779 |         }
  780 | 
  781 |         if count == glyph.contour_ends[c] {
      |                  ~~
  782 |             // dprintln("count == glyph.contour_ends[count]")
  783 |             if s == 2 { // final point was off-curve. connect to start
```

This is the check that I would like to see from a compiler point of view :) great job

2022-04-09 10:51 UTC, ntrel commented on vlib/toml/scanner/scanner.v
> +pub fn (s &Scanner) peek(n int) u32 {
@Larpon The docs say it "returns the character code from the input text" or end_of_text. I assume it is used mainly to compare with byte, which is unsigned. So if I'm correct, to avoid the most casts, returning unsigned and making end_of_file unsigned is the best solution.

2022-04-09 10:53 UTC, ntrel commented on vlib/v/checker/checker.v
> +					// prevent e.g. `u16(-1) == int(-1)` which is false in C
I'm assuming all signed/unsigned comparisons will become an error in V.

2022-04-09 11:05 UTC, ntrel commented
> `u16(-1) == -1` _should_ be false, as an unsigned value can never be negative.

It should be an error, hence this pull. Otherwise there is no point in the comparison if the types mean it is always false.

2022-04-09 11:07 UTC, ntrel commented
> I don't like the idea of promotion type, this is exactly what C does

This pull makes some int promotion cases (the worst ones IMO) an error instead.

2022-04-09 11:20 UTC, Larpon commented on vlib/toml/scanner/scanner.v
> +pub fn (s &Scanner) peek(n int) u32 {
Fully agree that less casts are better, and IIRC I use `end_of_text` consistently - so it shouldn't be problem - I merely gave a heads up because the value of `end_of_text` is still, [currently](https://github.com/vlang/v/pull/13967/files#diff-8a65223c95935b8ffeaccee61b280f7d5da77554634cd9174360ff584220438eL13), `-1` :slightly_smiling_face: If that is changes to something else it should still work, agreed

(don't know if we have "`u32_max`" or similar which would also be a good candidate)

2022-04-10 11:16 UTC, ntrel commented on vlib/toml/scanner/scanner.v
> +pub fn (s &Scanner) peek(n int) u32 {
Thanks. I've split this change out to #13998 for better git history.

2022-04-10 12:32 UTC, medvednikov commented
Indeed, like in Go, `u32(-1)` shouldn't compile:

```
cannot convert -1 (untyped int constant) to type uint16
```

2022-04-10 13:28 UTC, Larpon commented on vlib/toml/scanner/scanner.v
> +pub fn (s &Scanner) peek(n int) u32 {
Awesome - thanks for fixing the scanner tests :sweat_smile:

2022-04-10 13:37 UTC, JalonSolov commented
The equivalent to `u32(-1)` is used a _lot_ in other languages.

There is a simple way to achieve the same thing, but for some reason, most people have either forgotten it, or never learned it... `u32(~0)`.

2022-04-11 13:32 UTC, JalonSolov commented on vlib/toml/scanner/scanner.v
> +	end_of_text  = 4294967295
```suggestion
	end_of_text  = ~0
```

2022-04-11 19:19 UTC, JalonSolov commented on vlib/toml/scanner/scanner.v
> +	end_of_text  = 4294967295
`u32(~0)` is unsigned, and is a 32-bit value.

2022-04-12 16:27 UTC, spytheman commented on vlib/szip/szip.v
>  	}
I am not sure what is that supposed to do 🤔, it seems dead code to me in both versions.

2022-04-12 16:37 UTC, merged