correct date in smtp body
vlang/v pull request #14326
Opened 2022-05-06 18:14 UTC by WoodyAtHome

- 'ZZ' time zone: GMX, a very popular german email server relies on the 'ZZ' time zone info. Otherwise the mail body is rejected (see also RFC2822, 3.3)
- Content type for plain text should be UFT-8 because V also operates with UTF-8, for html I don't know

2022-05-07 14:19 UTC, Hunam6 requested changes

2022-05-07 14:19 UTC, Hunam6 commented on vlib/net/smtp/smtp.v
> +		sb.write_string('Content-Type: text/plain; charset=UTF-8')
Content type for HTML should be UTF-8 too.

2022-05-07 22:18 UTC, Hunam6 approved these changes
Good work, it removes the previous hacky system too

2022-05-07 22:20 UTC, Hunam6 commented
Cirrus CI stay cancelled, no idea why

2022-05-08 06:15 UTC, merged

2022-05-08 06:16 UTC, medvednikov commented
Thanks for the fix @WoodyAtHome !