Add Set with add, remove, exists and size methods
vlang/v pull request #14853
Opened 2022-06-26 00:08 UTC by vladimirmyshkovski

Just simple implementation of Set.

I think the following implementations should be added in the future:

#### Core set-theoretical operations

`union(S,T)`: returns the [union](https://en.wikipedia.org/wiki/Union_(set_theory)) of sets `S` and `T`.
`intersection(S,T)`: returns the [intersection](https://en.wikipedia.org/wiki/Intersection_(set_theory)) of sets `S` and `T`.
`difference(S,T)`: returns the [difference](https://en.wikipedia.org/wiki/Difference_(set_theory)) of sets `S` and `T`.
`subset(S,T)`: a predicate that tests whether the set `S` is a [subset](https://en.wikipedia.org/wiki/Subset) of set `T`.
 
 #### Static sets
 
`is_element_of(x,S)`: checks whether the value `x` is in the set `S`.
`is_empty(S)`: checks whether the set `S` is empty.
`iterate(S)`: returns a function that returns one more value of `S` at each call, in some arbitrary order.
`enumerate(S)`: returns a list containing the elements of `S` in some arbitrary order.
`build(x1,x2,…,xn,)`: creates a set structure with values `x1`,`x2`,...,`xn`.
`create_from(collection)`: creates a new set structure containing all the elements of the given [collection](https://en.wikipedia.org/wiki/Collection_(abstract_data_type)) or all the elements returned by the given [iterator](https://en.wikipedia.org/wiki/Iterator).

2022-06-26 16:36 UTC, Hunam6 commented
Why not just use a `map` to make a `Set`? What is/are the use(s) of using a separate type?

2022-06-26 17:15 UTC, vladimirmyshkovski commented
> Why not just use a `map` to make a `Set`? What is/are the use(s) of using a separate type?

I don't know for sure how `map` is implemented in `V`, but, in a number of other languages, `map` is less productive than array.

Also, a number of additional functions will make this type more convenient to use in specific cases. 


In addition, I saw that in the `README.md` package `datatypes`, there is a type `Set`, which someone considered necessary to implement. I took it as _welcome to contribution_ :-)

2022-06-26 17:27 UTC, Hunam6 commented
Okay 👌

2022-06-27 01:17 UTC, Hunam6 commented on vlib/datatypes/set.v
> +module set
This isn't possible, in V a folder = a module, see https://github.com/vlang/v/blob/master/doc/docs.md#modules

2022-06-27 01:17 UTC, Hunam6 commented on vlib/datatypes/set_test.v
> +module set
same here

2022-06-27 01:31 UTC, medvednikov commented on vlib/datatypes/set.v
> +module set
Indeed. For example datatypes.Heap:

![image](https://user-images.githubusercontent.com/687996/175843965-e7fba312-3316-4e35-bc09-f06196141718.png)

2022-06-27 01:39 UTC, penguindark commented
> > Why not just use a `map` to make a `Set`? What is/are the use(s) of using a separate type?
> 
> I don't know for sure how `map` is implemented in `V`, but, in a number of other languages, `map` is less productive than `array`.
> 
> Also, a number of additional functions will make this type more convenient to use in specific cases.
> 
> In addition, I saw that in the `README.md` package `datatypes`, there is a type `Set`, which someone considered necessary to implement. I took it as _welcome to contribution_ :-)

Have you tried to benchmark your solution vs map solution?

2022-06-27 01:59 UTC, ulises-jeremias commented
I was going to suggest the same as the rest did. Using a map solution will be better in term of performance! Just for reference, here there is a Set implementation I did in the past in PHP 😅 https://github.com/MBHFramework/structures/blob/385e1e3d49d8b953fa2354a6b522a3cf6de4c24f/Mbh/Collection/Set.php#L26

2022-06-27 09:07 UTC, vladimirmyshkovski commented on vlib/datatypes/set.v
> +	elements []T
Okay. I will soon present an implementation on `map` instead of `array`. 

But, in `Go` maybe something like `map[interface{}]struct{}`, we can store an empty structure as value, in `V` we need to store something like `int` as @ulises-jeremias  showed in the example, but wouldn't that lead to unnecessary memory usage?

2022-06-27 11:27 UTC, Hunam6 requested changes

2022-06-27 11:27 UTC, Hunam6 commented on vlib/datatypes/set.v
> +}
This function Is the equivalent as just writing `a := Set<int>{}`, it should be removed.

2022-06-27 11:27 UTC, Hunam6 commented on vlib/datatypes/set.v
> +}
Is this useful as you cannot set an initial capacity for a map?

2022-06-27 11:27 UTC, Hunam6 commented on vlib/datatypes/set.v
> +}
Why `.size()` instead of the more V-ish `.len()` or `.len`?

2022-06-27 11:27 UTC, Hunam6 commented on vlib/datatypes/set.v
> +}
Shouldn't the signature of the method be `fn (mut set Set<T>) remove(element T) ?`?

2022-06-27 11:27 UTC, Hunam6 commented on vlib/datatypes/set.v
> +	return set.elements.keys().filter(it != element)
Is this required as a map cannot have duplicate keys?

2022-06-27 11:27 UTC, Hunam6 commented on vlib/datatypes/set.v
> +// returns an arbitrary element of set
Precise if it's the first or last element added.

2022-06-27 11:27 UTC, Hunam6 commented on vlib/datatypes/set.v
> +	element := set.pick() or { return error('Failed to retrieve an arbitrary element') }
If you do not put an `or {}` here the error will be the one returned by `set.pick()`, much clearer IMO

2022-06-27 11:27 UTC, Hunam6 commented on vlib/datatypes/set.v
> +	set.elements = map[T]int{}
maybe use [`map.clear()`](https://modules.vlang.io/index.html#map.clear)

2022-06-27 11:27 UTC, Hunam6 commented on vlib/datatypes/set.v
> +}
This can probably be optimised by first checking the two lengths

2022-06-27 16:32 UTC, spytheman commented on vlib/datatypes/set.v
> +	}
Just one loop is enough, since you have already checked, that both maps have the same sizes:
`for k,_ in r.elements { l.elements[k] or { return false } }`

2022-06-27 16:34 UTC, spytheman commented on vlib/datatypes/set.v
> +	elements []T
You can use a `bool`, `u8` or an empty struct if you want, instead of int.

2022-06-27 17:26 UTC, vladimirmyshkovski commented
> I was going to suggest the same as the rest did. Using a map solution will be better in terms of performance! Just for reference, here there is a Set implementation I did in the past in PHP sweat_smile https://github.com/MBHFramework/structures/blob/385e1e3d49d8b953fa2354a6b522a3cf6de4c24f/Mbh/Collection/Set.php#L26
> 
> just for reference, using `map`, the set should be something like this:
> 
> ```v
> pub struct Set<T> {
> mut:
> 	table map[T]int // or map[T]bool or any type in the value
> }
> ```
> 
> then `Set` will be just a wrapper of `map` when the keys are the values of the Set and most of the operations will be really efficient

Maybe `voidptr` better than `int`?

2022-06-27 17:44 UTC, penguindark commented
> Maybe `voidptr` better than `int`?

voidptr can be 64bit, int is 32 vbit in V, you can save half the memory for each element.
otherwise you can use a simply u8 to reduce the memory footprint.

2022-06-27 18:28 UTC, vladimirmyshkovski commented
> > 
> 
> voidptr can be 64bit, int is 32 vbit in V, you can save half the memory for each element. otherwise you can use a simply u8 to reduce the memory footprint.

Perhaps it makes sense to take not only the type of value, but also the type of key?

```
pub struct Set<K, V> {
	// maximum number of values that Set<K, V> can hold.
	capacity int
mut:
	elements map[V]K
}
```

2022-06-27 21:41 UTC, penguindark commented
> Perhaps it makes sense to take not only the type of value, but also the type of key?

If this is a pure `set()` I don't think that the type of the value of the `map` has a meaning.
You can simply choice the smallest one like `u8`.

2022-06-28 00:49 UTC, ulises-jeremias commented
@vladimirmyshkovski I think there is no need of having a capacity for the Set

2022-06-28 06:35 UTC, ulises-jeremias commented on vlib/datatypes/set.v
> +}
I think we just need to remove the capacity from this struct

2022-06-28 12:39 UTC, vladimirmyshkovski commented
@ulises-jeremias 

What would be a better name for the method of adding elements from an array to a set? For example, in `Python` it is called `update`. I'm thinking about the name of the method that returns a copy of the set: `copy` or `clone`?

Also, `union` is a reserved name in `V` therefore, the method must be called something else. Right now I'm calling it `union_`.

2022-06-30 11:30 UTC, spytheman commented
> Also, `union` is a reserved name in `V` therefore, the method must be called something else. Right now I'm calling it `union_`.

The existing convention is to use `fn ... @union(...) ... {` for names that are also keywords, for example:
`vlib/sync/sync_default.c.v:93:pub fn (mut m Mutex) @lock() {
`vlib/net/common.v:31:fn @select(handle int, test Select, timeout time.Duration) ?bool {`
`vlib/net/unix/stream_nix.v:55:fn (mut s StreamSocket) @select(test Select, timeout time.Duration) ?bool {`

2022-06-30 11:32 UTC, spytheman commented on vlib/datatypes/set.v
> +	}
```suggestion
	set.elements[element] = 1
```

2022-06-30 11:34 UTC, spytheman commented on vlib/datatypes/set.v
> +fn (mut set Set<T>) update(elements []T) {
```suggestion
fn (mut set Set<T>) add_all(elements []T) {
```

2022-06-30 11:36 UTC, spytheman commented on vlib/datatypes/set.v
> +// returns true if the set is a subset.
```suggestion
// returns true if the set `r` is a subset of the set `l`.
```

2022-06-30 11:38 UTC, spytheman commented on vlib/datatypes/set_test.v
> +}
It may be good to have a test that uses `Set<int>`, since currently all of them use `Set<string>`.

2022-06-30 11:39 UTC, spytheman commented on vlib/datatypes/set.v
> +fn (mut l Set<T>) union_(r Set<T>) Set<T> {
`@union` or just `+` ?

2022-06-30 11:39 UTC, spytheman commented on vlib/datatypes/set.v
> +fn (mut l Set<T>) difference(r Set<T>) Set<T> {
just `-` instead of `difference` ?

2022-06-30 11:41 UTC, spytheman commented on vlib/datatypes/set.v
> +fn (mut set Set<T>) copy() Set<T> {
```suggestion
// copy returns a copy of the set.
fn (mut set Set<T>) copy() Set<T> {
```

2022-06-30 11:43 UTC, spytheman commented on vlib/datatypes/set.v
> +// updates the set from the array
```suggestion
// add_all adds the whole `elements` array to the set
```

2022-06-30 11:43 UTC, spytheman commented on vlib/datatypes/set.v
> +// returns the union of sets.
```suggestion
// @union returns the union of the two sets.
```

2022-06-30 12:22 UTC, penguindark commented on vlib/datatypes/set.v
> +fn (mut set Set<T>) size() int {
can we have the simply `.len` attribute like arrays?

2022-06-30 18:25 UTC, spytheman commented on vlib/datatypes/set.v
> +fn (mut set Set<T>) size() int {
The other data structures in that module (Queue, Stack, MinHeap, DoublyLinkedList) however already do have a .len() method, so yeah - it may be better to be .len() for consistency with them.

2022-06-30 21:34 UTC, penguindark commented on vlib/datatypes/set.v
> +fn (mut set Set<T>) size() int {
I've tried this example and it seem work.
maybe we can use the `.len` like the other stdlib base datatype?
```v


pub struct Set<T> {
mut:
	elements map[T]u8
	len int
}

// checks the element is exists.
fn (set Set<T>) exists(element T) bool {
	return element in set.elements
}

// adds the element to set, if it is not present already.
fn (mut set Set<T>) add(element T) {
	if element !in set.elements {
		set.elements[element] = u8(set.size() + 1)
		set.len++ 
	}
}

// removes the element from set.
fn (mut set Set<T>) remove(element T) {
	set.elements.delete(element)
	set.len--
}

// returns an arbitrary element of set, if set is not empty.
fn (mut set Set<T>) pick() ?T {
	for k, _ in set.elements {
		return k
	}
	return error('Set is empty.')
}

// returns the set consisting of all elements except for the arbitrary element.
fn (mut set Set<T>) rest() ?[]T {
	element := set.pick()?
	return set.elements.keys().filter(it != element)
}

// returns an arbitrary element and deleting it from set.
fn (mut set Set<T>) pop() ?T {
	element := set.pick()?
	set.elements.delete(element)
	set.len--
	return element
}

// delete all elements of set.
fn (mut set Set<T>) clear() {
	set.elements = map[T]u8{}
	set.len = 0
}

// checks whether the two given sets are equal (i.e. contain all and only the same elements).
fn (mut l Set<T>) equal(r Set<T>) bool {
	if l.elements.len != r.elements.len {
		return false
	}
	for e, _ in r.elements {
		if e !in l.elements {
			return false
		}
	}
	return true
}

// checks whether the set is empty.
fn (mut set Set<T>) is_empty() bool {
	return set.size() == 0
}

// returns the number of elements.
fn (mut set Set<T>) size() int {
	return set.elements.len
}

// returns a copy of the set.
fn (mut set Set<T>) copy() Set<T> {
	return Set<T>{
		elements: set.elements.clone()
		len: set.len
	}
}

// updates the set from the array
fn (mut set Set<T>) update(elements []T) {
	for element in elements {
		set.add(element)
	}
}

// returns the union of sets.
fn (mut l Set<T>) union_(r Set<T>) Set<T> {
	mut set := l
	for e, _ in r.elements {
		set.add(e)
	}
	return set
}

// returns the intersection of sets.
fn (mut l Set<T>) intersection(r Set<T>) Set<T> {
	mut set := l
	for e, _ in l.elements {
		if !r.exists(e) {
			set.remove(e)
		}
	}
	for e, _ in r.elements {
		if !l.exists(e) {
			set.remove(e)
		}
	}
	return set
}

// returns the difference of sets.
fn (mut l Set<T>) difference(r Set<T>) Set<T> {
	mut set := l
	for e, _ in l.elements {
		if r.exists(e) {
			set.remove(e)
		}
	}
	return set
}

// returns true if the set is a subset.
fn (mut l Set<T>) subset(r Set<T>) bool {
	for e, _ in r.elements {
		if e !in l.elements {
			return false
		}
	}
	return true
}

fn main(){
	mut a := Set<string>{}
	a.add("a")
	a.add("b")
	a.remove("a")
	println(a.len)
	println(a)
}
```

2022-07-01 05:31 UTC, spytheman commented on vlib/datatypes/set.v
> +fn (mut set Set<T>) size() int {
As you showed in the code, you will need to update the .len field in addition to the map ops, and risk them getting out of sync if one of the methods does not do it.

Will external users of this datastructure need .len access often?

2022-07-01 10:50 UTC, Hunam6 commented on vlib/datatypes/set.v
> +fn (mut set Set<T>) size() int {
As for myself, I agree with @penguindark

2022-07-01 10:53 UTC, Hunam6 commented on vlib/datatypes/set.v
> +fn (mut l Set<T>) union_(r Set<T>) Set<T> {
`+` looks great

2022-07-01 10:53 UTC, Hunam6 commented on vlib/datatypes/set.v
> +fn (mut l Set<T>) difference(r Set<T>) Set<T> {
`-` looks great

2022-07-01 10:53 UTC, Hunam6 commented on vlib/datatypes/set.v
> +fn (mut set Set<T>) size() int {
As for myself, I agree with @penguindark

2022-07-02 19:58 UTC, vladimirmyshkovski commented on vlib/datatypes/set.v
> +fn (mut set Set<T>) size() int {
Is it possible to set a reference to `u8` the last of the `elements`?

2022-07-02 19:58 UTC, vladimirmyshkovski commented on vlib/datatypes/set.v
> +fn (mut l Set<T>) difference(r Set<T>) Set<T> {
It's not possible.

2022-07-02 20:39 UTC, vladimirmyshkovski commented on vlib/datatypes/set_test.v
> +}
Tests with `int` failed with error:  `/tmp/v/test_session_2138467265856/set_test.16425039264974648067.tmp.c:15464: error: cannot convert 'int' to 'struct string'`

2022-07-02 20:51 UTC, vladimirmyshkovski commented on vlib/datatypes/set.v
> +	set.elements = map[T]int{}
@Hunam6 What do you think about it?

2022-08-13 05:23 UTC, ulises-jeremias commented on vlib/datatypes/set.v
> +fn (mut l Set<T>) difference(r Set<T>) Set<T> {
@spytheman it does not work with generics

2022-08-16 17:23 UTC, merged

2022-08-16 17:23 UTC, medvednikov commented
All tests pass now.

Merged, thanks!