cmd/tools/vls: add helpful message when server is not found
vlang/v pull request #15129
Opened 2022-07-19 13:33 UTC by nedpals

This PR adds helpful message when using `v ls` for the first time or when using a custom copy specified through `--path` (inspired by @Hunam6 's [comment](https://github.com/vlang/v/pull/15009#issuecomment-1181624855)):

```
v ls error: Language server is not installed nor found. (101)

- If you are using this for the first time, please run
  `v ls --install` first to download and install VLS.
- If you are using a custom version of VLS, check if
  the specified path exists and is a valid executable.
- If you have an existing installation of VLS, be sure
  to remove "vls.config.json" and "bin" located inside
  "$HOME_DIR/.vls" and re-install.

If none of the options listed have solved your issue,
please report it at https://github.com/vlang/v/issues
```

2022-07-19 13:53 UTC, spytheman requested changes

2022-07-19 13:53 UTC, spytheman commented on cmd/tools/vls.v
> +			eprintln('\n' +
Just use a multiline string.

2022-07-19 13:53 UTC, spytheman commented on cmd/tools/vls.v
> +			eprintln('\n' +
`$HOME_DIR` is not valid on either Windows, or Unix systems.

If the advice needs to be that detailed, showing `$HOME` on non windows,
and `%USERPROFILE%` on windows will be more helpful.

2022-07-19 14:10 UTC, medvednikov commented on cmd/tools/vls.v
> +			eprintln('\n' +
`os.home_dir()`

2022-07-20 01:19 UTC, nedpals commented on cmd/tools/vls.v
> +			eprintln('\n' +
fixed :+1:

2022-07-20 11:26 UTC, merged