vweb.csrf: adding README.md, corrected comments
vlang/v pull request #15697
Opened 2022-09-07 19:05 UTC by floscodes

I added README.md to the vweb.csrf-module. I also corrected some comments in the code due to spelling mistakes.

2022-09-07 19:44 UTC, enghitalo requested changes

2022-09-07 19:44 UTC, enghitalo commented on vlib/vweb/csrf/README.md
> +```
```v ignore

2022-09-07 19:44 UTC, enghitalo commented on vlib/vweb/csrf/README.md
> +```
```v ignore

2022-09-07 19:44 UTC, enghitalo commented on vlib/vweb/csrf/README.md
> +```
```v ignore

2022-09-07 19:44 UTC, enghitalo commented on vlib/vweb/csrf/README.md
> +```
```v ignore

2022-09-07 19:53 UTC, enghitalo commented on vlib/vweb/csrf/README.md
> +```
v ignore

2022-09-07 19:53 UTC, enghitalo commented on vlib/vweb/csrf/README.md
> +```
v ignore

2022-09-08 00:22 UTC, enghitalo commented
@floscodes you can see and accept
https://github.com/floscodes/v/pull/1

2022-09-08 05:09 UTC, floscodes commented
Ok, so is it more recommended to solve this by using "v ignore"? Now I solved it by making some new lines in the md-File and it worked... shall I change it an merge your version, @enghitalo ?

2022-09-08 05:58 UTC, enghitalo commented
> Ok, so is it more recommended to solve this by using "v ignore"? Now I solved it by making some new lines in the md-File and it worked... shall I change it an merge your version, @enghitalo ?
> 
The v ignore is used to set the v highlights in the github markdown files

2022-09-08 06:00 UTC, floscodes commented
Ok I see! Thanks!

2022-09-08 06:17 UTC, spytheman commented on vlib/vweb/csrf/README.md
> +If no argument is passed the value will be setted to true by default.
```suggestion
If no argument is passed the value will be set to true by default.
```

2022-09-08 10:20 UTC, merged