datatypes: Rewritten Ringbuffer - Implementing head and tail pointers, as well as fixed sized array
vlang/v pull request #15818
Opened 2022-09-19 10:56 UTC by floscodes

**Rewritten ringbuffer-feature moved to vlib/datatypes. Implementing head and tail pointers, as well as fixed sized array**

Example:

```
module main

import datatypes

fn main() {

    // create a new ringbuffer with size 4
    // the generic argument sets the type
    mut r := datatypes.new_ringbuffer<int>(4)

    // push elements
    r.push(3)
    r.push(4)

    // get the oldest element. It will be removed from the buffer when calling `pop()`
    oldest_value := r.pop()

    println(oldest_value) // Output: 3

    }

```

2022-09-19 11:56 UTC, spytheman commented on vlib/datatypes/ringbuffer.v
> +		rb.reader = rb.reader + 1
`rb.reader++`

2022-09-19 12:00 UTC, spytheman commented on vlib/datatypes/ringbuffer.v
> +		content: []T{len: rb.content.len, cap: rb.content.cap}
why not just `rb.reader, rb.writer = 0, 0`?

2022-09-19 13:53 UTC, floscodes commented
Done.

2022-09-19 16:37 UTC, Delta456 commented on vlib/datatypes/ringbuffer.v
> +		eprintln('Buffer overflow')
I think optional can be used here instead too.

2022-09-19 16:47 UTC, Delta456 commented on vlib/datatypes/ringbuffer.v
> +	}
This can be just `return rb.reader == rb.writer`.

2022-09-19 16:56 UTC, Delta456 commented on vlib/datatypes/ringbuffer.v
> +		writer: 0
Don't think this is needed because default value is `0`.

2022-09-19 17:25 UTC, floscodes commented on vlib/datatypes/ringbuffer.v
> +		eprintln('Buffer overflow')
Or should `push()` and `pop()` both return a custom Error? Something like `BufferError`?

2022-09-19 21:42 UTC, StunxFS requested changes

2022-09-19 21:42 UTC, StunxFS commented on vlib/datatypes/ringbuffer.v
> +		none
```suggestion
		return none
```

2022-09-20 08:24 UTC, floscodes commented on vlib/datatypes/ringbuffer.v
> +		content: []T{len: rb.content.len, cap: rb.content.cap}
I did it first, but then I switched to `rb = RingBuffer<T>{content: []T{len: rb.content.len, cap: rb.content.cap}}`again, because this will reset the whole buffer, including all elements that have ever been pushed.

2022-09-20 08:39 UTC, floscodes commented
I added errors now and implemented the suggested changes.

2022-09-20 09:35 UTC, shove70 commented
Thank you. I just need ringbuffer.

Can you provide a method to push more elements at a time? ```push(elements []T)```
This is very useful for reading and writing socket buffers. Reading and writing one by one a byte cumbersome and slow

2022-09-20 09:50 UTC, Delta456 commented
> Thank you. I just need ringbuffer.
> 
> Can you provide a method to push more elements at a time? ```push(elements []T)```
> This is very useful for reading and writing socket buffers. Reading and writing one by one a byte cumbersome and slow

Won't `push_many(elements []T)` method be better?

2022-09-20 10:07 UTC, floscodes commented
Good idea, will work on it.

2022-09-20 13:34 UTC, shove70 commented
> It may be even better to simply implement `push(elements ...T)`. Then you can supply 1 or more elements. If you want to only push 1, it would be `push(one)`. To push 2, `push(one, two)`. If you want to push an array, it would be `push(...arr)`.
> 
> You can even go crazy with something like `push(one, two, ...arr, three, four)`.

Strongly agree

2022-09-20 14:50 UTC, floscodes commented
> It may be even better to simply implement `push(elements ...T)`. Then you can supply 1 or more elements. If you want to only push 1, it would be `push(one)`. To push 2, `push(one, two)`. If you want to push an array, it would be `push(...arr)`.
> 
> You can even go crazy with something like `push(one, two, ...arr, three, four)`.

I also agree. Have to change it now, first I did `push_many`. Will change it.

2022-09-20 14:54 UTC, JalonSolov commented
I see you also have `pop` and `pop_many`.  Maybe just `pop` that always returns an array?  Not sure about that one.  Less convenient if you only want to pop one thing, but consistent...

2022-09-20 14:58 UTC, floscodes commented
> I see you also have `pop` and `pop_many`. Maybe just `pop` that always returns an array? Not sure about that one. Less convenient if you only want to pop one thing, but consistent...

Yes, I have also been thinking about it. I could do `pop(n ...u64)` allowing only one n element in the array to be given. If `n.len` equals 0 or 1, it would return a single element, otherwise it would return an array... What do you think?

2022-09-20 15:12 UTC, floscodes commented
I tried to do it like `push(elemts ...T)`, but I get a builder error when trying it out... I don't know why. See below... But for now I think I will leave it like this for now with `push(element T)` and `push_many(elements []T)`. This solution works.

```
/tmp/v_501/ring.15083904507890574193.tmp.c:12164:131: error: initializing 'int' with an expression of incompatible type 'Array_int' (aka 'struct array')
        _option_void _t1 = ringbuffer__RingBuffer_T_int_push_T_int(&ring, new_array_from_c_array_noscan(1, 1, sizeof(int), _MOV((int[1]){_v_array})));
                                                                                                                                         ^~~~~~~~
1 warning and 1 error generated.
...
==================
(Use `v -cg` to print the entire error message)

builder error: 
==================
C error. This should never happen.
```

2022-09-20 15:14 UTC, floscodes commented
**For now I will leave it like this with two separate methods`push(element T)` and `push_many(elements []T)`. This solution works.**

2022-09-20 15:46 UTC, JalonSolov commented
> I tried to do it like `push(elements ...T)`, but I get a builder error when trying it out... I don't know why. See below...

When you receive it, it will look like an array.  You have to do the `for e in elements` that you have in `push_many`.

2022-09-20 15:49 UTC, floscodes commented
> > I tried to do it like `push(elements ...T)`, but I get a builder error when trying it out... I don't know why. See below...
> 
> 
> 
> When you receive it, it will look like an array.  You have to do the `for e in elements` that you have in `push_many`.

Yes, this is what I did.

2022-09-20 16:38 UTC, Larpon commented
Good work @floscodes

2022-09-20 16:39 UTC, Larpon approved these changes

2022-09-20 17:24 UTC, floscodes commented
> Good work @floscodes

Thank you 🙏

2022-09-21 06:44 UTC, Larpon commented
The failing macos-cross job is because of network errors.
I'll try and re-run it

2022-09-21 08:35 UTC, floscodes commented
> The failing macos-cross job is because of network errors.
> 
> I'll try and re-run it
> 
> **edit**
> 
> Looks like we're all green :)

.... oh that's why 😅 thank you!

2022-09-21 16:42 UTC, spytheman approved these changes
Good work.

2022-09-21 16:42 UTC, merged

2022-09-21 16:44 UTC, floscodes commented
> Good work.

Thank you 🙏

2024-08-27 17:11 UTC, AKonia commented
@floscodes I have a question - why pushing to `full` `RingBuffer` leads to error ? Why ? As I know overwriting of oldest elements is one of the key features and more common strategy for RingBuffer, but in case of current implementation it's more like some kind of queue based on fixed buffer. Maybe I am missing something and there is a `push_*` function that pushes elements with overwriting oldest elements without error that dictates cumbersome `check[+pop]+push` sequence ? For example in `boost`(c++ lib) this detail(strategies for `push` in case of full buffer) has been discussed and was explicitly mentioned in the [boost docs](https://www.boost.org/doc/libs/1_39_0/libs/circular_buffer/doc/circular_buffer.html#fullbuffer), has there been a similar discussion here ?