all: fix struct field optional default/init/assign and disallow stroing result (fix #16339 #16211)
vlang/v pull request #16392
Opened 2022-11-11 09:46 UTC by shove70

1. Disallow stroing result in struct fields.
2. Fix #16339
3. Fix #16211
4. Fix https://github.com/vlang/v/issues/16099#issuecomment-1283821705

```v
struct Foo {
	bar !int
}
```
output:
```
vlib/v/parser/tests/struct_field_has_result_err.vv:2:7: error: struct field does not support storing result
    1 | struct Foo {
    2 |     bar !int
      |          ~~~
    3 | }
```

-------

```v
struct Foo {
mut:
	bar ?int = 1
}

fn main() {
	// default value test
	mut f := Foo{}
	println(f.bar)
	dump(f.bar)

	// init test
	f = Foo{
		bar: 2
	}
	println(f.bar)
	dump(f.bar)

	// assign test
	f.bar = 3
	println(f.bar)
	dump(f.bar)
}
```

output:

```
Option(1)
[vlib/v/tests/inout/struct_field_optional.vv:10] f.bar: 1
Option(2)
[vlib/v/tests/inout/struct_field_optional.vv:16] f.bar: 2
Option(3)
[vlib/v/tests/inout/struct_field_optional.vv:20] f.bar: 3
```

2022-11-11 09:50 UTC, medvednikov commented
Wow, optional struct fields! Great job!

2022-11-11 10:10 UTC, spytheman commented
What would be the type of `a` in `a := f.bar` ?

2022-11-11 10:15 UTC, spytheman commented
also how can I store `none` in f.bar ?

2022-11-11 10:15 UTC, shove70 commented
> 

it's ```?int```, But there are some small problems. I'll fix them right away.

```c
VV_LOCAL_SYMBOL void main__main(void) {
	_option_int _t1;
	_option_ok(&(int[]) { 1 }, (_option*)(&_t1), sizeof(int));
	main__Foo f = ((main__Foo){.bar =_t1,});
	println(_option_int_str(f.bar));
	 _v_dump_expr_int(_SLIT("a.v"), 10, _SLIT("f.bar"), (int)*(f.bar.data));
	_option_int _t2;
	_option_ok(&(int[]) { 2 }, (_option*)(&_t2), sizeof(int));
	f = ((main__Foo){.bar =_t2,});
	println(_option_int_str(f.bar));
	 _v_dump_expr_int(_SLIT("a.v"), 16, _SLIT("f.bar"), (int)*(f.bar.data));
	_option_int _t3;
	_option_ok(&(int[]) { 3 }, (_option*)(&_t3), sizeof(int));
	f.bar =_t3;
	println(_option_int_str(f.bar));
	 _v_dump_expr_int(_SLIT("a.v"), 20, _SLIT("f.bar"), (int)*(f.bar.data));
	_option_int a = f.bar;      // ==> here
	println(_option_int_str(/*opt*/(*(int*)a.data)));
}
```

2022-11-11 10:15 UTC, spytheman commented
will `a := f.bar or { 123 }` work too?

2022-11-11 10:18 UTC, shove70 commented
Thanks, I'll handle it together  :)

2022-11-11 10:19 UTC, enghitalo commented
Maaan!! You are great!!!! Thank you for this!!!

2022-11-11 15:04 UTC, Delta456 commented
Wow, this is amazing 😍👍

2022-11-11 15:18 UTC, JalonSolov commented
Sorry... had to change `stroing` to `storing`.  :-)

2022-11-13 09:39 UTC, dumblob commented
@shove70 looks promising - could you also align the tests with the "reification and non-reification" cases outlined in https://github.com/vlang/rfcs/blob/master/error_handling.md#handling-the-results ?

Thanks!

2022-11-13 10:41 UTC, shove70 commented
> @shove70 looks promising - could you also align the tests with the "reification and non-reification" cases outlined in https://github.com/vlang/rfcs/blob/master/error_handling.md#handling-the-results ?
> 
> Thanks!



> 

Thanks, Some rules are waiting for further confirmation. Once I get the final rules, I will..   :)

2022-11-13 10:44 UTC, shove70 commented
I'm learning about your discussion

2022-11-14 14:39 UTC, medvednikov commented
This seems to be good to merge for now @shove70 ?

2022-11-14 19:32 UTC, danieldaeschle commented
```
vlib/v/parser/tests/struct_field_has_result_err.vv:2:7: error: struct field does not support storing result
    1 | struct Foo {
    2 |     bar !int
      |          ~~~
    3 | }
```

It should be 
```
vlib/v/parser/tests/struct_field_has_result_err.vv:2:7: error: struct field does not support storing result
    1 | struct Foo {
    2 |     bar !int
      |         ~~~~
    3 | }
```

2022-11-15 02:19 UTC, shove70 commented
> This seems to be good to merge for now @shove70 ?

@medvednikov, There are still some codes that haven't been pushed. I'm still optimizing and debugging.  :)

2022-11-16 05:02 UTC, Delta456 requested changes

2022-11-16 05:02 UTC, Delta456 commented on vlib/v/gen/c/struct.v
> +				// Dont use g.typ() here becuase it will register
`becuase` -> `because`

2022-11-16 05:36 UTC, shove70 commented on vlib/v/gen/c/struct.v
> +				// Dont use g.typ() here becuase it will register
> `becuase` -> `because`

Thanks, done  :)

2022-11-16 08:34 UTC, shove70 commented
done, CI fails seems unrelated.

2022-11-16 12:46 UTC, Delta456 approved these changes

2022-11-16 13:16 UTC, spytheman commented on vlib/v/tests/inout/struct_field_optional.vv
> +	println(f.bar?)
`    dump(f.baz or { 9999 })` here produces:
```
[vlib/v/tests/inout/struct_field_optional.vv:19] f.baz: 0
```

2022-11-16 13:19 UTC, spytheman commented on vlib/v/checker/checker.v
> +					c.error('unexpected `!`, the field `${node.field_name}` does neither return an optional nor a result',
```suggestion
					c.error('unexpected `!`, the field `${node.field_name}` is neither  an optional, nor a result',
```

2022-11-16 13:20 UTC, spytheman commented on vlib/v/checker/checker.v
> +					c.error('unexpected `?`, the field `${node.field_name}` does neither return an optional nor a result',
```suggestion
					c.error('unexpected `?`, the field `${node.field_name}` is neither an optional, nor a result',
```

2022-11-16 13:20 UTC, shove70 commented on vlib/v/tests/inout/struct_field_optional.vv
> +	println(f.bar?)
Oh, oh, okay,  Thanks!

2022-11-16 13:20 UTC, spytheman commented on vlib/v/checker/checker.v
> +					c.error('unexpected `or` block, the field `${node.field_name}` does neither return an optional nor a result',
```suggestion
					c.error('unexpected `or` block, the field `${node.field_name}` is neither an optional, nor a result',
```

2022-11-16 13:22 UTC, spytheman commented on vlib/v/checker/checker.v
> +			c.error('unexpected `!`, the field `${expr.field_name}` does not have a result',
```suggestion
			c.error('unexpected `!`, result fields are not supported',
```

2022-11-16 13:24 UTC, spytheman commented on vlib/v/checker/checker.v
> +					c.error('field `${expr.field_name}` withs ${with_modifier_kind}, so it should have an `or {}` block at the end',
```suggestion
					c.error('field `${expr.field_name}` is ${with_modifier_kind}, so it should have an `or {}` block at the end',
```

2022-11-16 13:24 UTC, spytheman commented on vlib/v/checker/checker.v
> +					c.error('field `${expr.field_name}` withs ${with_modifier_kind}, so it should have either an `or {}` block, or `${with_modifier}` at the end',
```suggestion
					c.error('field `${expr.field_name}` is ${with_modifier_kind}, so it should have either an `or {}` block, or `${with_modifier}` at the end',
```

2022-11-16 14:19 UTC, shove70 commented on vlib/v/checker/checker.v
> +					c.error('field `${expr.field_name}` withs ${with_modifier_kind}, so it should have either an `or {}` block, or `${with_modifier}` at the end',
❤️❤️❤️ Thanks very much!

2022-11-16 15:29 UTC, danieldaeschle commented on vlib/v/checker/checker.v
> +					c.error('unexpected `!`, the field `${node.field_name}` does neither return an optional nor a result',
@spytheman there are two spaces after "neither"

2022-11-16 16:44 UTC, shove70 commented on vlib/v/checker/checker.v
> +					c.error('unexpected `!`, the field `${node.field_name}` does neither return an optional nor a result',
Mm-hmm. I also noticed. thank you!  @danieldaeschle

2022-11-17 05:47 UTC, spytheman commented on vlib/v/checker/checker.v
> +					c.error('unexpected `!`, the field `${node.field_name}` does neither return an optional nor a result',
My mistake. Thanks for the correction.

2022-11-17 05:48 UTC, spytheman commented on vlib/v/checker/checker.v
> +					c.error('field `${expr.field_name}` withs ${with_modifier_kind}, so it should have either an `or {}` block, or `${with_modifier}` at the end',
happy to help

2022-11-17 05:51 UTC, spytheman approved these changes
Excellent work, and a very welcome fix!

2022-11-17 05:51 UTC, merged