fix comptime value recognize on generic argument
vlang/v pull request #16768
Opened 2022-12-25 13:10 UTC by felipensp

Fix #16759

2022-12-25 16:06 UTC, spytheman commented on vlib/v/checker/comptime.v
> +				c.comptime_for_field_var = node.val_var
it should be reset after the loop

2022-12-25 16:13 UTC, spytheman requested changes
Good work. It just needs the example in the issue to become a test in `vlib/v/tests/` to prevent future regressions, and it will be ready to merge.

2022-12-26 16:43 UTC, spytheman approved these changes

2022-12-26 16:44 UTC, merged

2022-12-26 17:43 UTC, JalonSolov commented
Hmm... format problems on those last 2 test files - no trailing EOL.