Fix allow iterater over optional
vlang/v pull request #16858
Opened 2023-01-03 17:12 UTC by felipensp

Fix #16523

```V
struct Test {
	a ?[]int
	b ?[]string
	c ?[]f64
	d ?[][]string
}

fn run_loop[U](val []U) []string {
	mut out := []string{}
	for element in val {
		out << '${val}: ${element}'
	}
	return out
}

fn test_main() {
	test := Test{
		a: [1, 2, 3]
		b: ['foo', 'bar']
		c: [1.2, 2.3]
		d: [['foo'], ['bar']]
	}

	assert run_loop(test.a?).str() == "['[1, 2, 3]: 1', '[1, 2, 3]: 2', '[1, 2, 3]: 3']"
	assert run_loop(test.b?).str() == "['['foo', 'bar']: foo', '['foo', 'bar']: bar']"
	assert run_loop(test.c?).str() == "['[1.2, 2.3]: 1.2', '[1.2, 2.3]: 2.3']"
	assert run_loop(test.d?).str() == "['[['foo'], ['bar']]: ['foo']', '[['foo'], ['bar']]: ['bar']']"
}
```

2023-01-04 09:33 UTC, spytheman commented on vlib/v/tests/for_loop_with_optional_test.v
> +	assert run_loop(test.d?).str() == "['[['foo'], ['bar']]: ['foo']', '[['foo'], ['bar']]: ['bar']']"
These asserts pass on master as well.

2023-01-04 09:34 UTC, spytheman commented on vlib/v/tests/for_loop_with_optional_test.v
> +	assert run_loop(test.d?).str() == "['[['foo'], ['bar']]: ['foo']', '[['foo'], ['bar']]: ['bar']']"
did you mean `run_loop(test.a)` etc, instead?

2023-01-04 09:44 UTC, spytheman requested changes
Something like this would be a better/more focused test, and it currently does not work on master:
```v
struct Test {
	a ?[]int
	b ?[]string
	c ?[]f64
	d ?[][]string
}

fn test_for_in_optional_fields() {
	mut out := []string{}
	test := Test{
		a: [1, 2, 3]
		b: ['foo', 'bar']
		c: [1.2, 2.3]
		d: [['foo'], ['bar']]
	}
	//
	for element in test.a {
		out << '${element}'
	}
	dump(out)
	assert out == ['1', '2', '3']
	out.clear()
	//
	for element in test.b {
		out << '${element}'
	}
	dump(out)
	assert out == ['foo', 'bar']
	out.clear()
	//
	for element in test.c {
		out << '${element}'
	}
	dump(out)
	assert out == ['1.2', '2.3']
	out.clear()
	//
	for element in test.d {
		out << '${element}'
	}
	dump(out)
	assert out == ["['foo']", "['bar']"]
	out.clear()
}
```

2023-01-04 15:49 UTC, felipensp commented
> Something like this would be a better/more focused test, and it currently does not work on master:
> 
> ```v
> struct Test {
> 	a ?[]int
> 	b ?[]string
> 	c ?[]f64
> 	d ?[][]string
> }
> 
> fn test_for_in_optional_fields() {
> 	mut out := []string{}
> 	test := Test{
> 		a: [1, 2, 3]
> 		b: ['foo', 'bar']
> 		c: [1.2, 2.3]
> 		d: [['foo'], ['bar']]
> 	}
> 	//
> 	for element in test.a {
> 		out << '${element}'
> 	}
> 	dump(out)
> 	assert out == ['1', '2', '3']
> 	out.clear()
> 	//
> 	for element in test.b {
> 		out << '${element}'
> 	}
> 	dump(out)
> 	assert out == ['foo', 'bar']
> 	out.clear()
> 	//
> 	for element in test.c {
> 		out << '${element}'
> 	}
> 	dump(out)
> 	assert out == ['1.2', '2.3']
> 	out.clear()
> 	//
> 	for element in test.d {
> 		out << '${element}'
> 	}
> 	dump(out)
> 	assert out == ["['foo']", "['bar']"]
> 	out.clear()
> }
> ```
> 
> On master, the above produces a checker error. On this PR, there is no checker error, as expected, but there is a cgen one instead:
> 
> ```
> #1 11:45:08 ᛋ fix_allow_iterater_over_optional /v/vclean❱./v bug_test.v 
> ==================
> /tmp/v_1000/bug_test.14231054159339106842.tmp.c:18541: error: field not found: len
> ...
> ==================
> ```

Yeah, you are right. I have updated the tests and fixed such cgen error.

2023-01-04 15:49 UTC, felipensp commented on vlib/v/tests/for_loop_with_optional_test.v
> +	assert run_loop(test.d?).str() == "['[['foo'], ['bar']]: ['foo']', '[['foo'], ['bar']]: ['bar']']"
fixed the test

2023-01-05 00:27 UTC, JalonSolov commented
Odd... all the errors appear to be with `-usecache`.

2023-01-05 01:06 UTC, felipensp commented
> Odd... all the errors appear to be with `-usecache`.

Yeah, I was trying understand the issue.

2023-01-06 06:33 UTC, merged