vlib/rand: add full precision f32 and f64 random functions; fix f32/f64 multipliers
vlang/v pull request #16875
Opened 2023-01-04 15:41 UTC by j-bm

Actually four sets of changes here:

1. fix the fp32() and fp64() functions to avoid producing 1.00000.  Adjust the multiplier used.  Add to documentation explaining how the pseudo-random number is generated.  Fixes #16707.
2. Add fp32cp() and fp64cp() functions to generate pseudo-random numbers with full-precision mantissa.  The exponents are adjusted as well such that really small numbers, e.g. less than 1.0E08 are suitably rare.
3. Add a test of fp32()/fp32cp() and fp64()/fp64cp() with known seeds and verify frequency of small numbers is always the same.
4. Update the README to clarify how to generate seeds, and explain when and why you may want to re-use the same seeds.

Example code to show why the default u32() * constant method generates imprecise mantissas for smaller values:

```
import math
import rand
for {
        y := rand.f32()
        if y < 1.0e-6 {
                println('${math.f32_bits(y):x} ${y}')
                break
        }
}
```
Run this a few times and notice the hex values always have trailing zeros.  Replace with the f32cp() and the hex values are consistently random.

2023-01-04 17:26 UTC, hungrybluedev requested changes
Define the constants in the private scope of the rand module (or somewher else in case of a better option).

I would like to see links to the reference implementations or papers so that I can verify the correctness of implementation.

Looks solid otherwise. Especially the new hist test!

2023-01-04 17:26 UTC, hungrybluedev commented on vlib/rand/rand.v
> +	float_eps := 1.19209289550781E-07
Best to describe it outside the function, as a module private constant.

2023-01-04 17:26 UTC, hungrybluedev commented on vlib/rand/rand.v
> +	bits23 := (u32(1) << 23) - 1
Same for these constants... They can be declared outside the functions.

2023-01-04 17:31 UTC, spytheman commented on vlib/rand/rand.v
> +	}
why is that in `unsafe{}` ?

2023-01-04 17:39 UTC, spytheman commented on vlib/rand/fp_test.v
> +	count = 90100100
With this count, on i3, and tcc, the test for me takes over ~40s:
```
#0 19:36:55 ᛋ const-precision /v/vnew❱VJOBS=1 ./v test vlib/rand/
---- Testing... ----------------------------------------------------------------------------------------
 OK    [ 1/13]  2742.746 ms vlib/rand/dist_test.v
 OK    [ 2/13] 42366.148 ms vlib/rand/fp_test.v
 OK    [ 3/13]   956.331 ms vlib/rand/mt19937/mt19937_test.v
 OK    [ 4/13]   860.714 ms vlib/rand/musl/musl_rng_test.v
 OK    [ 5/13]   826.717 ms vlib/rand/pcg32/pcg32_test.v
 OK    [ 6/13]   276.692 ms vlib/rand/rand_test.js.v
 OK    [ 7/13]   550.786 ms vlib/rand/random_bytes_test.v
 OK    [ 8/13]   522.016 ms vlib/rand/random_identifiers_test.v
 OK    [ 9/13]   579.500 ms vlib/rand/random_numbers_test.v
 OK    [10/13]   890.669 ms vlib/rand/splitmix64/splitmix64_test.v
 OK    [11/13]   837.053 ms vlib/rand/sys/system_rng_test.v
 OK    [12/13]   819.640 ms vlib/rand/wyrand/wyrand_test.v
 OK    [13/13]   854.196 ms vlib/rand/xoroshiro128pp/xoros128pp_test.v
----------------------------------------------------------------------------------------
Summary for all V _test.v files: 13 passed, 13 total. Runtime: 53085 ms, on 1 job.

```

Can we choose other seeds, and count, so that it takes ~4-5 seconds max?

2023-01-04 17:41 UTC, spytheman commented on vlib/rand/rand.v
> +		if x == 0 {
```suggestion
		if _unlikely_(x == 0) {
```

2023-01-04 17:45 UTC, spytheman commented on vlib/rand/rand.v
> +import math
The main `math` module is big. I will copy the 2 needed functions `math.f32_from_bits` and `math.f64_from_bits` into `math.bits` (which is more suitable place for them anyway, given the names), so that they could be used directly from there, without importing `math`.

2023-01-04 18:04 UTC, j-bm commented on vlib/rand/rand.v
> +	}
Legacy from prior versions (hadn't discovered math.f32_from_bits at that point).

2023-01-04 18:06 UTC, j-bm commented on vlib/rand/fp_test.v
> +	count = 90100100
Good point.  I was wondering what a valid time limit was.  Although at say 5s of cpu the relevant counts are 1/10 these values.  I will think about perhaps making a different histogram to make the counts a bit higher with that constraint.

2023-01-04 18:07 UTC, j-bm commented on vlib/rand/rand.v
> +		if x == 0 {
OK.

2023-01-04 18:15 UTC, j-bm commented on vlib/rand/rand.v
> +import math
Why not -skip-unused which (should) eliminate much of math?  I don't see a compile-time difference but then I don't much pay attention to that.  I have tried -skip-unused a few times and wondered why it is not default.  Not to highjack this thread. perhaps move this q&a to discourse or something.

2023-01-04 18:19 UTC, spytheman commented on vlib/rand/rand.v
> +import math
Because -skip-unused is not used by default yet, and because also `vlib/math/math.c.v` has `#flag -lm`, which -skip-unused would not eliminate.

With `import math` all `rand` using executables currently are ~200KB larger on Linux.

2023-01-04 18:53 UTC, j-bm commented on vlib/rand/rand.v
> +	float_eps := 1.19209289550781E-07
OK, I will put in a suitably named value.

2023-01-04 18:54 UTC, j-bm commented on vlib/rand/rand.v
> +	bits23 := (u32(1) << 23) - 1
I will add references.

2023-01-04 20:08 UTC, spytheman commented
@ulises-jeremias what do you think of changing `vsl/noise/perlin_test.v` (currently it is the only failing CI - https://github.com/vlang/v/actions/runs/3840516206/jobs/6539668335) so that it works with the new floating point random numbers ?

2023-01-04 21:07 UTC, ulises-jeremias commented
@spytheman sure! I'm afk right now but will try to change it asap

2023-01-04 22:35 UTC, spytheman commented
> @spytheman sure! I'm afk right now but will try to change it asap

Thank you 🙇🏻‍♂️ .

2023-01-09 21:25 UTC, j-bm commented on vlib/rand/fp_test.v
> +	count = 90100100
Same histogram and slightly different numbers.

2023-01-18 10:11 UTC, hungrybluedev approved these changes
I've read the reference (skimmed through it). Seems to be working alright. Good job!

2023-01-18 10:43 UTC, KamkoAmoh approved these changes

2023-01-19 09:34 UTC, spytheman commented
(rebased over master, and rerun the CI, to see what remains to be fixed from the CI tested projects)

2023-01-19 12:10 UTC, JalonSolov commented
Only 1 failing test, on Mac... and not much info about it:
```
 FAIL  [  19/1264]   113.732 ms vlib/builtin/js/int_test.js.v
thread_suspend failed
```

2023-01-19 12:16 UTC, spytheman commented
The macos failure is not related; I've tested manually on m1 and it passes there.

2023-01-19 12:22 UTC, spytheman commented
I would restart that job, but can not right now, since it is complected with the windows-gcc run for some reason in the github UI.

2023-01-19 13:21 UTC, merged