Feat add multi-platform portability to string `split_into_lines()`
vlang/v pull request #17078
Opened 2023-01-22 22:43 UTC by rivy

* fixes and increases cross-platform portability of `split_into_lines()`; now has MacOS (`\r`), POSIX (`\n`), and WinOS (`\r\n`) compatibility
* added/revised tests for the updated capability
* also fixes the builtin/js version and activated/corrected it's tests as well

Could you explain the *builtin/js* version? I did correct it's function and activated the respective test, but I'm not sure about the applicability.

Anyway, CI with all tests (both *builtin* and *builtin/js*)are passing.

2023-01-22 23:13 UTC, JalonSolov commented
Wow... how many years has it been since Mac used only `\r` line endings?

2023-01-22 23:19 UTC, rivy commented
> Wow... how many years has it been since Mac used only `\r` line endings?

Though older MacOS was the primary contributor, there are still, unfortunately, lots of files around with CR-only line endings.
Given there's no loss of efficiency for the added flexibility, it seems appropriate to include it.

2023-01-22 23:33 UTC, rivy commented
@spytheman , I wasn't sure of you could comment on what the *builtin/js* code was used for?

2023-01-23 00:29 UTC, JalonSolov commented
I don't disagree about handling old Mac files, it has just been years since I've seen them mentioned.  :-)

`builtin/js` is pretty much what is implied - JavaScipt equivalents to the regular builtin files.  For use by the JavaScript backend.

2023-01-23 09:28 UTC, spytheman commented
Yes, the `vlib/builtin/js` folder in `builtin` is used only by the js backend. It should be merged into `vlib/builtin` only keeping the .js.v files for the JS specific implementation, but that has not happened yet :-| .

It was made separate, to make bootstrapping the JS backend easier, but that is technical debt that has to be payed at some point, otherwise it burdens all non pure V modules due to the code duplication.

2023-01-23 09:34 UTC, spytheman commented on vlib/builtin/string.v
> +	lf := '\n'[0]
use just:
```suggestion
	cr := `\r`
	lf := `\n`
```

2023-01-23 09:36 UTC, spytheman commented on vlib/builtin/string.v
> +	lf := '\n'[0]
or:
```suggestion
	cr := 13
	lf := 10
```
(it is not like the ASCII codes are going to change soon)

2023-01-23 09:42 UTC, spytheman requested changes
Good work, just use the runes or the ASCII codes directly, instead of creating strings just to get their first character.

2023-01-24 04:41 UTC, rivy commented on vlib/builtin/string.v
> +	lf := '\n'[0]
Changed to rune version (and pushed).
Because of my limited experience with the language, I couldn't figure out how to correctly create the individual characters. 🤦🏻‍♂️
Thanks for the suggestion!

2023-01-24 04:41 UTC, rivy commented
> Good work, just use the runes or the ASCII codes directly, instead of creating strings just to get their first character.

PR updated with suggestion. Thanks!

2023-01-24 08:01 UTC, spytheman approved these changes

2023-01-24 08:02 UTC, merged