json2: strict_decode
vlang/v pull request #17927
Opened 2023-04-10 13:24 UTC by enghitalo

```v
struct StructType {
mut:
	val        string
	option_val ?string
}

fn test_superfluous() {
	json.strict_decode[StructType]('{"val": "","val2": ""}') or {
		assert err.msg() == '[x.json2] useless data detected. Try prune superfluous fields showed in err.superfluous_fields()'
		assert err.superfluous_fields() == ['val2']
		return
	}
	assert false
}
```

2023-04-14 03:47 UTC, tobealive requested changes

2023-04-14 03:47 UTC, tobealive commented on vlib/x/json2/decode_strict_struct_test.v
> +		assert err.msg() == '[x.json2] useless data detected. Try pruning superfluous fields shown in err.superfluous_fields()'
To further improve semantics and make it more concise.
```suggestion
		assert err.msg() == '[x.json2] unusable data detected. Try pruning superfluous fields in err.superfluous_fields()'
```

2023-04-14 03:47 UTC, tobealive commented on vlib/x/json2/decode_strict_struct_test.v
> +		assert err.msg() == '[x.json2] useless data detected. Try prune superfluous fields showed in err.superfluous_fields()'
Not to forget No.2
```suggestion
		assert err.msg() == '[x.json2] unusable data detected. Try pruning superfluous fields in err.superfluous_fields()'
```

2023-12-10 20:38 UTC, enghitalo commented
How can this CI fail can be related to this PR? 
![image](https://github.com/vlang/v/assets/63821277/3c11dbd6-7bdc-48d9-b69e-a04d0895614f)

2023-12-11 03:31 UTC, ttytm commented on vlib/x/json2/strict/strict.v
> +fn get_superfluous_keys[T](tokens []string, key_struct []KeyStruct) []string {
`tokens` is unused.

2023-12-11 03:31 UTC, ttytm commented on vlib/x/json2/strict/strict.v
> +fn get_duplicates_keys(tokens []string, key_struct []KeyStruct) []string {
same for `tokens` here.

2023-12-11 03:31 UTC, ttytm commented on vlib/x/json2/strict/strict.v
> +	return arrays.uniq_only_repeated(json_keys)
`it` syntax sugar might fit here.
```v
	json_keys := key_struct.map(it.key).sorted()
	return arrays.uniq_only_repeated(json_keys)
```

2023-12-11 03:31 UTC, ttytm commented on vlib/x/json2/strict/strict.v
> +		mut superfluous := get_superfluous_keys[T](tokens, key_struct)
One thing that comes to my mind would be to get the duplicates and superfluous in one loop. They are called recursively, so it could be worth a try using one instead of multiple consecutive loops. Did you try that?

2023-12-11 03:32 UTC, ttytm commented
> How can this CI fail can be related to this PR?
Likely not related :slightly_smiling_face: :+1:

2023-12-15 23:02 UTC, enghitalo commented on vlib/x/json2/strict/strict.v
> +		mut superfluous := get_superfluous_keys[T](tokens, key_struct)
I will try it in next PR. Thank you!!

2023-12-15 23:05 UTC, enghitalo commented
Thank you for review @ttytm !

2023-12-17 11:04 UTC, spytheman commented
I do not understand, what is the use case of this submodule?

2023-12-17 11:07 UTC, spytheman commented on vlib/x/json2/strict/strict.v
> +fn strict_check[T](json_data string) StructCheckResult {
```suggestion
pub fn strict_check[T](json_data string) StructCheckResult {
```

2023-12-17 11:08 UTC, spytheman commented on vlib/x/json2/strict/strict.v
> +fn get_keys_from_json(tokens []string) []KeyStruct {
```suggestion
pub fn get_keys_from_json(tokens []string) []KeyStruct {
```

2023-12-17 11:09 UTC, spytheman commented
I think we have a bug in the compiler, that allowed non public functions to be called by the test, without it being marked as an internal one.

2023-12-17 13:12 UTC, enghitalo commented
> I do not understand, what is the use case of this submodule?

Many of the companies I worked for had slowdown issues due to excessive unnecessary data sent through the back-end of web applications. Using a library like this, on the front-end, for example, helps keep the back-end code fast, efficient and with better-defined routes.

2023-12-17 13:36 UTC, spytheman commented
I still do not understand the usecase 🤔 .

Lets take for example a web app, and let it have:
a) a JS client running in a browser, 
b) a backend webserver implemented in V, connected to 
c) a DB, say MySQL.

The communication between the JS client and the backend in V, happens by sending JSON messages.

Where would such a module be used?
aa) when the V webserver sends JSON to the JS client?
bb) when the V webserver receives JSON from the JS client?

If aa) is the case, could not the webserver just *not generate* the additional keys, in the first place, and that would have been caught in code review?

If bb) is the case, what would the webserver do, when it detects it? Log that it found duplicated keys? Who will read those logs? Or will it stop processing, until the JS client is fixed?

2023-12-17 13:38 UTC, spytheman commented
I also could not understand how is that related to routing at all 🤔 .

2023-12-21 02:48 UTC, enghitalo commented
Hi. Sorry the delay. I will answer everything As Soon As Possible

2023-12-29 13:33 UTC, enghitalo commented
> I also could not understand how is that related to routing at all 🤔 .

It is very common for some developers to use a single route for multiple purposes, what is no good. For example, a route that returns all the products in the database, sometimes even with relationships, when, in many cases, they do not need all this information. Use the strict library to check that there is no unnecessary data, to perform end-to-end tests, send a log, or even return an error. It would help to create and maintain a final product with greater quality and performance, create a quality metric for the development team, facilitate code review...

2023-12-29 13:52 UTC, enghitalo commented
> I still do not understand the usecase 🤔 ....

More the bb) case. 

It will depend on how rigid the team is. Personally, I would use Log Management or apply it to tests. Since, for me, it wouldn't be very interesting to break the application with errors that could be random (But it also depends on how these errors will be handled)

2024-01-01 11:55 UTC, spytheman approved these changes

2024-01-01 11:56 UTC, merged