complex and gamma: Added missing docstrings fir log_gamma_sign and complex fn
vlang/v pull request #19523
Opened 2023-10-06 22:30 UTC by sudoerp

2023-10-07 00:14 UTC, ttytm requested changes

2023-10-07 00:14 UTC, ttytm commented on vlib/math/complex/complex.v
> +// Return a Complex Struct with re and im
```suggestion
// complex returns a Complex struct with the given `re` and `im`.
```

The convention for function documentation includes the function name.
It's not always followed atm, but I think it's good if new changes that are made follow it.

E.g. running the below in your v root will show a lot of warnings regarding this:
```
v vet vlib/math/complex
```
```
vlib/math/complex/complex.v:16: warning: A function name is missing from the documentation of "pub fn complex(re f64, im f64) Complex".
...
```

2023-10-07 00:14 UTC, ttytm commented on vlib/math/complex/complex.v
> +// mod(x + iy) = √( x^2 + y^2 )
```suggestion
// mod returns the modulus value of `c`
```
```
// mod(x + iy) = √( x^2 + y^2 )
```
The illustration might be a bit irritating as the function usage would be `c.mod()`

2023-10-07 07:16 UTC, spytheman commented on vlib/math/gamma.v
> +// uses log_gamma_sign internally
that is not relevant imho

2023-10-07 07:17 UTC, spytheman commented on vlib/math/complex/complex.v
> +// Return a Complex Struct with re and im
Yes, function comments has to start with the function name, to be picked up by `v doc` .

2023-10-07 10:44 UTC, ttytm commented on vlib/math/complex/complex.v
> +// complex returns a Complex Struct with the given `re` and `im`
// complex returns a Complex data structure with the given `re` and `im`.

small caps `struct` or `data structure` is the common choice.
I'd vote for ending with a peroid, it's also used more often in current doc and the standard in e.g. go doc comments.

2023-10-08 08:38 UTC, Larpon approved these changes

2023-10-08 09:20 UTC, merged