builtin: Add `is_hex()`, `is_int()`, `is_bin()`, and `is_oct()` by strings - Feature
vlang/v pull request #20540
Opened 2024-01-15 02:05 UTC by viniciusfdasilva

### Code

```v
// Check if a string is an hexadecimal value. Returns 'true' if it is, or 'false' if it is not
pub fn (str string) is_hex() bool {

	mut tmp_string := str

	if tmp_string.starts_with('0x') {
		tmp_string = tmp_string[2..tmp_string.len]
	}else if tmp_string.starts_with('-0x') {
		tmp_string = tmp_string[3..tmp_string.len]
	}else{
		return false
	}

	if tmp_string.len >= 1 {
		
		for s in tmp_string {
			if (u8(s) >= `0` && u8(s) <= `9`) || ((u8(s) >= `a` && u8(s) <= `f`) || (u8(s) >= `A` && u8(s) <= `F`))  {
				continue
			}else{
				return false
			}
		}

		return true
	}else{
		return false
	}
}

// Check if a string is an integer value. Returns 'true' if it is, or 'false' if it is not
pub fn (str string) is_int() bool {

	mut tmp_string := str

	if tmp_string.starts_with('-') {
		tmp_string = tmp_string[1..tmp_string.len]
	}

	if tmp_string.len >= 1 {
		for s in tmp_string {
			if u8(s) >= `0` && u8(s) <= `9` {
				continue
			}else{
				return false
			}
		}
		return true
	}else{
		return false
	}
}
```

### Test code

```v
// vlib/builtin/string_test.v file
fn test_is_bin(){

	assert '0b1'.is_bin()       == true
	assert '0b0'.is_bin()       == true
	assert '0b'.is_bin()        == false
	assert '-0b'.is_bin()       == false
	assert '-0b1'.is_bin()      == true
	assert '-0b0'.is_bin()      == true
	assert '-0b1101'.is_bin()   == true
	assert '-0b0101'.is_bin()   == true
	assert '-324'.is_bin()      == false
	assert '-0'.is_bin()        == false
	assert '0x1'.is_bin()       == false
	assert '0x1A'.is_bin()      == false
	assert '-0x1'.is_bin()      == false
	assert '-0x1A'.is_bin()     == false
	assert '0x'.is_bin()        == false
	assert '0'.is_bin()         == false
	assert '0xFF'.is_bin()      == false
	assert '0xG'.is_bin()       == false
	assert '-0xFF'.is_bin()     == false
	assert '0.34'.is_bin()      == false
	assert '0o23'.is_bin()      == false
	assert 'vlang'.is_bin()     == false
}

fn test_is_oct(){

	assert '0o0'.is_oct()       == true
	assert '0o1'.is_oct()       == true
	assert '0o2'.is_oct()       == true
	assert '-0o0'.is_oct()      == true
	assert '-0o1'.is_oct()      == true
	assert '-0o2'.is_oct()      == true

	assert '0o04'.is_oct()      == true
	assert '0o16'.is_oct()      == true
	assert '0o23'.is_oct()      == true
	assert '-0o05'.is_oct()     == true
	assert '-0o13'.is_oct()     == true
	assert '-0o22'.is_oct()     == true

	assert '0o8'.is_oct()       == false
	assert '0o9'.is_oct()       == false
	assert '-0o8'.is_oct()      == false
	assert '-0o9'.is_oct()      == false
	assert '0o84'.is_oct()      == false
	assert '0o96'.is_oct()      == false
	assert '-0o83'.is_oct()     == false
	assert '-0o2923'.is_oct()   == false
	assert '0b1'.is_oct()       == false
	assert '0b0'.is_oct()       == false
	assert '0b'.is_oct()        == false
	assert '-0b'.is_oct()       == false
	assert '-0b1'.is_oct()      == false
	assert '-0b0'.is_oct()      == false
	assert '-0b1101'.is_oct()   == false
	assert '-0b0101'.is_oct()   == false
	assert '-324'.is_oct()      == false
	assert '-0'.is_oct()        == false
	assert '0x1'.is_oct()       == false
	assert '0x1A'.is_oct()      == false
	assert '-0x1'.is_oct()      == false
	assert '-0x1A'.is_oct()     == false
	assert '0x'.is_oct()        == false
	assert '0'.is_oct()         == false
	assert '0xFF'.is_oct()      == false
	assert '0xG'.is_oct()       == false
	assert '-0xFF'.is_oct()     == false
	assert '0.34'.is_oct()      == false
	assert 'vlang'.is_oct()     == false
}

fn test_is_hex(){

	assert '-324'.is_hex()       == false
	assert '-0'.is_hex()         == false
	assert '0x1'.is_hex()        == true
	assert '0x1A'.is_hex()       == true
	assert '-0x1'.is_hex()       == true
	assert '-0x1A'.is_hex()      == true
	assert '0x'.is_hex()         == false
	assert '0'.is_hex()          == false
	assert '0xFF'.is_hex()       == true
	assert '0xG'.is_hex()        == false
	assert '-0xFF'.is_hex()      == true
	assert '0b1101'.is_hex()     == false
	assert '0.34'.is_hex()       == false
	assert '0o23'.is_hex()       == false
	assert 'vlang'.is_hex()      == false
}

fn test_is_int(){

	assert '-324'.is_int()       == true
	assert '234'.is_int()        == true
	assert '-0'.is_int()         == true
	assert '-b'.is_int()         == false
	assert '-123456789'.is_int() == true
	assert '123456789'.is_int()  == true
	assert '0x1'.is_int()        == false
	assert '0b1101'.is_int()     == false
	assert '0.34'.is_int()       == false
	assert '0o23'.is_int()       == false
	assert 'vlang'.is_int()      == false
}
```

### Test output 

![test](https://github.com/vlang/v/assets/32939036/fad19c62-8ee4-452a-bb02-c14cadc4b11a)

2024-01-15 02:10 UTC, JalonSolov commented
You'll need to format your changes.

2024-01-15 02:20 UTC, viniciusfdasilva commented
@JalonSolov Any suggestions on what I should do?

2024-01-15 02:28 UTC, JalonSolov commented
Just run `v fmt -w .` in your playpen, and commit the reformatted files.

2024-01-15 02:32 UTC, JalonSolov commented
Note that you can install a git hook to check the files when you try to commit them by running `cp <v install dir>/cmd/tools/git_pre_commit_hook.vsh <your clone>/.git/hooks/pre-commit`

2024-01-15 02:38 UTC, viniciusfdasilva commented
@JalonSolov `v fmt -w .` executed!

2024-01-15 04:09 UTC, JalonSolov commented
Still says `string_test.v` is not formatted.

2024-01-15 10:09 UTC, viniciusfdasilva commented
@JalonSolov Sorry! I had forgotten!

2024-01-15 12:30 UTC, penguindark commented
my only concern as always is performance,
anyway good job. 👍

2024-01-15 12:47 UTC, viniciusfdasilva commented
@penguindark

"I do too! In this case, the implementation meets this requirement, in my view, by eliminating any other invalid formats in the checks before the `for` loop! =)

2024-01-15 18:39 UTC, penguindark requested changes
After a quick check on the code I'm suggesting to rewrite the functions in a mor efficent way.
At my first sight I missed the string allocation in the function.
Allocate in the Heap for a check on a string it is truly not recommended IMHO.
Anyway I appreciate a lot the effort the @viniciusfdasilva put in this code 👍 
Thanks a lot for your ffort to contribute to V.

2024-01-15 18:39 UTC, penguindark commented on vlib/builtin/string.v
> +		tmp_string = tmp_string[2..tmp_string.len]
here you can use simply: `tmp_string = tmp_string[2..]`

2024-01-15 18:39 UTC, penguindark commented on vlib/builtin/string.v
> +		tmp_string = tmp_string[3..tmp_string.len]
here you can use simply: `tmp_string = tmp_string[3..]`

2024-01-15 18:39 UTC, penguindark commented on vlib/builtin/string.v
> +	if tmp_string.starts_with('0o') {
the case "+0o" is not managed, is it right?
Same for the ogher bin and hex functions.

2024-01-15 18:39 UTC, penguindark commented on vlib/builtin/string.v
> +		tmp_string = tmp_string[2..tmp_string.len]
here you can use simply: `tmp_string = tmp_string[2..]`

2024-01-15 18:39 UTC, penguindark commented on vlib/builtin/string.v
> +		tmp_string = tmp_string[3..tmp_string.len]
here you can use simply: `tmp_string = tmp_string[3..]`

2024-01-15 18:39 UTC, penguindark commented on vlib/builtin/string.v
> +		tmp_string = tmp_string[2..tmp_string.len]
here you can use simply: `tmp_string = tmp_string[2..]`

2024-01-15 18:39 UTC, penguindark commented on vlib/builtin/string.v
> +		tmp_string = tmp_string[3..tmp_string.len]
here you can use simply: `tmp_string = tmp_string[3..]`

2024-01-15 18:39 UTC, penguindark commented on vlib/builtin/string.v
> +	mut tmp_string := str
Use of this temporary string if you don't need to change the content is very inefficient. 
You can scan the string like in this example without allocate further memory:
```v
pub fn is_oct(s string) bool {
	mut i := 0
	// manage the sign
	if s[i] == `+` || s[i] == `-` {
		i++
	}
	// octal header
	if s[i] != `0` {
		return false
	}
	i++
	if s[i] != `o` {
		return false
	}
	i++
	// check the main body of the number
	for i < s.len {
		if s[i] < `0` || s[i] > `7` {
			return false
		}
		i++
	}
	return true
}
```

2024-01-15 18:39 UTC, penguindark commented on vlib/builtin/string_test.v
> +fn test_is_bin() {
Think if the cases like `+0b1001` or `+0xFA3` must be managed

2024-01-15 19:11 UTC, viniciusfdasilva commented on vlib/builtin/string.v
> +	if tmp_string.starts_with('0o') {
Perfect! Is a invalid format!

2024-01-15 19:14 UTC, viniciusfdasilva commented
@penguindark

I appreciate the recognition for the effort in my collaboration! I'm just starting with the language! I've only had 1 month of exposure to it, and I'm happy to contribute to the language's development!  :)

2024-01-15 19:15 UTC, viniciusfdasilva commented on vlib/builtin/string.v
> +	mut tmp_string := str
Perfect! I'll make the modifications. 👍

2024-01-15 19:24 UTC, viniciusfdasilva commented on vlib/builtin/string_test.v
> +fn test_is_bin() {
Yes! I find the problem! kkkkk

2024-01-16 04:01 UTC, penguindark approved these changes
For me it is ok!
Tnx for your work :)

2024-01-16 04:29 UTC, JalonSolov commented on vlib/builtin/string.v
> +	}
More idiomatic (and slightly shorter) V would be
```suggestion
	for c in str[i..] {
		if c < `0` || c > `7` {
			return false
		}
	}
```

2024-01-16 05:23 UTC, penguindark commented on vlib/builtin/string.v
> +	}
less performant I suppose due  the `str[i..]` -_-

2024-01-16 12:49 UTC, viniciusfdasilva commented on vlib/builtin/string.v
> +	}
@JalonSolov
```v
for c in str[i..]
```
I agree with @penguindark. I think direct index access might be more performant by avoiding the cost of generating the slice in my opinion! I suggest sticking to the original implementation.

2024-01-16 14:22 UTC, JalonSolov commented on vlib/builtin/string.v
> +	}
If this were the only change, true.  However, you could move the entire function inside `for c in str` and avoid using the index at all.

However, that can be done later.

2024-01-16 14:46 UTC, viniciusfdasilva commented on vlib/builtin/string.v
> +	}
@JalonSolov  and @penguindark 

Of course! Thank you for the suggestion! I request approval for this pull request! I plan to work on some other similar functions as well!

Let's analyze later which aspects can lead one approach to be better than another! :)

2024-01-16 21:46 UTC, spytheman commented on vlib/builtin/string.v
> +	mut i := 0
```suggestion
	if str.len == 0 {
		return false
	}
	mut i := 0
```

2024-01-16 21:48 UTC, spytheman commented on vlib/builtin/string.v
> +	mut i := 0
Otherwise `str[i]` on the next line will read the 0th byte that V requires for all V strings, for compatibility with C, which is ok, but not ideal.

2024-01-16 21:53 UTC, spytheman commented on vlib/builtin/string.v
> +	mut i := 0
Same, `if str.len == 0 { return false }` should be here as well.

2024-01-16 21:54 UTC, spytheman commented on vlib/builtin/string.v
> +	mut i := 0
Add `if str.len == 0 { return false }` at the start.

2024-01-16 21:54 UTC, spytheman commented on vlib/builtin/string.v
> +	mut i := 0
Add `if str.len == 0 { return false }` at the start.

2024-01-16 21:55 UTC, spytheman commented on vlib/builtin/string_test.v
> +	assert '0b1'.is_bin() == true
Please also assert on the `''.is_bin()` etc cases too.

2024-01-16 21:57 UTC, spytheman approved these changes
Good work.

2024-01-16 21:58 UTC, merged