Json2 (count): pre define buffer capacity to avoid memory copy and allocation
vlang/v pull request #20920
Opened 2024-02-28 20:31 UTC by enghitalo

gains around 20% for now in `vlib/v/tests/bench/bench_json_vs_json2.v`

2024-03-11 16:26 UTC, spytheman requested changes
The new `Count` struct and its related API, does not need to be public. 

The tests for it are very repetitive. The test file can also be an internal one (starting with `module json2`), thus avoiding exposing the helper Count struct.

2024-03-11 16:55 UTC, enghitalo commented
> The new `Count` struct and its related API, does not need to be public.
> 
> The tests for it are very repetitive. The test file can also be an internal one (starting with `module json2`), thus avoiding exposing the helper Count struct.

I thought this might be useful in cases like
```v
mut count := json.Count{0}

count.count_chars(StructType[string]{})

mut request := 'GET / HTTP/1.1\r\nContent-Length: ${count.get_total()}\r\n\r\n'.bytes()

request.ensure_cap( request.len + count.get_total())

encoder.encode_value(val, mut request)!
```

2024-03-12 06:20 UTC, spytheman commented
I think, that we already have io reader/writer interfaces.

I also think that making something public, *if* there is a need for it in the future, justified by actual code and actual measurements in concrete situations, is easy.

In contrast, turning a public API to a private one, is much harder, costing time for deprecation, to minimize the breaking change. I also think, that the cost for both maintainers and users, of a non essential, inconvenient API is high.

2024-03-12 15:17 UTC, enghitalo commented
You rock! Thanks for the review.

2024-03-14 19:21 UTC, spytheman approved these changes

2024-03-14 19:23 UTC, merged