array: common methods - min, max, argmin, argmax
vlang/v pull request #6177
Opened 2020-08-19 20:54 UTC by mobarski

I'm trying to add some common array methods that should work on all numerical types.
In this draft PR I include 2 solutions - one based on generics, other on type promotion.

I would like to know what do you think about both.

Usage:
```v
[i16(5),3,1,2,4].min() // generics based
[i16(5),3,1,2,4].min2() // type promotion based
```

Type promotion solution only has min2 implemented.
Generics based: min,max,argmin,argmax.

Both solutions are in separate files: 'array_generics.v' and 'array_promotion.v'
Both solutions have unittests.

With both solutions I've encountered a problem with returning an option (for empty array) so currently it just panics.

2020-08-20 08:16 UTC, ntrel commented
A true generic implementation of min should not be unsafe. Unfortunately V arrays are not generic, and Alex has said he doesn't want them to be. This means generic programming in V is crippled.

2020-08-20 09:05 UTC, mobarski commented
> A true generic implementation of min should not be unsafe.
Sorry for that. That's just my fault - premature optimization.
Safe version works fine:
```v
fn arr_min<T>(a []T) T {
	if a.len==0 { panic('.min called on an empty array') } // TODO
	mut val := a[0]
	for i in 0..a.len {
		if a[i] < val {
			val = a[i]
		}
	}
	return val
}
```
I'll change the code.

2020-08-20 09:09 UTC, mobarski commented
Code changed. Generics are not unsafe now.

2020-08-20 09:44 UTC, ntrel commented on vlib/builtin/array_generics.v
> -		data := &T(a.data)
Using `a.data` is fine to avoid bounds checks, you can keep that code. Now that the function takes `[]T` there's no need for the `[unsafe]` attribute, the function has a safe interface. Ditto for the other 3 functions.

2020-08-20 12:06 UTC, ntrel commented
> you can't have a generic method on an array

So adding method overloads for each type is not available as we add other algorithms in future.

One option would be to make the methods functions instead, and put them in a module called `algorithm`. E.g. `max<int>(arr)`. This technique also works for containers other than just arrays, so I recommend using functions instead. Other reviewers may disagree, let's see.

2020-08-20 12:07 UTC, ntrel commented
BTW GitHub has wrongly marked my code comment add outdated: https://github.com/vlang/v/pull/6177#discussion_r473824400

2020-08-20 19:47 UTC, mobarski commented
> So adding non-generic method overloads for each type is not scalable as we add other algorithms in future.

Yeah, generating similar code by hand feels wrong but I don'y see any other way now to achieve clean API without explicit type specification. While I don't mind it on "bigger" functions, `min<int>` feels wrong for me... I think that commonly used functions should heve short & clean API. But maybe I'm wrong and it's the price to pay for a "lean" language. 

> One option would be to make these methods functions instead, and put them in a module called `algorithm`. E.g. `max<int>(arr)`. This technique also works for containers other than just arrays, so I recommend using functions instead. Other reviewers may disagree, let's see.

Yeah (again), It's a solution that has clean implementation, results in a explicit api... but feels wrong to me.

`x := arrays.min<int>(a.filter(it>0).map(it*it))`
vs
`x := a.filter(it>0).map(it*it).min<int>()`
vs
`x := a.filter(it>0).map(it*it).min()`

2020-08-24 09:13 UTC, mobarski commented
I'll make an `arrays` module (analogy to the  strings module) and put theese functions there.
Do you think it's also a good place for various sorting related code for arrays: qsort, msort, bisect, heapify, merge etc?

2020-08-24 09:21 UTC, mobarski commented
> Introducing a temporary variable for every function call is not hygienic or convenient.

100÷ agree. It's also hard as we know that there are only two hard things in programming ;) On a more serious note - piping is also optimization friendly.

> We already break the one way rule in various ways when there's a good enough reason.

I'm aware of this and I'm open minded but I feel that breaking the rule should be a "last resort" move.

2020-08-24 09:32 UTC, medvednikov commented
There will be a method `.sorted()` that returns the result.

`.sort()` will keep modifying the array in place.

2020-08-24 15:39 UTC, JalonSolov commented
Modifying an immutable array in place seems like a bad idea...

2020-08-24 16:01 UTC, medvednikov commented
Why immutable? It's not.

2020-08-24 16:10 UTC, Delta456 commented
@JalonSolov Its like how Python does. `sorted()` **returns** the sorted array and `sort()` sorts i.e. **modifies** the array.

2020-08-24 16:17 UTC, JalonSolov commented
Python is not of interest to me.

Never mind about mutable vs immutable.  V does error out if you try to call .sort() on an immutable.

2020-08-24 21:58 UTC, mobarski commented
New arrays module with the following generic functions:
- **min** returns the minimum
- **max** returns the maximum
- **argmax** returns the index of the first minimum
- **argmax** returns the index of the first maximum
- **shuffle** randomizes the items of an array in place
- **all** checks if all array items are equal to given value


> @mobarski V won't need specifying what it already knows:
> `x := arrays.min(arr)`

@medvednikov This doesn't work for me, I must always specify the type:
```v
a := [8, 2, 6, 4]
assert arrays.argmin(a)==1
```
error: implicit declaration of function 'arrays__argmin' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

2020-08-25 07:05 UTC, ntrel commented
> I must always specify the type

It's not implemented yet.

> all checks if all array items are equal to given value

I'm not sure that's worth having - how often would it be used? It would be more useful if it had a function predicate parameter:
```v
all_even := all(arr, fn(e){e % 2 == 0})
```
(I omitted types for the lambda and return).

2020-08-25 07:10 UTC, medvednikov commented
Yeah, I agree. Have to keep the stdlib small and avoid duplication. No need in `all()` when we can just do `arr.filter(it == val)`

2020-08-25 07:12 UTC, ntrel commented
> arr.filter(it == val)

Doesn't that allocate an array?

2020-08-25 11:38 UTC, mobarski commented
> Yeah, I agree. Have to keep the stdlib small and avoid duplication. No need in `all()` when we can just do `arr.filter(it == val)`

`arr.filter(it == val).len==arr.len` is not exactly all() as the handling of the empty array is different

But I understand the need of a lean stdlib.

2020-08-25 13:15 UTC, mobarski commented
I've removed the `all()` function.

I've also changed the shuffle function to allow partial shuffle which will enable easy and efficient 'sample without repetitions' without introducing new function:
`sample_without_repetition(arr,4)` -> `shuffle(arr,4)[..4]`

And finally I've added the `merge` function.

2020-08-25 13:29 UTC, JalonSolov commented
How hard would it be to add `idxXXX` aliases for the `argXXX` routines, so those of us who aren't math majors (and haven't drunk the Python/numpy cool-aid) will know what the routines are supposed to do without having to look them up every time?

2020-08-25 13:35 UTC, Delta456 commented on vlib/arrays/arrays.v
> +}
I don't think we need this. We already have `arr << [2, 3, 4]` for that.

2020-08-25 14:06 UTC, mobarski commented
> How hard would it be to add `idxXXX` aliases for the `argXXX` routines, so those of us who aren't math majors (and haven't drunk the Python/numpy cool-aid) will know what the routines are supposed to do without having to look them up every time?

Oh, I would also prefer idxmin, idxmax but I've got the impression that V aims at being familiar to other languages (for example using <- for channels). I think that aliases are a no go as they contradict the 'one way' rule. I will happily change the name if more people agree.

2020-08-27 17:22 UTC, mobarski commented
Wouldn't idx_min / idx_max be even better names?

2020-08-28 14:18 UTC, ntrel requested changes

2020-08-28 14:18 UTC, ntrel commented on vlib/arrays/arrays.v
> +		if i != x {
Can you remove this if test please? Branching can be expensive and swapping a[i] with a[i] is ok anyway.

2020-08-28 14:18 UTC, ntrel commented on vlib/arrays/arrays_test.v
> +	assert b != c // false negative chance: 1/20!
A failing unit test is not acceptable whatever the chance. If you can set the seed then maybe the result of shuffle will be known?

2020-08-28 18:54 UTC, mobarski commented on vlib/arrays/arrays.v
> +		if i != x {
Done.

2020-08-28 18:54 UTC, mobarski commented on vlib/arrays/arrays_test.v
> +	assert b != c // false negative chance: 1/20!
Done.

2020-09-03 15:44 UTC, ntrel approved these changes

2020-09-07 11:50 UTC, merged