scanner: handler the case of "\r\n" line end
vlang/v pull request #6502
Opened 2020-09-28 05:57 UTC by lcddh

2020-09-28 07:16 UTC, SleepyRoy requested changes

2020-09-28 07:16 UTC, SleepyRoy commented on vlib/v/scanner/scanner.v
> +			if s.expect('\r\n', s.pos) {
could be simplified to
```V
if s.expect('\r\n', s.pos) {
	s.pos++
}
s.inc_line_number()
```

2020-09-28 17:28 UTC, spytheman commented
Please, can you add a test case for what this PR handles/fixes?

2020-09-29 01:04 UTC, lcddh commented
![image](https://user-images.githubusercontent.com/5841609/94500551-34a85700-0232-11eb-8ff5-c9c3f322201a.png)
In windows,if the file is "CRLF" line end,then the token's pos is not right, i just do not kown how to write the test code.

2020-09-29 03:39 UTC, medvednikov commented
This fixes line counter on windows, to test this we'd have to add a V program with windows line breaks (which should never be used, and git removes them, but that's another story) and errors and then make sure the V compiler reports correct line numbers.

2020-10-01 12:50 UTC, spytheman commented
I think we can enforce CRLF for a specific file with .gitattributes?

2020-10-02 03:19 UTC, medvednikov commented on vlib/v/scanner/scanner.v
> +			if s.expect('\r\n', s.pos) {
@lcddh yes please update this

2020-10-08 17:31 UTC, spytheman commented
A test file can be a  vlib/v/checker/tests/error_crlf_.vv and vlib/v/checker/tests/error_crlf_.out pair .
Files matching *_crlf_* in that folder are marked to be binary in vlib/v/checker/tests/.gitattributes.
See for example the already existing vlib/v/checker/tests/error_with_comment_with_crlf_ending.{vv,out} pair.

2020-10-14 08:40 UTC, spytheman commented
@lcddh Please, can you attach an example file, that exhibits the wrong behavour before this PR, I'll try to make a test for it, so it does not regress. As it is, I really do not understand the problem that this PR is solving, I am sorry :-| .

2020-10-18 12:21 UTC, closed without merging