gen: implement type_name method for sum type instances
vlang/v pull request #6802
Opened 2020-11-12 10:58 UTC by ntrel

`typeof(expr)` is planned to produce a type known at compile-time, not a string.
`typeof(expr).name` is the replacement for compile-time known types.
`sum.type_name()` is implemented here to get the name of the dynamic type held by sum type instance `sum`.

2020-11-12 11:06 UTC, Delta456 commented
What happens when someone tries to overload the function i.e. `type_name`?

2020-11-12 11:40 UTC, ntrel commented
@Delta456 Good point, I've now added an error for that.

2020-11-13 11:07 UTC, ntrel commented
An alternative would be e.g. `sum.type_.name()`. sum.type_ would be a value that wraps table.Type but not be directly readable to the user. The value would only be useful for its name method and for testing equality against another value.

2020-11-13 15:32 UTC, Delta456 commented
I believe `type_name` is fine because `type_.name` feels really empty i.e it must have some name after the `_`.

2020-11-13 17:36 UTC, spytheman commented on vlib/v/tests/typeof_test.v
> -	assert typeof(a) == 'int'
Please leave the typeof() tests for now as they are, and add new ones for .type_name() .
Until we are ready for the complete change, renaming test cases make typeof() less stable against regressions.

2020-11-13 17:38 UTC, spytheman requested changes
Good work, just please add additional tests for .type_name() itself.

2020-11-14 10:51 UTC, ntrel commented
@spytheman restored typeof(sum) test lines.

2020-11-14 11:59 UTC, merged