deprecate `strings.repeat(c, n)` and `strings.repeat_string(s, n)` an…
vlang/v pull request #6807
Opened 2020-11-12 14:34 UTC by Delta456

…d use `c.repeat(n) and `s.repeat(n)` instead

2020-11-12 15:22 UTC, trufae commented
Add spaces around the operators.

2020-11-12 15:33 UTC, Delta456 commented
Can you tell where I should add spaces?

2020-11-12 15:37 UTC, trufae requested changes
Also repeating a char is not the same as repeating a string. Will the string repeat nethod disapear?

2020-11-12 15:37 UTC, trufae commented on vlib/builtin/string.v
> +	blen := slen*count
Missing spaces

2020-11-12 15:37 UTC, trufae commented on vlib/builtin/string.v
> +				bytes[bislen+si] = s[si]
Same here

2020-11-12 16:12 UTC, Delta456 commented on vlib/builtin/string.v
> +	blen := slen*count
Done

2020-11-12 16:12 UTC, Delta456 commented on vlib/builtin/string.v
> +				bytes[bislen+si] = s[si]
Done

2020-11-12 16:35 UTC, JalonSolov commented
Agreed.  I expected `repeat_with_string` to be the default/only.  For example, that's all Go has.

2020-11-12 16:43 UTC, spaceface777 commented
`fn strings.repeat(c byte, n int) string` -> `fn (c byte) repeat(n int) string`
`fn strings.repeat_string(s string, n int) string` -> `fn (s string) repeat(n int) string`

Both functions still exist, and both are the default for their respective types.

2020-11-12 17:35 UTC, ntrel approved these changes

2020-11-12 17:35 UTC, ntrel commented on vlib/builtin/string.v
> +				bytes[bislen + si] = s[si]
I would expect memcpy to be faster than this inner loop, but it doesn't matter for this pull

2020-11-13 03:35 UTC, Delta456 commented on vlib/builtin/string.v
> +				bytes[bislen + si] = s[si]
I straight away copied the implementation from `strings.repeat_string` as it seemed to faster.

2020-11-13 17:05 UTC, medvednikov commented
So after looking at it, I think `fn strings.repeat(c byte, n int) string` should remain (it will later use `rune` instead of `byte` of course).

```
`a`.repeat(10) 
```

returning a string seems to be a bit unintuitive.

2020-11-13 17:08 UTC, medvednikov commented
Well it might make sense for `rune.repeat(10)` but not for `byte.repeat(10)`, so I would not do it like this until we fully replace bytes with runes.

2020-11-14 09:32 UTC, closed without merging