deprecate `strings.repeat_string`
vlang/v pull request #6824
Opened 2020-11-14 10:18 UTC by Delta456

New PR for https://github.com/vlang/v/pull/6807 as there were merge conflicts.

2020-11-14 10:28 UTC, ntrel requested changes

2020-11-14 10:28 UTC, ntrel commented on vlib/strings/strings_test.v
> -	assert strings.repeat_string('', 200) == ''
These tests need adapting and moving to `builtin/string_test.v`.

2020-11-14 11:09 UTC, Delta456 commented on vlib/strings/strings_test.v
> -	assert strings.repeat_string('', 200) == ''
Ok

2020-11-15 11:51 UTC, ntrel approved these changes

2020-11-15 12:34 UTC, merged