json2: decode fn returns `?T`; enable more tests
vlang/v pull request #6933
Opened 2020-11-24 09:57 UTC by nedpals

Since `?T` now work in a generic function, `json2.decode` will now return an option error instead of `panic`-ing. This also enables more set of tests (albeit implementing a custom `from_json` and `to_json` methods)

2020-11-24 10:05 UTC, danieldaeschle commented on vlib/x/json2/json2_test.v
>  	println(u2)
remove println

2020-11-24 10:06 UTC, danieldaeschle requested changes

2020-11-24 10:06 UTC, danieldaeschle commented on vlib/x/json2/json2_test.v
>  	println(out)
remove println

2020-11-24 10:06 UTC, danieldaeschle commented on vlib/x/json2/json2_test.v
>  		exit(1)
assert false

2020-11-24 10:06 UTC, danieldaeschle commented on vlib/x/json2/json2_test.v
>  		println('text')
remove println?

2020-11-24 10:06 UTC, danieldaeschle commented on vlib/x/json2/json2_test.v
>  	println(out)
remove that as well

2020-11-24 10:13 UTC, nedpals commented on vlib/x/json2/json2_test.v
>  	println(u2)
Should I? I was checking into `json_test.v` as well and it had that similar `println` too

2020-11-24 10:46 UTC, danieldaeschle commented on vlib/x/json2/json2_test.v
>  	println(u2)
yeah, remove.

2020-11-24 10:50 UTC, nedpals commented on vlib/x/json2/json2_test.v
>  	println(u2)
Ok

2020-11-24 11:30 UTC, danieldaeschle commented
CI is failing

2020-11-24 11:33 UTC, nedpals commented
@danieldaeschle Unrelated to the module. It's an error on `examples/links_scraper.v`

2020-11-24 11:56 UTC, medvednikov commented
macOS ci often has networking issues

2020-11-24 16:50 UTC, JalonSolov commented
Casting a string to int/float is not a valid json conversion.  In json, a string is a string and a number is a number.  It may be more "flexible", but it isn't valid.

It should continue to return 0 for non-numbers.

It should only try to convert the strings to valid numbers if there is a "non-strict" flag.

2020-11-25 00:16 UTC, nedpals commented
I don't see any harm in converting strings to ints since `strconv` takes care of it underneath. Besides, there are some instances wherein a single JSON field may be encoded either as a number or a string . Similarly, this is also what `bool()` does to strings too (converts a stringified true or false to a real boolean)

However, I've spun it off to a separate PR #6941 for further discussion.

2020-11-25 00:18 UTC, nedpals commented
CI is failing because of some markdown example failed to compile.

2020-11-25 07:04 UTC, danieldaeschle requested changes

2020-11-25 07:04 UTC, danieldaeschle commented on vlib/x/json2/builder.v
>  // Inserts a bool into the array.
sorry, not a edited line but we could do it either if you want.
comment should be: `insert_bool interts a null into the array.`

2020-11-25 07:04 UTC, danieldaeschle commented on vlib/x/json2/decoder.v
> +		.lcbr {
@medvednikov vfmt should format this to one line

@nedpals ignore it for now ;)

2020-11-25 07:04 UTC, danieldaeschle commented on vlib/x/json2/json2.v
> +	TODO: type check match src {
remove unused code please

2020-11-25 07:04 UTC, danieldaeschle commented on vlib/x/json2/json2.v
> +	// if typeof(typ).name in ['string', 'int', 'f64', 'f32', 'i64'] {
remove unused code please (everywhere)

2020-11-25 07:04 UTC, danieldaeschle commented on vlib/x/json2/json2.v
>  // A generic function that encodes a type into a JSON string.
make sure the docstring has the correct format

2020-11-25 07:04 UTC, danieldaeschle commented on vlib/x/json2/json2.v
> +		f32 { return f.str().int() }
why is str() needed? isn't it possible to cast a `f32` to an int?

2020-11-25 07:04 UTC, danieldaeschle commented on vlib/x/json2/json2_test.v
> +/*
remove unused code

2020-11-25 07:04 UTC, danieldaeschle commented on vlib/x/json2/json2_test.v
>  	// out := json.encode(numbers)
remove unused code

2020-11-25 07:04 UTC, danieldaeschle commented on vlib/x/json2/json2_test.v
>  fn test_parse_map() {
remove

2020-11-25 07:18 UTC, nedpals commented on vlib/x/json2/json2.v
> +	// if typeof(typ).name in ['string', 'int', 'f64', 'f32', 'i64'] {
This has been commented right now and I don't want to re-implement it once again.

2020-11-25 07:25 UTC, danieldaeschle commented on vlib/x/json2/json2.v
> +	// if typeof(typ).name in ['string', 'int', 'f64', 'f32', 'i64'] {
if you'' remove it later it's okay, oteherwise you have the git history :)

2020-11-25 13:46 UTC, nedpals commented
Sorry for the delay. I thought they we're submitted immediately by the time I added my feedback to the reviews lol

2020-11-25 13:47 UTC, danieldaeschle commented on vlib/x/json2/json2_test.v
>  fn test_parse_map() {
uncommented code

2020-11-25 13:48 UTC, danieldaeschle commented on vlib/x/json2/json2_test.v
>  	// out := json.encode(numbers)
ok, something like `TODO: replace with` would be nice

2020-11-25 13:48 UTC, danieldaeschle commented on vlib/x/json2/json2.v
>  // A generic function that encodes a type into a JSON string.
yes `function_name ...`

2020-11-25 14:24 UTC, JalonSolov commented on vlib/x/json2/json2.v
>  // A generic function that encodes a type into a JSON string.
V uses the "godoc" convention, which is "The comment is a complete sentence that begins with the name of the element it describes. This important convention allows us to generate documentation in a variety of formats, from plain text to HTML to UNIX man pages, and makes it read better when tools truncate it for brevity, such as when they extract the first line or sentence."  For example, documenting this way makes `modules.vlang.io` entries look much better.

2020-11-25 14:27 UTC, JalonSolov commented on vlib/x/json2/json2_test.v
>  fn test_parse_map() {
To expand:  He's asking you to remove the commented out code.  Unless you need it to be there for the next PR, coming soon, there's no need to keep commented-out code in the source.  `git history` can show you what changes have been made, you can diff between SHAs to see the code differences, etc.

2020-11-26 19:43 UTC, danieldaeschle commented
Does this solve https://github.com/vlang/v/issues/6726 ? Can you add a test?

2020-11-28 12:26 UTC, nedpals commented
> Does this solve #6726 ? Can you add a test?

Actually nope this does not since it's a C gen error. I'm adding tests for `Any` conversion for now.

2020-11-28 13:04 UTC, nedpals commented on vlib/x/json2/builder.v
>  // Inserts a bool into the array.
I'll be removing the builder methods on a separate PR so I leave it as is for now

2020-11-28 13:32 UTC, danieldaeschle approved these changes

2020-11-29 13:54 UTC, merged