x.websocket: Another try for go docs style of comments :)
vlang/v pull request #7091
Opened 2020-12-02 12:32 UTC by helto4real

Second attempt to comply to V docs style (go docs). #7047

2020-12-02 12:42 UTC, danieldaeschle commented on vlib/x/websocket/events.v
> +	ref      voidptr // referenced object
@medvednikov are field doc comments behind the field or above? would it be on the same line like [attributes]? then the line can be get really long...

2020-12-02 12:44 UTC, danieldaeschle commented on vlib/x/websocket/events.v
> +// on_message register a callback on new messages
```
on_message registers
                   ~
```

2020-12-02 12:44 UTC, danieldaeschle commented on vlib/x/websocket/events.v
> +// on_message_ref register a callback on new messages and provide a reference object
```
on_message_ref registers a callback on new messages and provides a reference object
                       ~                                       ~
```

2020-12-02 12:45 UTC, danieldaeschle commented on vlib/x/websocket/events.v
> +// on_open_ref register a callback on successful open and provide a reference object
on successful open**ing**

2020-12-02 12:46 UTC, danieldaeschle commented on vlib/x/websocket/events.v
> +// on_open register a callback on successful open
on successful open**ing**

2020-12-02 12:46 UTC, danieldaeschle commented on vlib/x/websocket/handshake.v
> +// handle_server_handshake manage websocket server handshake process
manage**s**

2020-12-02 12:47 UTC, danieldaeschle commented on vlib/x/websocket/handshake.v
> +// the response and secure key provided by websocket client
provided by **the** websocket client

2020-12-02 12:49 UTC, helto4real commented on vlib/x/websocket/events.v
> +	ref      voidptr // referenced object
Yea interesting question. I could not find clear rules about that. Fmt should handle it preferable

2020-12-02 13:01 UTC, danieldaeschle commented on vlib/x/websocket/message.v
> +	extended_payload16_end_byte = 4 // offset for extended lenght 16 bit of websocket header
not sure, but isn't `16 bit offset for extended lenght of websocket header` better?

2020-12-02 13:02 UTC, danieldaeschle commented on vlib/x/websocket/message.v
> +	opcode OPCode // defines the interpretation of the payload data
remove `defines the` please. I know that convention from my work and it's horrible. `interpretation of the payload data` is enough.

2020-12-02 13:02 UTC, danieldaeschle commented on vlib/x/websocket/message.v
> +	frame_size  int = 2	// size of the total frame
why that gap between comment and value?

2020-12-02 13:03 UTC, danieldaeschle commented on vlib/x/websocket/message.v
> +	payload_len int // payload lenght
typo: `length`

2020-12-02 13:04 UTC, danieldaeschle commented on vlib/x/websocket/message.v
> +	invalid_close_codes = [999, 1004, 1005, 1006, 1014, 1015, 1016, 1100, 2000, 2999, 5000, 65536] // List of invalid websocket close codes
this is not public and the comment describes the same as the constant name. remove it.

2020-12-02 13:08 UTC, danieldaeschle commented on vlib/x/websocket/websocket_client.v
> +// that implements the websocket capabilities
Maybe a `.` at the end of a sentence. I'm not sure right now if we should put a `.` everywhere. Not necesarry right now. But on multi line comments it should.

2020-12-02 13:08 UTC, danieldaeschle commented on vlib/x/websocket/websocket_client.v
> +// The client is a refactor of the original V-websocket client class
unnecessary information

2020-12-02 13:09 UTC, danieldaeschle commented on vlib/x/websocket/websocket_client.v
>  // check with valgrind if you do any changes in the free calls
`.`

2020-12-02 13:10 UTC, danieldaeschle commented on vlib/x/websocket/websocket_test.v
>  	s.listen() or {
```
s.listen()?
```

2020-12-02 13:11 UTC, danieldaeschle commented on vlib/x/websocket/websocket_test.v
> +		// not used
remove that comment, just collapse the body

2020-12-02 13:12 UTC, danieldaeschle commented on vlib/x/websocket/websocket_server.v
> +// free manage manual free of memory for Server instance
manage**s**

2020-12-02 13:12 UTC, danieldaeschle commented on vlib/x/websocket/websocket_server.v
> +// accept_new_client creates a new client instance for client that connects to socket
to **the** socket

2020-12-02 13:13 UTC, danieldaeschle commented on vlib/x/websocket/websocket_server.v
> +// serve_client accepts incoming connection and setup the callbacks
set**s** up

2020-12-02 13:13 UTC, danieldaeschle commented on vlib/x/websocket/websocket_server.v
> +		// todo: replace for with s.clients.delete_all(clients_to_remove) if (https://github.com/vlang/v/pull/6020) merges
`TODO:` is correct

2020-12-02 13:16 UTC, danieldaeschle commented on vlib/x/websocket/websocket_server.v
> +	client        &Client // client instance
remove unnecessary comment, same above.

2020-12-02 13:18 UTC, Larpon commented on vlib/x/websocket/websocket_client.v
> +// that implements the websocket capabilities
I've added punctuation when I could. It's more grammatical correct I guess :man_shrugging:

2020-12-02 13:19 UTC, Larpon commented on vlib/x/websocket/websocket_server.v
> +		// todo: replace for with s.clients.delete_all(clients_to_remove) if (https://github.com/vlang/v/pull/6020) merges
What about the `TODO(<username>)`? (I've seen it used in Go's sources)

2020-12-02 13:31 UTC, danieldaeschle commented on vlib/x/websocket/websocket_server.v
> +// ServerClient represent a connected client
`represents`, don't know if we need to document ALL private stuff. most names are self explained. less is more sometimes.

2020-12-02 13:32 UTC, danieldaeschle requested changes
try to figure out which comment of private stuff is really necessary.
`foo // represents foo` is not needed and can be ommitet. if you changed my suggestions i'll take a deeper look again.

2020-12-02 13:33 UTC, danieldaeschle commented on vlib/x/websocket/websocket_server.v
> +		// todo: replace for with s.clients.delete_all(clients_to_remove) if (https://github.com/vlang/v/pull/6020) merges
maybe optional... but not required.

2020-12-02 13:47 UTC, JalonSolov commented on vlib/x/websocket/events.v
> +// on_open_ref register a callback on successful open and provide a reference object
This one is actually ok as-is.  'open' is the action referenced.

2020-12-02 13:47 UTC, JalonSolov commented on vlib/x/websocket/events.v
> +// on_open register a callback on successful open
Same as previous.

2020-12-02 13:48 UTC, JalonSolov commented on vlib/x/websocket/handshake.v
> +// the response and secure key provided by websocket client
Adding `the` is more grammatically correct, but it works ok without it as it is simply a more terse form.

2020-12-02 13:48 UTC, spytheman commented on vlib/x/websocket/utils.v
> +// get_nonce creates an randomized array used in handshake process
creates `a` randomized

2020-12-02 13:52 UTC, spytheman commented on vlib/x/websocket/websocket_server.v
> +// ServerClient represent a connected client
I think that here, the 'connected client' is useful addition, that otherwise would have to be deduced by the reader.

2020-12-02 13:53 UTC, spytheman commented on vlib/x/websocket/websocket_server.v
> +		// todo: replace for with s.clients.delete_all(clients_to_remove) if (https://github.com/vlang/v/pull/6020) merges
`TODO:` is easy to search for, it should stay in uppercase indeed.

2020-12-02 13:54 UTC, danieldaeschle commented on vlib/x/websocket/websocket_server.v
> +// ServerClient represent a connected client
yeah ok :)

2020-12-02 13:56 UTC, spytheman commented on vlib/x/websocket/websocket_test.v
>  	s.listen() or {
`s.listen()?` is not the same as `s.listen() or {}`; the first will propagate the error to the caller, the second will ignore the error completely; I do not know what is appropriate for this context though.

2020-12-02 14:04 UTC, helto4real commented on vlib/x/websocket/websocket_client.v
> +// The client is a refactor of the original V-websocket client class
Agree on line 1-2 but I want to attribution to thecorrer that made the first implementation. I make this more specific.
Will narrow it down to
```
// websocket module implements websocket client and a websocket server
// attribution: @thecoderr the author of original websocket client 
```

2020-12-02 14:05 UTC, danieldaeschle commented on vlib/x/websocket/websocket_test.v
>  	s.listen() or {
the upper one returns an optional as well. if not with `?` then do `or {}`

2020-12-02 14:05 UTC, helto4real commented on vlib/x/websocket/websocket_client.v
>  // check with valgrind if you do any changes in the free calls
will remove most of this text except attribution. It is not really needed.

2020-12-02 14:08 UTC, JalonSolov commented on vlib/x/websocket/message.v
> +	extended_payload16_end_byte = 4 // offset for extended lenght 16 bit of websocket header
leng**th**, not leng**ht** (this appears several times), and yes could be worded better.  This one and the one above for `extended_payload64_end_byte`.

```v
	extended_payload16_end_byte = 4 // Header length with 16-bit extended payload
	extended_payload64_end_byte = 10 // Header length with 64-bit extended payload
```

2020-12-02 14:09 UTC, helto4real commented on vlib/x/websocket/websocket_test.v
>  	s.listen() or {
Yea I will go through the tests when I move it to net module from x. I want to refactor it a bit more. I take this comment with me doing this. Think we will could potentially fail without failing tests looking at the test as written now.

2020-12-02 14:18 UTC, helto4real commented on vlib/x/websocket/websocket_server.v
> +// ServerClient represent a connected client
Yea think I will refactor the names when moving to net.websocket from x.net.websocket I will remove comments then

2020-12-02 14:20 UTC, helto4real commented on vlib/x/websocket/websocket_server.v
> +	client        &Client // client instance
> try to figure out which comment of private stuff is really necessary.
> `foo // represents foo` is not needed and can be ommitet. if you changed my suggestions i'll take a deeper look again.

Yea agree, as stated I will refactor naming prior move to net.websocket from x.websocket

2020-12-02 14:35 UTC, JalonSolov commented
You need a global search and replace to change `lenght` to `length`.

2020-12-02 14:53 UTC, helto4real commented on vlib/x/websocket/message.v
> +	frame_size  int = 2	// size of the total frame
Weird the gap is not present in vscode ???

2020-12-02 14:55 UTC, helto4real commented
> You need a global search and replace to change `lenght` to `length`.

Fixed... I need to learn how to spell that :)

2020-12-02 14:58 UTC, helto4real commented
> d and can b



> try to figure out which comment of private stuff is really necessary.
> `foo // represents foo` is not needed and can be ommitet. if you changed my suggestions i'll take a deeper look again.

If you want to help me review the planned refactor moving from x module to net module I will go through naming of naming. Specifically private functions and make them clearer. Many of them are from the original code. Better names I can remove alot of those comments as well for private functions.

2020-12-02 15:03 UTC, danieldaeschle commented
i think everyone here can help, i haven't used the websocket module once.

2020-12-02 15:08 UTC, danieldaeschle commented on vlib/x/websocket/events.v
> +	handler2 SocketCloseFn2 // callback function with reference
of course, this is a bad naming.

2020-12-02 15:08 UTC, danieldaeschle commented
maybe we can make renaming in an extra PR with an issue which collects all naming issues.

2020-12-02 16:08 UTC, helto4real commented on vlib/x/websocket/events.v
> +	handler2 SocketCloseFn2 // callback function with reference
yea agree, but the purpose of PR is comments. Will fix in other PR

2020-12-02 18:06 UTC, helto4real commented
> maybe we can make renaming in an extra PR with an issue which collects all naming issues.

Made issue and assigned myself #7098.

2020-12-03 09:05 UTC, Larpon requested changes

2020-12-03 09:05 UTC, Larpon commented on vlib/x/websocket/websocket_server.v
> +// new_server instance a new websocket server on provided port and route
```// new_server instantiate a new websocket server on `port` using `route` ```

2020-12-03 09:05 UTC, Larpon commented on vlib/x/websocket/websocket_server.v
> +// listen start listen and process to incoming connections from websocket clients
`// listen start listening and process incoming connections from websocket clients`

2020-12-03 09:05 UTC, Larpon commented on vlib/x/websocket/websocket_server.v
> +// Close closes server (not implemented yet)
closes **the** server

2020-12-03 09:05 UTC, Larpon commented on vlib/x/websocket/websocket_server.v
> +// serve_client accepts incoming connection and sets up the callbacks
accepts **the** incoming

2020-12-03 09:05 UTC, Larpon commented on vlib/x/websocket/websocket_server.v
> +// accept_new_client creates a new client instance for client that connects to the socket
for **the** client that

2020-12-03 09:05 UTC, Larpon commented on vlib/x/websocket/websocket_server.v
> +// free manages manual free of memory for Server instance
`// free frees all memory allocated by the Server instance`

2020-12-03 09:07 UTC, Larpon commented
Sorry to gramma-slam you @helto4real - your work is much appreciated! :sweat_smile:

2020-12-03 09:52 UTC, helto4real commented
> Sorry to gramma-slam you @helto4real - your work is much appreciated! 😅
> I think you've might have become somewhat of a guinea pig for us to find out the way documentation should be written, hang in there!

No worries, I was thinking the same. This is why I took action to make it better. Lets make this close to how the quality bar of docs should be. I am greatful since English is not my native language obviously ;) It’s the final result that counts!

2020-12-03 19:19 UTC, spytheman commented
I think that is going to be one of the most commented PRs in this repository :smile: .

2020-12-03 19:34 UTC, JalonSolov commented
Heh.  I think it's a the point where it should probably be merged, and any lingering issues can be cleaned up after the `x/websocket` -> `net/websocket` move.

2020-12-04 00:52 UTC, merged