net.html: Polishing, update docs
vlang/v pull request #7193
Opened 2020-12-08 05:46 UTC by nedpals

This PR updates the `net.html` module in its entirety. The following are the changes included in this PR:
- Removes hacks used when it was developed on the old compiler.
- Remove `limit.h`. Hard `int_min` and use `== 0` for `C.NULL`
- Use `strings.Builder` for concatenating strings.
- Update most of the byte comparisons from `== <byte number>` to `== `<char>`
- Update tests
- Add functions such as `parse` and `parse_file` to parse HTML without manually creating a `Parser` instance.
- Update `README` and transferred the docs section to its respective function names. Rewrote and simplified some of the parts

Please take note that there are still some (non-deal breaking) issues that are yet to be fixed and I will be creating a separate PR for it whenever I have the time.

2020-12-08 05:55 UTC, nedpals commented
@Jictyvoo I refactored and changed some of the stuff. What do you think?

2020-12-08 16:18 UTC, Jictyvoo commented on vlib/net/html/parser.v
> +				parser.lexical_attributes.open_string == string_code {
This probably doesn't make a big difference, but if in input receive `"` to open the string, and after that receive `'`, the original `"` will be replaced as the string opener. I choose keep nested ifs

2020-12-08 16:22 UTC, JalonSolov commented on vlib/net/html/README.md
> +More examples found on [`parser_test.v`](parser_test.v) and [`html_test.v`](html_test.v)
`found in` rather than `found on`

2020-12-08 16:35 UTC, JalonSolov commented on vlib/net/html/dom.v
> +// get_tag_by_attribute_value retrieves all the tags in the document that has the given attribute name and value.
`that have` rather than `that has`

2020-12-08 16:35 UTC, JalonSolov commented on vlib/net/html/dom.v
> +// get_tag retrieves all the tags in the document that has the given tag name.
`that have` rather than `that has`

2020-12-08 16:35 UTC, JalonSolov commented on vlib/net/html/dom.v
> +// get_tag_by_attribute retrieves all the tags in the document that has the given attribute name.
`that have` rather than `that has`

2020-12-08 16:35 UTC, JalonSolov commented on vlib/net/html/html.v
> +// parse parses and returns the DOM from the given text.
Feels awkward to have `parse parses`... how about `parse returns the DOM parsed from the given text`

2020-12-08 16:35 UTC, JalonSolov commented on vlib/net/html/parser.v
> +// Parser is responsible for reading the HTML strings and converting them into a `DocumentObjectModel`.
`Parser` is a struct.  It isn't responsible for reading anything, it only stores things.  Functions with a Parser instance as a receiver do things.

2020-12-08 16:35 UTC, JalonSolov commented on vlib/net/html/parser.v
> +// This function is used to add a tag for the parser ignore it's content.
`// add_code_tag adds a tag whose content will be ignored by the parser.`

2020-12-08 16:35 UTC, JalonSolov commented on vlib/net/html/parser.v
> +// split_parse parses the HTML fragment
`an HTML fragment`

2020-12-08 16:35 UTC, JalonSolov commented on vlib/net/html/parser.v
> +// parse_html parses the given HTML string
`parses the given string as HTML`

2020-12-08 16:35 UTC, JalonSolov commented on vlib/net/html/tag.v
> +// Tag holds the information of an HTML tag.
`// Tag contains data about an HTML tag.`

2020-12-08 16:47 UTC, Jictyvoo reviewed
@nedpals Sorry, only have time to review it now. I like yout changes, really improved the code, I leave 2 comments. One about a nested if, I think is better keep as the original, and the other is a question about File reading.  Removing getters made the code easier to read, and probably get away of some reference bugs.

And update of the byte comparisons from `== <byte number>` to `== <character>` was a awesome update, I've been thinking on updating it, but never had time to do it.
Great job, congrats

2020-12-08 16:47 UTC, Jictyvoo commented on vlib/net/html/parser.v
> +				parser.lexical_attributes.open_string == string_code {
This probably doesn't make a big difference, but if in input receive " to open the string, and after that receive ', the original " will be replaced as the string opener. I choose keep nested ifs

2020-12-08 16:47 UTC, Jictyvoo commented on vlib/net/html/html.v
> +	content := os.read_file(filename) or { return DocumentObjectModel{
Parser.v has a method called `parse_html`, which divides the lines in the file and analyzes them line by line. If you have a way to continue reading each line and analyze it, so as not to put the whole string in memory, it would be great, but only if you have a way to do it.

2020-12-08 16:47 UTC, Jictyvoo commented on vlib/net/html/parser.v
> +	mut lines := data.split_into_lines()
Nice optimization

2020-12-08 16:50 UTC, Jictyvoo commented
@nedpals about the "(non-deal breaking) issues", you can list some? I can take a look at it later and try to fix

2020-12-08 16:54 UTC, Jictyvoo commented
@nedpals about the "(non-deal breaking) issues", you can list some? I can take a look at it later and try to fix
I also noticed in the line https://github.com/vlang/v/blob/90c1c639fe8c60bc02f6c97591e5f8a73b8a83ae/vlib/net/html/parser_test.v#L17
that in HTML if you have something like 
```html
<bo

dy>
```
the parser takes `bo` as tag name, you think we need to fix it?

2020-12-09 19:02 UTC, danieldaeschle requested changes

2020-12-09 19:02 UTC, danieldaeschle commented on vlib/net/html/html_test.v
> +	// assert h1_tag.str() == '<h1 class="title">Hello world!</h1>'
remove this line?

2020-12-09 19:02 UTC, danieldaeschle commented on vlib/net/html/parser.v
> +// split_parse parses the HTML fragment
punctuation?

2020-12-09 19:02 UTC, danieldaeschle commented on vlib/net/html/parser.v
> +// parse_html parses the given HTML string
`.`

2020-12-09 19:08 UTC, medvednikov commented
I've merged this for now since it's not a priority atm.

2020-12-09 19:08 UTC, merged