array: add more docs
vlang/v pull request #7194
Opened 2020-12-08 08:51 UTC by Delta456

Add docs for `buitlin/array.v` as https://github.com/vlang/v/issues/7047

2020-12-08 08:52 UTC, Delta456 commented on vlib/builtin/array.v
> +// extra code for every type
I didn't know where to place but as it is an important comment so we should put it somewhere.

2020-12-08 09:15 UTC, danieldaeschle commented
I will review it tomorrow

2020-12-08 13:15 UTC, JalonSolov commented on vlib/builtin/array.v
> +// array.data uses a void pointer allows to implement arrays without generics and without generating
`// array.data uses a void pointer, which allows implementing arrays without generics and without generating`

2020-12-08 13:54 UTC, Gladear commented on vlib/builtin/array.v
> +	element_size int // element_size is no. of elements in the array
element_size is the size in bytes of one element in the array (maybe it shouldn't be public btw).
len does represent the number of elements in the array 🙂

2020-12-08 18:40 UTC, medvednikov commented on vlib/builtin/array.v
> +	element_size int // element_size is size in bytes of one element in the array
there's no need to prefix struct fields comments with their names

2020-12-08 20:32 UTC, JalonSolov commented on vlib/builtin/array.v
> +// // array.data uses a void pointer, which allows implementing arrays without generics and without generating
Extra `//`  :-)

2020-12-09 08:44 UTC, Delta456 commented on vlib/builtin/array.v
> +// // array.data uses a void pointer, which allows implementing arrays without generics and without generating
I had fixed it earlier in the second last commit.

2020-12-09 18:52 UTC, danieldaeschle requested changes

2020-12-09 18:52 UTC, danieldaeschle commented on vlib/builtin/array.v
> +// array is a builtin struct used for denoting array types in V
I'm not sure if `array is used for denoting array types in V` might be enough.

2020-12-09 18:52 UTC, danieldaeschle commented on vlib/builtin/array.v
> +	data         voidptr // array data
`data of the array` then?

2020-12-09 18:52 UTC, danieldaeschle commented on vlib/builtin/array.v
> +	data         voidptr // array data
or something like: `data that the array holds`

2020-12-09 18:52 UTC, danieldaeschle commented on vlib/builtin/array.v
> +// array.data uses a void pointer, which allows implementing arrays without generics and without generating
move this documentation to the field?

2020-12-09 18:52 UTC, danieldaeschle commented on vlib/builtin/array.v
> +// reverse_in_place reverses the array in place
Since i don't know what the function does, the documentation doesn't help me. What does in place mean? You explain the behvaiour with the same words in the name of the function. Not helpful, sorry.

2020-12-09 18:52 UTC, danieldaeschle commented on vlib/builtin/array.v
> +// index returns the index of the first element equal to the given value,
`returns the first index at which a given element can be found in the array`

2020-12-09 18:52 UTC, danieldaeschle commented on vlib/builtin/array.v
> +// eq checks if the arrays have the same element or not
element**s** ?

2020-12-09 18:52 UTC, danieldaeschle commented on vlib/builtin/array.v
> +// TODO: make it generic or use compiler magic??
In builtin we won't have generics, so this should be: `TODO: make this work with all types` or something similar.

2020-12-09 18:58 UTC, danieldaeschle commented
Can you add punctuation?

2020-12-10 04:01 UTC, Delta456 commented on vlib/builtin/array.v
> +// array.data uses a void pointer, which allows implementing arrays without generics and without generating
This comment is big to be fitted in that field.

2020-12-10 04:03 UTC, Delta456 commented on vlib/builtin/array.v
> +// array is a builtin struct used for denoting array types in V
I think `builtin struct` is necessary as it highlights that this structure was implemented in `builtin.v`.

2020-12-10 04:04 UTC, Delta456 commented on vlib/builtin/array.v
> +	data         voidptr // array data
I will be going with `data of the array`.

2020-12-10 04:06 UTC, Delta456 commented on vlib/builtin/array.v
> +// reverse_in_place reverses the array in place
This function reverses i.e. modifies the original array. It's like `sort` method of Python's list.

2020-12-10 04:07 UTC, Delta456 commented on vlib/builtin/array.v
> +// TODO: make it generic or use compiler magic??
Ok

2020-12-10 04:07 UTC, Delta456 commented on vlib/builtin/array.v
> +// eq checks if the arrays have the same element or not
Yes

2020-12-10 04:08 UTC, Delta456 commented
> Can you add punctuation?

Will do so

2020-12-10 08:11 UTC, danieldaeschle commented on vlib/builtin/array.v
> +// array.data uses a void pointer allows to implement arrays without generics and without generating
If the comment is to long it should be above the field according to alex.

2020-12-10 08:13 UTC, danieldaeschle commented on vlib/builtin/array.v
> +// array is a builtin struct used for denoting array types in V
Isn‘t it obvious? Otherwise, why does it help knowing that it‘s places in builtin?
@medvednikov what do you think.

2020-12-10 08:14 UTC, danieldaeschle commented on vlib/builtin/array.v
> +// array.data uses a void pointer, which allows implementing arrays without generics and without generating
If the comment is to long it should be above the field according to alex.

2020-12-10 08:15 UTC, danieldaeschle commented on vlib/builtin/array.v
> +// reverse_in_place reverses the array in place
Write it down in the docs to make it clear :D

2020-12-10 13:47 UTC, JalonSolov commented on vlib/builtin/array.v
> +// reverse_in_place reverses the array in place
`// reverse_in_place reverses existing array data in place`

2020-12-10 14:52 UTC, Delta456 commented on vlib/builtin/array.v
> +// reverse_in_place reverses the array in place
@JalonSolov way better

2020-12-10 17:25 UTC, danieldaeschle commented
Wait for this result: https://github.com/vlang/v/discussions/7245

2020-12-10 17:26 UTC, danieldaeschle commented
Last two topics. If they're resolved it can be merged :)
nice work. keep going!

2020-12-13 08:31 UTC, medvednikov commented on vlib/builtin/array.v
> +// array is a builtin struct used for denoting array types in V
Indeed, this comment doesn't add any valuable information.

2020-12-13 08:32 UTC, medvednikov commented on vlib/builtin/array.v
> +	data         voidptr // data of the array
unnecessary

2020-12-13 10:35 UTC, Delta456 commented on vlib/builtin/array.v
> +// array is a builtin struct used for denoting array types in V
Ok

2020-12-13 10:35 UTC, Delta456 commented on vlib/builtin/array.v
> +	data         voidptr // data of the array
if we are adding comments for every field then I feel it's also needed for this as well.

2020-12-13 11:19 UTC, danieldaeschle commented on vlib/builtin/array.v
> +	data         voidptr // data of the array
only necessary comments. Or describe it better. This comment says nothing about the field. It has the same value like no comment.

2020-12-13 13:45 UTC, Delta456 commented on vlib/builtin/array.v
> +	data         voidptr // data of the array
Can you suggest a better alternative if possible?

2020-12-13 13:46 UTC, Delta456 commented on vlib/builtin/array.v
> +	data         voidptr // data of the array
Ok

2020-12-13 16:44 UTC, danieldaeschle commented on vlib/builtin/array.v
> +	data         voidptr // data of the array
Maybe data doesn‘t need to be documented but len and cap. Len could be: the current length/count of items in the array
Cap: the full capacity of items which the array can hold.

2020-12-15 08:31 UTC, merged