time: complete documentation
vlang/v pull request #7225
Opened 2020-12-09 23:21 UTC by theoo3

This PR completes all documentation in the time module (#7047).
One issue I noticed is that vdoc did not generate documentation for `sys_mono_now` and `now`. They both used `$if`.

2020-12-10 09:28 UTC, spytheman commented on vlib/time/misc/misc.v
> +// random returns a random time struct in *the past*. It is seeded from the unix time at the start of the program.
The time is not seeded. It is just bounded till the start time of the program, i.e. that guarantees that it is in the past.

2020-12-10 09:29 UTC, spytheman commented on vlib/time/stopwatch.v
>  pub struct StopWatchOptions {
StopWatchOptions is a struct, it does not do anything by itself. It just serves as a parameter to time.new_stopwatch.

2020-12-10 09:30 UTC, spytheman commented on vlib/time/stopwatch.v
>  pub struct StopWatch {
Structs do not do anything, they just contain data. Functions/methods do things.

2020-12-10 09:33 UTC, spytheman commented on vlib/time/stopwatch.v
>  pub fn (mut t StopWatch) start() {
That looks very redundant to me. In the previous formulation, `Starts` was like the start of a new sentence. Now it is just
repetition - `start starts the stopwatch` may be reformulated to just `start the stopwatch`, with no loss of meaning.

2020-12-10 09:34 UTC, spytheman commented on vlib/time/stopwatch.v
>  pub fn (mut t StopWatch) restart() {
same - `restart the stopwatch` is less redundant imho.

2020-12-10 09:36 UTC, spytheman commented on vlib/time/time.v
> +// FormatDelimiter enumerates different time/date delemiters
`delimiters`

2020-12-10 09:40 UTC, spytheman commented on vlib/time/time_darwin.c.v
>  fn sys_mono_now_darwin() u64 {
The sys_mono_now_*** functions return a monotonically increasing time, not just any kind of time. 
For example during daylight savings changes, ordinary time can jump backwards, but that should not affect the values returned by the sys_mono_now_*** functions.

2020-12-10 09:41 UTC, spytheman commented on vlib/time/time_nix.c.v
>  pub fn sys_mono_now() u64 {
This is misleading. The goal of sys_mono_now() is to get a monotonically increasing timestamp, not just any kind of os time.

2020-12-10 09:42 UTC, spytheman commented on vlib/time/time_windows.c.v
>  pub fn sys_mono_now() u64 {
same - this is misleading. sys_mono_now returns a monotonically increasing timestamp, not just any kind of os time.

2020-12-11 17:03 UTC, danieldaeschle commented on vlib/time/misc/misc.v
> +	// start_time_unix is set when the program is started
comment should be on the same line, next to the constant.

2020-12-11 17:04 UTC, danieldaeschle commented on vlib/time/stopwatch.v
>  pub fn (mut t StopWatch) start() {
but then it should be `starts the stopwatch`. I think `start starts the stopwatch` is ok.

2020-12-11 17:05 UTC, danieldaeschle commented on vlib/time/stopwatch.v
> +// stop stops the timer, even if the time is running
punctuation.

2020-12-11 17:05 UTC, danieldaeschle commented on vlib/time/stopwatch.v
> +// pause pauses the timer
punctuation.

2020-12-11 17:05 UTC, danieldaeschle commented on vlib/time/stopwatch.v
> +// stop stops the timer, even if the time is running
Can it be stopped when time is not running?

2020-12-11 17:05 UTC, danieldaeschle commented on vlib/time/time.v
> +// Time contains various time units for a point in time
punctuation.

2020-12-11 17:06 UTC, danieldaeschle commented on vlib/time/time.v
> +// Time contains various time units for a point in time
everywhere please.

2020-12-11 17:07 UTC, danieldaeschle commented on vlib/time/time.v
> +// FormatDelimiter enumerates different time/date delimiters
an enum enumerates? Yeah ok... Could it be like `FormatDelimiter contains different time/date delimiteres`?

2020-12-11 17:09 UTC, danieldaeschle commented on vlib/time/time.v
>  pub struct C.timeval {
Should a C struct be public?

2020-12-11 17:10 UTC, danieldaeschle commented on vlib/time/time_windows.c.v
> +// dummy to compile with all compilers
`darwin_utc is a dummy function to compile with all compilers` ? I'm not sure what it does.

2020-12-11 17:11 UTC, danieldaeschle commented
If this will be merged, check the checkboxes on https://github.com/vlang/v/issues/7047

2020-12-11 21:09 UTC, JalonSolov commented on vlib/time/format.v
> +// This is just a TEMPORARY function for cookies and their expire dates.
Should be `expiration` instead of `expire`

2020-12-17 04:09 UTC, crthpl commented on vlib/time/misc/misc.v
> +	start_time_unix = time.now().unix // start_time_unix is set when the program is started
@danieldaeschle said that is should be on the next line

2020-12-17 07:16 UTC, danieldaeschle commented on vlib/time/misc/misc.v
> +	start_time_unix = time.now().unix // start_time_unix is set when the program is started
We're not sure right now: https://github.com/vlang/v/discussions/7245

It's defenitely better to have it on the same line if it goes (for now).

2020-12-17 07:18 UTC, danieldaeschle commented on vlib/time/misc/misc.v
> +	start_time_unix = time.now().unix // start_time_unix is set when the program is started
but it think even there we should have punctuation.

2020-12-17 07:20 UTC, danieldaeschle commented on vlib/time/stopwatch.v
> +// new_stopwatch returns a new stopwatch with StopWatchOptions.
`new_stopwatch initializes a new StopWatch with the current time as start`

2020-12-17 07:20 UTC, danieldaeschle commented on vlib/time/stopwatch.v
> +// start the stopwatch. If the timer was paused, restarts counting.
i'm for `start starts the stopwatch.`

2020-12-17 07:21 UTC, danieldaeschle commented on vlib/time/stopwatch.v
> +// restart the stopwatch. If the timer was paused, restarts counting.
same like on start

2020-12-17 07:21 UTC, danieldaeschle commented on vlib/time/stopwatch.v
> +// stop stops the timer, regardless of running state.
`...by setting the end time to the current time`

2020-12-17 07:23 UTC, danieldaeschle commented on vlib/time/stopwatch.v
> +// pause pauses the timer.
```
pause resets the `start` time sets adds the current elapsed time to `elapsed`.
```

2020-12-17 07:24 UTC, danieldaeschle requested changes
still some things to edit :)

2020-12-17 20:06 UTC, JalonSolov commented on vlib/time/stopwatch.v
>  pub fn (mut t StopWatch) start() {
start resumes after the stopwatch has been paused.

2020-12-17 20:11 UTC, JalonSolov commented on vlib/time/stopwatch.v
>  pub fn (mut t StopWatch) restart() {
restart reinitializes the stopwatch, clearing elapsed time, and setting the start time to the current time.

2020-12-17 20:14 UTC, JalonSolov commented on vlib/time/stopwatch.v
> +// stop stops the timer, even if the time is running
stop sets the end time to current time, effectively ceasing increases in elapsed time.

2020-12-17 20:16 UTC, JalonSolov commented on vlib/time/stopwatch.v
> +// pause pauses the timer
pause calculates current elapsed time, and stops the timer from counting.

2020-12-31 20:13 UTC, crthpl commented
Most of the CIs are failing with the following error:
```
==================
/tmp/v/vself.9811566871879746134.tmp.c:12375:16: error: redefinition of ‘time__Time__minus’
 time__Duration time__Time__minus(time__Time lhs, time__Time rhs) {
                ^~~~~~~~~~~~~~~~~
/tmp/v/vself.9811566871879746134.tmp.c:11879:23: note: previous definition of ‘time__Time__minus’ was here
 inline time__Duration time__Time__minus(time__Time lhs, time__Time rhs) {
                       ^~~~~~~~~~~~~~~~~
...
==================
```
Should an issue be opened?

2021-01-08 14:22 UTC, Delta456 commented
Please rebase

2021-01-12 20:07 UTC, crthpl commented
Ok this PR is irrecoverable. Opening new one.

2021-01-12 20:07 UTC, closed without merging