checker: ban any types outside buitlin
vlang/v pull request #7675
Opened 2020-12-29 07:56 UTC by Delta456

2020-12-29 08:04 UTC, nedpals approved these changes

2020-12-29 08:19 UTC, spytheman commented on vlib/v/checker/checker.v
> +	inside_unsafe                    bool // are we inside `unsafe{}`?
hm, these comments just duplicate the field names?

2020-12-29 08:22 UTC, Delta456 commented on vlib/v/checker/checker.v
> +	inside_unsafe                    bool // are we inside `unsafe{}`?
I think it should be consistent with the comment of `is_builtin_mod`.

2020-12-29 08:22 UTC, Delta456 commented
I will add checker tests later.

2020-12-29 11:44 UTC, medvednikov commented on vlib/v/checker/checker.v
> +	inside_unsafe                    bool // are we inside `unsafe{}`?
no need in this comment

2020-12-29 11:48 UTC, danieldaeschle commented
instead of having extra errors for this types shouldn't it behave like they just don't exist?

2020-12-29 11:50 UTC, Delta456 commented
> 
> 
> instead of having extra errors for this types shouldn't it behave like they just don't exist?

Many people already would have used it in their work. I think extra errors are fine in this case to explain the users as why they where made in the first place.

2020-12-29 12:04 UTC, danieldaeschle commented
> > instead of having extra errors for this types shouldn't it behave like they just don't exist?
> 
> Many people already would have used it in their work. I think extra errors are fine in this case to explain the users as why they were made in the first place.

V is still in progress. They can't rely on features like that. However, the error should disappear in long term like it never existed.

2020-12-29 13:57 UTC, Delta456 commented
> 
> 
> > > instead of having extra errors for this types shouldn't it behave like they just don't exist?
> > 
> > 
> > Many people already would have used it in their work. I think extra errors are fine in this case to explain the users as why they were made in the first place.
> 
> V is still in progress. They can't rely on features like that. However, the error should disappear in long term like it never existed.

Done

2020-12-29 14:41 UTC, danieldaeschle requested changes

2020-12-29 14:41 UTC, danieldaeschle commented on vlib/v/ast/ast.v
> +	receiver_pos    token.Position // receiver's position
remove that comment

2020-12-29 14:41 UTC, danieldaeschle commented on vlib/v/ast/ast.v
> +	method_type_pos token.Position // `User` in `(u User)` position
position of `User` in `fn (u User)`

2020-12-29 14:41 UTC, danieldaeschle commented on vlib/v/ast/ast.v
> +	body_pos        token.Position // function body's position
`body's` without the `'` is gramatically more correct afaik.

2020-12-29 14:41 UTC, danieldaeschle commented on vlib/v/checker/checker.v
> +				c.error('unknown type `$sym.name`', field.type_pos)
is `any_int` and `any_float` in `table.known_type_names`? or why didn't you merge it with the upper condition?

2020-12-29 14:41 UTC, danieldaeschle commented on vlib/v/checker/checker.v
> +		return_sym.kind in [.placeholder, .any_int, .any_float] && return_sym.language == .v {
what happened before adding this with placeholder? shouldn't this be handled in parser and result in .placeholder when any_int and any_float is used?

2020-12-29 14:44 UTC, Delta456 commented on vlib/v/checker/checker.v
> +				c.error('unknown type `$sym.name`', field.type_pos)
I didn't do that because the upper one also suggests a name and if a field type has `any_float` then it will give a suggestion to use `any_int` and to avoid that I did it.

2020-12-29 17:04 UTC, spytheman commented on vlib/v/checker/checker.v
> +				c.error('unknown type `$sym.name`', field.type_pos)
I also think that separate checks will be better. The 2 situations have nothing in common.

2020-12-29 17:05 UTC, spytheman commented on vlib/v/checker/checker.v
> +				c.error('unknown type `$sym.name`', field.type_pos)
@Delta456 when you separate them again, please use something like 'can not use `any_int`, please use `int` instead' etc.

2020-12-29 17:11 UTC, Delta456 commented on vlib/v/checker/checker.v
> +				c.error('unknown type `$sym.name`', field.type_pos)
Ok

2020-12-29 23:39 UTC, danieldaeschle commented on vlib/v/checker/checker.v
> +				c.error('unknown type `$sym.name`', field.type_pos)
Why an extra error? any_int or any_float shouldn't be visible to the user.

btw: `cannot`

2020-12-29 23:39 UTC, danieldaeschle approved these changes

2020-12-30 04:06 UTC, Delta456 commented on vlib/v/checker/checker.v
> +				c.error('unknown type `$sym.name`', field.type_pos)
If you see the CI then it fails on `windows-msvc` due to `f32` comparison issue.

I think "unknown type `any_int`. Did you mean int?" and "unknown type `any_float`. Did you mean f64?" will be in a separate condition for making it consistent with the rest. If that's what it needs.

2020-12-30 08:00 UTC, spytheman commented on vlib/v/checker/checker.v
> +				c.error('unknown type `$sym.name`', field.type_pos)
> Why an extra error?

Because the errors are different:
1. these types are not unknown, that is misleading
2. the unknown type situation offers a probabilistic suggestion based on a word similarity metric, because that is the best V can do in that situation. That is not the case for the `any_int` and `any_float` situation.

2020-12-30 09:28 UTC, danieldaeschle commented on vlib/v/checker/checker.v
> +				c.error('unknown type `$sym.name`', field.type_pos)
1. Outside of builtin they should be unknown imo. @medvednikov what do you think?
2. If the compiler suggests int for any_int ut's great, or? I see no flaws with it.

2020-12-30 16:58 UTC, Delta456 commented
Can this be merged?

2020-12-31 11:41 UTC, merged