v.ast: add "walker" submodule for ast walking
vlang/v pull request #7775
Opened 2021-01-01 09:58 UTC by nedpals

This PR is a generalized form of the one implemented on https://github.com/vlang/vls/pull/34 and also as suggested by @spytheman in the Discord server.

The decision to put it on a submodule instead of `v.ast` is to in order to not add additional (yet unnecessary) size to the compiler. The design of the AST walker is inspired from [Go](https://golang.org/src/go/ast/walk.go#L51) albeit with slight differences.
This is still a draft version as I need to gather some feedback, add more tests and documentations, and it also needs an interface fix (<INSERT PR LINK HERE>) in order to be merged.

2021-01-01 11:30 UTC, danieldaeschle commented on vlib/v/ast/ast.v
> +	ScopeObject | SelectBranch | Stmt | StructField | StructInitField | table.Param
add a TODO to change the table.Param thing. For now it seems ok, but in future it should change.

2021-01-01 11:40 UTC, danieldaeschle requested changes

2021-01-01 11:40 UTC, danieldaeschle commented on vlib/v/ast/ast.v
> +						len: pos.len + node.name.len
this is not really safe this way.
it could be that the dev writes this `import          name`

Please add a name_pos to the Module struct. and extend it.

2021-01-01 11:40 UTC, danieldaeschle commented on vlib/v/ast/ast.v
> +						len: pos.len + node.mod.len + node.alias.len + 7
same like the previous one.

2021-01-01 11:40 UTC, danieldaeschle commented on vlib/v/ast/ast.v
> +			// NB: these four decl nodes cannot be merged as one branch
why not?

2021-01-01 11:40 UTC, danieldaeschle commented on vlib/v/ast/walker/walker.v
> +		return &i
don't return reference of reference, that should be forbidden.

2021-01-01 11:40 UTC, danieldaeschle commented on vlib/v/ast/walker/walker.v
> +pub fn inspect(node ast.Node, data voidptr, i_fn fn (node ast.Node, data voidptr) bool) {
create function type alias for readability.

2021-01-01 11:40 UTC, danieldaeschle commented on vlib/v/ast/walker/walker.v
> +	i_fn fn (node ast.Node, data voidptr) bool
what does i_fn mean? is there no better name?

2021-01-01 11:41 UTC, danieldaeschle commented
awesome work

2021-01-01 13:40 UTC, spytheman commented on vlib/v/ast/walker/walker.v
> +	i_fn fn (node ast.Node, data voidptr) bool
`inspector_callback` ?

2021-01-01 14:10 UTC, nedpals commented on vlib/v/ast/ast.v
> +			// NB: these four decl nodes cannot be merged as one branch
The four nodes have different types for the `fields` field. Resulting to this:
```
/home/ned/Downloads/v/vlib/v/ast/ast.v:1364:17: error: field `ast.GlobalDecl.fields` type is different
 1362 |             // NB: these four decl nodes cannot be merged as one branch
 1363 |             StructDecl, GlobalDecl, ConstDecl, EnumDecl {
 1364 |                 return node.fields.map(Node(it))
      |                             ~~~~~~
 1365 |             }
 1366 |             FnDecl {
 ```

2021-01-01 16:22 UTC, danieldaeschle commented on vlib/v/ast/ast.v
> +			// NB: these four decl nodes cannot be merged as one branch
extend the comment

2021-01-01 16:22 UTC, danieldaeschle commented on vlib/v/ast/walker/walker.v
> +	i_fn fn (node ast.Node, data voidptr) bool
or just `callback`?

2021-01-02 01:51 UTC, nedpals commented on vlib/v/ast/walker/walker.v
> +		return &i
I will fix this in the PR #7776 .

2021-01-02 01:53 UTC, nedpals commented on vlib/v/ast/walker/walker.v
> +pub fn inspect(node ast.Node, data voidptr, i_fn fn (node ast.Node, data voidptr) bool) {
fixed

2021-01-02 01:54 UTC, nedpals commented on vlib/v/ast/ast.v
> +						len: pos.len + node.name.len
Yeah this shouldn't be the recommended way to modify positions. I'll add it today :smiley:

2021-01-02 03:53 UTC, nedpals commented on vlib/v/ast/ast.v
> +	ScopeObject | SelectBranch | Stmt | StructField | StructInitField | table.Param
Done

2021-01-03 01:25 UTC, zakuro9715 commented
#7771 and #7773 are now fixed.

2021-01-04 09:59 UTC, danieldaeschle requested changes

2021-01-04 09:59 UTC, danieldaeschle commented on vlib/v/ast/ast.v
> +			return token.Position{}
Maybe position from the first child to the last?

2021-01-04 09:59 UTC, danieldaeschle commented on vlib/v/ast/walker/walker_test.v
> +	walker.inspect(file, 0, fn (node ast.Node, data voidptr) bool {
Where is the assert?

2021-01-04 10:22 UTC, nedpals commented on vlib/v/ast/walker/walker_test.v
> +	walker.inspect(file, 0, fn (node ast.Node, data voidptr) bool {
it's not done yet but nice catch :laughing:

2021-01-05 08:06 UTC, danieldaeschle commented on vlib/v/ast/walker/walker_test.v
> +		// True means that the inspector must now inspect ast.File's children
nice documentation. isn't it better to document in the code instead of the test?

2021-01-05 08:08 UTC, danieldaeschle approved these changes

2021-01-05 08:08 UTC, danieldaeschle commented
still draft?

2021-01-05 08:53 UTC, nedpals commented on vlib/v/ast/walker/walker_test.v
> +		// True means that the inspector must now inspect ast.File's children
That's what I asked on Discord earlier since Go's docs perfectly describes what those functions are. But the thing is, isn't my implementation sort of a port from Go's if I add the comments into it?

Here's the message: https://discord.com/channels/592103645835821068/592320321995014154/795876148768800839

2021-01-05 08:54 UTC, nedpals commented
> still draft?

Yep still working on documentation

2021-01-05 09:03 UTC, danieldaeschle commented on vlib/v/ast/walker/walker_test.v
> +		// True means that the inspector must now inspect ast.File's children
You already copied the code? Is it different when copying the docs too? What about writing your own docs?
I just want to move your current docs to the correct place ;)

2021-01-05 09:05 UTC, danieldaeschle commented on vlib/v/ast/walker/walker_test.v
> +		// True means that the inspector must now inspect ast.File's children
otherwise adding the license header from go should be enough.

2021-01-05 10:24 UTC, nedpals commented on vlib/v/ast/walker/walker_test.v
> +		// True means that the inspector must now inspect ast.File's children
No, I didn't copy the code but only just the function/interface descriptions (with minor modifications ofcourse because of the differences in implementation). I considered writing my own but believe that the result would be more or less like a bad version (bootleg I should say) of the Go one regardless if I had known it or not.

2021-01-05 10:38 UTC, danieldaeschle commented on vlib/v/ast/walker/walker_test.v
> +		// True means that the inspector must now inspect ast.File's children
better a bad version than no docs

2021-01-06 09:10 UTC, nedpals commented on vlib/v/ast/walker/walker_test.v
> +		// True means that the inspector must now inspect ast.File's children
true. ill just settle with putting a simple description for now

2021-01-06 11:29 UTC, danieldaeschle commented on vlib/v/ast/walker/walker.v
> +// Visitor's visit method is invoked by the walker in each node it encounters.
`Visitor contains a visit method that is invoked...`

2021-01-06 14:09 UTC, JalonSolov commented on vlib/v/ast/walker/walker.v
> +// Visitor's visit method that is invoked by the walker in each node it encounters.
The word `that` doesn't make sense here.  The sentence was correct before.

2021-01-06 15:25 UTC, danieldaeschle commented on vlib/v/ast/walker/walker.v
> +// Visitor's visit method that is invoked by the walker in each node it encounters.
`Visitor implements a visit method that is invoked...`

2021-01-06 18:08 UTC, spytheman commented on vlib/v/ast/walker/walker.v
> +// Visitor's visit method that is invoked by the walker in each node it encounters.
I think both can be understood, but Jalon is a native English speaker, so lets go with his variant (the old one).

2021-01-06 18:22 UTC, danieldaeschle commented on vlib/v/ast/walker/walker.v
> +// Visitor's visit method that is invoked by the walker in each node it encounters.
Ah ok. the problem i see is that `Visitor's` is against our guideline, because of the ending `'s`

2021-01-06 18:29 UTC, JalonSolov commented on vlib/v/ast/walker/walker.v
> +// Visitor's visit method that is invoked by the walker in each node it encounters.
If that's the case `Visitor defines a visit method which is invoked by the walker in each node it encounters.`

Visit doesn't implement the method, it just defines the signature.

2021-01-07 01:05 UTC, nedpals commented on vlib/v/ast/walker/walker.v
> +// Visitor's visit method that is invoked by the walker in each node it encounters.
I too have been confused as to what is the guidelines for this. Thanks @JalonSolov

2021-01-08 08:42 UTC, nedpals commented
@spytheman Can we merge this now?

2021-01-08 15:33 UTC, medvednikov commented
Let's merge this right now. Can you fix the conflict please?

2021-01-08 15:35 UTC, danieldaeschle commented
why does fsanitize-address fails?

2021-01-08 15:42 UTC, JalonSolov commented
It says there's a stack buffer overflow.

2021-01-08 21:01 UTC, spytheman commented
Rebased over master, fixed conflict in parser.v

2021-01-09 00:47 UTC, nedpals commented
Fixed the conflicts

2021-01-09 01:46 UTC, medvednikov commented
One error:

```
FAIL  [125/341]  3384.077 ms vlib/v/ast/walker/walker_test.v
=================================================================
==6922==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffe4dba6a20 at pc 0x00000049408a bp 0x7ffe4dba6690 sp 0x7ffe4dba5e58
READ of size 168 at 0x7ffe4dba6a20 thread T0
    #0 0x494089 in __asan_memcpy (/tmp/v/test_session_108841879777/walker_test+0x494089)
    #1 0x67e83f in v__table__Table_find_fn (/tmp/v/test_session_108841879777/walker_test+0x67e83f)
    #2 0x75a9d8 in v__parser__Parser_fn_decl (/tmp/v/test_session_108841879777/walker_test+0x75a9d8)
    #3 0x7b395b in v__parser__Parser_top_stmt (/tmp/v/test_session_108841879777/walker_test+0x7b395b)
    #4 0x79f973 in v__parser__Parser_parse (/tmp/v/test_session_108841879777/walker_test+0x79f973)
    #5 0x7a1b93 in v__parser__parse_text (/tmp/v/test_session_108841879777/walker_test+0x7a1b93)
    #6 0x820089 in main__parse_text (/tmp/v/test_session_108841879777/walker_test+0x820089)
    #7 0x8210a6 in main__test_walk (/tmp/v/test_session_108841879777/walker_test+0x8210a6)
    #8 0x81fa47 in main (/tmp/v/test_session_108841879777/walker_test+0x81fa47)
    #9 0x7f17caf1c0b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16
    #10 0x41c4fd in _start (/tmp/v/test_session_108841879777/walker_test+0x41c4fd)
```

2021-01-09 01:54 UTC, nedpals commented
i'll try to check if https://github.com/vlang/v/pull/7972 solved the problem for this

2021-01-09 04:36 UTC, merged

2021-01-09 07:19 UTC, zakuro9715 commented
@nedpals Good work!

2021-01-09 07:20 UTC, nedpals commented
@zakuro9715 thanks :)