mysql: Add main documentation
vlang/v pull request #7824
Opened 2021-01-02 22:56 UTC by donnisnoni

2021-01-02 22:57 UTC, donnisnoni commented
Request Review @spytheman

2021-01-03 00:30 UTC, esquerbatua commented
For what do you need to install pkg-config? with the dev lib of mysql it's enough

2021-01-03 00:31 UTC, esquerbatua commented on vlib/mysql/README.md
> +
Not needed at all

2021-01-03 00:34 UTC, esquerbatua requested changes

2021-01-03 00:34 UTC, esquerbatua commented on vlib/mysql/README.md
> +```
Not needed at all

2021-01-03 00:50 UTC, donnisnoni commented on vlib/mysql/README.md
> +```
Hmm... I just simplify it

2021-01-03 04:00 UTC, donnisnoni commented on vlib/mysql/README.md
> +Please install [the installer](https://dev.mysql.com/downloads/installer/) , then copy the `include` and `lib` folders to `thirdparty/mysql` on V root folder.
@JalonSolov That is the old version of the file. Please refer to the new one.

2021-01-03 04:02 UTC, donnisnoni commented on vlib/mysql/README.md
> +Below are the things that are needed before using this module:
@JalonSolov That is the old version of the file. Please refer to the new one.

2021-01-03 04:03 UTC, donnisnoni commented on vlib/mysql/README.md
> +For windows users, you can skip it.
https://github.com/vlang/v/pull/7824#discussion_r550952575

2021-01-03 04:05 UTC, JalonSolov commented on vlib/mysql/README.md
> +For Windows, install [the installer](https://dev.mysql.com/downloads/installer/) , then copy the `include` and `lib` folders to `thirdparty/mysql` on V root folder.
"folders to `thirdparty/mysql` on V root folder." -> "folders to the `<V install directory>\thirdparty\mysql` folder.

2021-01-03 20:13 UTC, JalonSolov approved these changes

2021-01-04 16:37 UTC, merged