vdoc: heavy refactor, immutable config
vlang/v pull request #7945
Opened 2021-01-07 15:20 UTC by Larpon

This PR will refactor `vdoc`.

The confusing "global" state `DocConfig` is now separated into `VDoc`, `Config` and `Output` structs.
Before the various fields (especially `output_*`) was mutated by many different methods which made it hard to debug resembling a global state that we are trying to avoid.

I've introduced an immutable config state to avoid unexpected "global" state changes and instead pass around a state only for the output - this help encapsulate what's being mutated and thus avoids confusion.

The most optimal would be to further incapsulate the different output renderers into their own module with their own state to keep things from entangling into the hairball it was before.

The external interface is untouched - so this is purely an internal refactor.

2021-01-07 15:39 UTC, danieldaeschle commented
There is an error with serve_html.

2021-01-07 15:40 UTC, danieldaeschle commented
Could we also remove the internal http server for now? It's not even working correctly...

2021-01-07 15:41 UTC, JalonSolov commented
Separate PR for removing the internal http server.

2021-01-07 15:44 UTC, danieldaeschle requested changes
Awesome work! :)

2021-01-07 15:44 UTC, danieldaeschle commented on cmd/tools/vdoc/utils.v
> +fn js_compress(str string) string {
this is related to html.

2021-01-07 15:44 UTC, danieldaeschle commented on cmd/tools/vdoc/utils.v
> +fn gen_footer_text(d &doc.Doc, include_timestamp bool) string {
this is related to html.

2021-01-07 15:44 UTC, danieldaeschle commented on cmd/tools/vdoc/html.v
> +fn doc_node_html(dd doc.DocNode, link string, head bool, include_examples bool, tb &table.Table) string {
could you replace `dd` with `dn`?

2021-01-07 15:48 UTC, Larpon commented on cmd/tools/vdoc/utils.v
> +fn gen_footer_text(d &doc.Doc, include_timestamp bool) string {
It's also used in `markdown` :)

2021-01-07 15:50 UTC, Larpon commented on cmd/tools/vdoc/utils.v
> +fn js_compress(str string) string {
> Could we also remove the internal http server for now? It's not even working correctly...

Yup will do in separate PR

2021-01-07 15:52 UTC, Larpon commented
The failing tests is because the build-tools test doesn't account for the new vdoc directory

2021-01-07 18:17 UTC, danieldaeschle approved these changes

2021-01-07 23:22 UTC, nedpals approved these changes

2021-01-08 10:00 UTC, spytheman commented
@Larpon I went with a combined approach for vbuild-tools.v, that should support `vdoc` and future tools like it, by adding their folder, after the prepare_test_session call (which only adds .v files).

2021-01-08 10:13 UTC, Larpon commented
Awesome! Thanks for taking your time with this :slightly_smiling_face:

2021-01-08 10:25 UTC, merged