compiler: support `$embed_file()` compile time call
vlang/v pull request #8048
Opened 2021-01-11 20:55 UTC by Larpon

Effort to make the following work:
```v
module main

import os

const (
	const_file = $embed_file('embed1.png')
)

fn main() {
	file := $embed_file('embed2.png')
	println('$const_file')
	println('$file')
	filename := '/tmp/out.png'
	mut fw := os.create(filename) or {
		panic('failed to create file $filename')
	}
	fw.write_bytes(file.data(), file.len)
	fw.close()
}
```

2021-01-11 21:18 UTC, medvednikov commented
@Larpon what a legend!

2021-01-11 23:31 UTC, penguindark commented
Great, it will be very useful :)

2021-01-12 21:35 UTC, zakuro9715 commented
Awesome! I wanted this.

2021-01-13 01:06 UTC, StunxFS commented
Amazing work! It arrives just when I need it, thanks :)

2021-01-13 15:14 UTC, JalonSolov requested changes

2021-01-13 15:14 UTC, JalonSolov commented on vlib/embed/embed.v
> +// EmbeddedData incapsulates functionality for the `$embed_file()` compile time call.
Minor - `encapsulates`.  `incapsulates` is not a valid English word.

2021-01-13 15:14 UTC, JalonSolov commented on vlib/v/checker/checker.v
> +					c.error('please supply a valid relative or absolute file path to the embedded file',
`to the file to embed`

The phrase `to the embedded file` implies it has already been embedded.

2021-01-13 15:14 UTC, JalonSolov commented on vlib/v/checker/checker.v
> +						c.error('embedded file "$path" is not a file', node.left.position())
perhaps something like
`"$path" cannot be embedded - not a file`

The phrase `embedded file` implies it has already been embedded.

2021-01-13 15:14 UTC, JalonSolov commented on vlib/v/checker/checker.v
> +							c.error('embedded file "$path" is not a file', node.left.position())
`embedded file` again.  See previous comment... this needs to be changed everywhere.

2021-01-13 16:11 UTC, spytheman commented on vlib/v/parser/comptime.v
> +	supported_calls := ['html', 'tmpl', 'embed_file']
that can be extracted to a const

2021-01-13 16:12 UTC, spytheman commented on vlib/v/parser/comptime.v
> +	supported_calls := ['html', 'tmpl', 'embed_file']
comp_call is called potentially many times

2021-01-13 16:13 UTC, spytheman approved these changes
Good work!

2021-01-13 16:26 UTC, Larpon commented on vlib/v/parser/comptime.v
> +	supported_calls := ['html', 'tmpl', 'embed_file']
Ah yes, ofc :slightly_smiling_face:

2021-01-13 16:58 UTC, Larpon commented
Sorry for the test mess. Something odd is up :thinking:

2021-01-13 19:33 UTC, spytheman commented
Sorry for the delay. I will have a look at the test now.

2021-01-13 20:28 UTC, Larpon commented
> Sorry for the delay. I will have a look at the test now.

Sorry right now the paths in the test files are hardcoded to check if it was the relative paths giving us trouble - which it seems it is indeed. They should be just 'v.png' (and that file is 603 in .len)

2021-01-13 21:55 UTC, Larpon commented
https://github.com/vlang/v/pull/8048/checks?check_run_id=1698131808#step:11:10
This is what's baffling me. Makes no sense and I can't reproduce it locally

2021-01-14 14:20 UTC, merged

2021-01-14 15:17 UTC, Larpon commented
:partying_face: