checker: smartcast for && cond, `expr && x is Type`
vlang/v pull request #8151
Opened 2021-01-16 13:50 UTC by zakuro9715

Before
```v
if expr && x is Type {
  t := x as Type
  println(typeof(t).name)) // Type
}
```
After

```v
if expr && x is Type {
  println(typeof(x).name)) // Type
}
```

2021-01-16 14:11 UTC, danieldaeschle commented
what happens in case of `if expr && x is Type && x is Type2 {`?

2021-01-16 14:15 UTC, danieldaeschle requested changes

2021-01-16 14:15 UTC, danieldaeschle commented on vlib/v/tests/if_smartcast_test.v
> +	if x is Abc && y is Xyz {
what happens with `if x is Type && x is Type2 {`? please add a test.

2021-01-16 14:15 UTC, danieldaeschle commented on vlib/v/parser/sql.v
> +				if e.left is ast.Ident {
will you change it back in the next PR?

2021-01-16 21:25 UTC, zakuro9715 commented on vlib/v/parser/sql.v
> +				if e.left is ast.Ident {
yeah. For now, this is needed to avoid failing v self

2021-01-16 23:10 UTC, danieldaeschle requested changes

2021-01-16 23:10 UTC, danieldaeschle commented on vlib/v/tests/if_smartcast_test.v
> +		assert x.name == ''
Does this compile? I think it shouldn‘t.

2021-01-16 23:10 UTC, danieldaeschle commented on vlib/v/tests/if_smartcast_test.v
> +	if x is Abc && x is Xyz {
Looks duplicated to line  53 :o

2021-01-16 23:10 UTC, danieldaeschle commented on vlib/v/tests/if_smartcast_test.v
> +		assert x.name == ''
Is an aggregate created?

2021-01-17 08:03 UTC, zakuro9715 commented on vlib/v/tests/if_smartcast_test.v
> +		assert x.name == ''
for now, x will be Xyz (most right of cond).

I think this should be intersection type. But I don't know how to implement this.

2021-01-17 08:05 UTC, zakuro9715 commented on vlib/v/tests/if_smartcast_test.v
> +	if x is Abc && x is Xyz {
line 53 is two variable. This is one variable, two casts

2021-01-17 09:21 UTC, SleepyRoy commented
@zakuro9715 one CI check failed. Could your fix it?

2021-01-17 09:28 UTC, zakuro9715 commented
@SleepyRoy This PR includes braking changes. And current vls code will not be able to compile by this PR. To compile vls, small fix is required.

2021-01-17 09:37 UTC, spaceface777 commented on vlib/v/tests/if_smartcast_test.v
> +		assert x.name == ''
I don't think this should compile, one variable can't have two distinct types. 

Same idea as `if x == 1 && x == 2 { ... }`, that block is unreachable.

2021-01-17 09:38 UTC, SleepyRoy commented
@zakuro9715 I looked at CI running results. Here's the error message about vls.
```V
vls/features.v:246:24: error: cannot cast non-sum type `v.ast.Ident` using `as`
  244 |             // symbols of that module.
  245 |             if expr.expr_type == 0 && expr.expr is ast.Ident {
  246 |                 ident := expr.expr as ast.Ident
      |                                    ~~
  247 |                 if ident.name !in cfg.modules_aliases {
  248 |                     return completion_items
```
I guess with your PR `as ast.Ident` in line 246 is no longer needed. Probably you could try just deleting that?
However that's strange, because smartcast should only work for simple variables(?)

2021-01-17 09:46 UTC, zakuro9715 commented
@SleepyRoy To pass CI, changing vlang/vls code is required. It can't be fixed in this PR.

This PR make smartcast works for `&&` expr

Before this PR, expr.expr is not smartcasted in `if expr.expr_type == 0 && expr.expr is ast.Ident` .
But by this PR, expr.expr is smartcasted to `ast.Ident`

2021-01-17 09:53 UTC, zakuro9715 commented on vlib/v/tests/if_smartcast_test.v
> +		assert x.name == ''
That's right. Practically, this is unreachable code and it should be checker error.

I want  to merge this PR for now. Then make both of `x == 1 && x == 2` and `x is Abc && x is Xyz` checker error in future PR

2021-01-17 09:59 UTC, SleepyRoy commented
@zakuro9715 Yes I got your idea.

2021-01-17 11:58 UTC, danieldaeschle commented on vlib/v/tests/if_smartcast_test.v
> +		assert x.name == ''
just don't smartcast in this case. It's implemented in this PR, can't you remove it again for such cases? There is a reason why i didn't implement such complicated things yet. I wasn't even sure if we should do this.

2021-01-17 11:59 UTC, danieldaeschle commented
I'm still not statisfied how it works, sorry. We need to think about it if we allow it. Otherwise it will get too complex and bring edge cases which are not working.

2021-01-20 04:11 UTC, zakuro9715 commented
Certainly this is complex and some problems exists. I've been thinking about this for a few days. But I could not find a good solution
I close this for now. If i find a good solution, I will submit PR

2021-01-20 04:11 UTC, closed without merging