checker: Remove vweb unused vars
vlang/v pull request #8180
Opened 2021-01-18 10:54 UTC by LouisSchmieder

This PR handle vweb variables and don't mark them as unused

2021-01-18 12:34 UTC, danieldaeschle requested changes

2021-01-18 12:34 UTC, danieldaeschle commented on vlib/v/checker/checker.v
> +			match v {
use `if`

2021-01-18 12:34 UTC, danieldaeschle commented on vlib/v/checker/checker.v
> +			c.vweb_types[k] = var.typ
why using var types and not var names?

2021-01-18 12:34 UTC, danieldaeschle commented on vlib/v/checker/checker.v
> +			if i < 5 {
what's wrong with the first 4?

2021-01-18 12:39 UTC, LouisSchmieder commented on vlib/v/checker/checker.v
> +			if i < 5 {
they are template variables which aren't declared in the function just in the file see https://github.com/vlang/v/blob/master/vlib/vweb/tmpl/tmpl.v

2021-01-18 12:40 UTC, LouisSchmieder commented on vlib/v/checker/checker.v
> +			if i < 5 {
and now I added the app var too

2021-01-18 12:40 UTC, danieldaeschle requested changes

2021-01-18 12:40 UTC, danieldaeschle commented on vlib/v/checker/checker.v
> +	vweb_types                       []string
rename it to `vweb_var_names`

2021-01-18 12:40 UTC, danieldaeschle commented on vlib/v/checker/tests/vweb_tmpl_used_var.vv
> +    return $vweb.html()
please check the indent.

2021-01-18 12:40 UTC, danieldaeschle commented on vlib/v/checker/tests/vweb_tmpl_used_var.vv
> +	port := 8181
you can inline this one.

2021-01-18 12:44 UTC, danieldaeschle requested changes

2021-01-18 12:44 UTC, danieldaeschle commented on vlib/v/checker/checker.v
> +			if i < 4 {
why skip the first 3? 🤔

2021-01-18 12:45 UTC, LouisSchmieder commented on vlib/v/checker/checker.v
> +			if i < 4 {
they are template variables which aren't declared in the function just in the file see https://github.com/vlang/v/blob/master/vlib/vweb/tmpl/tmpl.v

2021-01-18 12:54 UTC, danieldaeschle commented on vlib/v/checker/checker.v
> +			if i < 4 {
comment it please

2021-01-18 12:55 UTC, LouisSchmieder commented on vlib/v/checker/checker.v
> +			if i < 4 {
https://github.com/vlang/v/blob/ac2c3847afc0f7a9a0d3b99064188124df6a6fb5/vlib/vweb/tmpl/tmpl.v#L55
https://github.com/vlang/v/blob/ac2c3847afc0f7a9a0d3b99064188124df6a6fb5/vlib/vweb/tmpl/tmpl.v#L57

2021-01-18 12:55 UTC, LouisSchmieder commented on vlib/v/checker/checker.v
> +			if i < 4 {
https://github.com/vlang/v/blob/ac2c3847afc0f7a9a0d3b99064188124df6a6fb5/vlib/vweb/tmpl/tmpl.v#L146

2021-01-18 12:56 UTC, LouisSchmieder commented on vlib/v/checker/checker.v
> +			if i < 4 {
and those are written in the String builder where the string get compiled afterwards

2021-01-18 15:27 UTC, danieldaeschle requested changes

2021-01-18 15:27 UTC, danieldaeschle commented on vlib/v/checker/checker.v
> +				// Skip first three because their are tmpl vars see https://github.com/vlang/v/blob/master/vlib/vweb/tmpl/tmpl.v
change link to only `vlib/vweb/tmpl/tmpl.v`

2021-01-18 21:20 UTC, medvednikov commented on vlib/v/checker/checker.v
> +		mut i := 0
Can you add a comment here to explain what this code does

2021-01-18 21:20 UTC, medvednikov commented on vlib/v/checker/checker.v
> +				// Skip first three because their are tmpl vars see vlib/vweb/tmpl/tmpl.v
they are

2021-01-18 21:24 UTC, LouisSchmieder commented
will continue with this tomorrow

2021-01-19 11:35 UTC, danieldaeschle requested changes

2021-01-19 11:35 UTC, danieldaeschle commented on vlib/v/parser/comptime.v
> +	eprintln(path)
remove

2021-01-19 11:46 UTC, LouisSchmieder commented on vlib/v/parser/comptime.v
> +	eprintln(path)
just temporary there because I try with delta to fix the problems

2021-01-20 11:12 UTC, danieldaeschle approved these changes

2021-01-20 11:15 UTC, danieldaeschle approved these changes

2021-01-20 11:24 UTC, LouisSchmieder commented
close #8141

2021-01-20 21:24 UTC, spytheman commented on cmd/tools/vtest-self.v
> +		'vlib/v/checker/tests/vweb_tmpl_used_var.vv'
.vv files are skipped automatically by `v test-self`, why is it added here?

These skip lists should contain only `_test.v` files.

2021-01-20 21:58 UTC, LouisSchmieder commented on cmd/tools/vtest-self.v
> +		'vlib/v/checker/tests/vweb_tmpl_used_var.vv'
Oh it's still there sry

2021-01-21 08:31 UTC, danieldaeschle approved these changes

2021-01-21 10:09 UTC, merged