fix orm fox empty struct
vlang/v pull request #8246
Opened 2021-01-21 12:33 UTC by LouisSchmieder

close #5553
This PR add handling for orm when struct that get parse into are empty

2021-01-21 12:35 UTC, Delta456 commented
Can a test be added for this?

2021-01-21 12:41 UTC, danieldaeschle requested changes

2021-01-21 12:41 UTC, danieldaeschle commented on vlib/v/checker/tests/orm_empty_struct.vv
> +    println(res)
remove this.

2021-01-21 12:45 UTC, danieldaeschle approved these changes

2021-01-22 13:05 UTC, danieldaeschle commented
@spytheman can you merge this?

2021-01-22 13:34 UTC, medvednikov commented on vlib/v/ast/ast.v
> +	table_pos   token.Position
this should be named `orm_table_pos`

but I don't think it's necessary at all

2021-01-22 20:42 UTC, danieldaeschle commented on vlib/v/ast/ast.v
> +	table_pos   token.Position
i think it's fine:
1. it's called table_name and table_type, not orm_table_type.
2. having table_pos leads to better error messages. pos doesn't contain the position of the declared struct.

2021-01-22 21:52 UTC, danieldaeschle approved these changes

2021-01-22 22:28 UTC, merged