crypto: add missing documentation to all pub functions
vlang/v pull request #8251
Opened 2021-01-21 13:16 UTC by Larpon

This documents all `pub` functions in the `crypto` module.
When merged, the following boxes in #7047 should be checked off:
 - [x] `vlib/crypto/aes/aes.v`
 - [x] `vlib/crypto/aes/aes_cbc.v`
 - [x] `vlib/crypto/md5/md5.v`
 - [x] `vlib/crypto/rand/rand_linux.c.v`
 - [x] `vlib/crypto/rand/rand_solaris.c.v`
 - [x] `vlib/crypto/rand/utils.v`
 - [x] `vlib/crypto/sha1/sha1.v`
 - [x] `vlib/crypto/sha256/sha256.v`
 - [x] `vlib/crypto/sha512/sha512.v`
 
Please note that I've made the `write` and `sum` functions of the following files private:
 * `crypto/md5/md5.v`
 * `crypto/sha1/sha1.v`

These looked like typos or copy-paste accidents as they touch internal state.

2021-01-21 20:35 UTC, spytheman commented
I think the `pub` changes should be in a separate PR.

2021-01-21 20:51 UTC, Larpon commented
> I think the `pub` changes should be in a separate PR.

Right I just tend to forget such small things easily between sessions 🙂

I'll split them out later 👍

2021-01-21 21:44 UTC, danieldaeschle requested changes

2021-01-21 22:01 UTC, Larpon commented on vlib/crypto/aes/aes.v
> +// block_size returns the block size of the checksum in bytes.
It's the amount of bytes a block takes up, yes. Wording is hard 😅

2021-01-21 22:02 UTC, Larpon commented on vlib/crypto/aes/aes_cbc.v
>  pub fn (mut x AesCbc) decrypt_blocks(mut dst []byte, src []byte) {
No idea, could be an old workaround or similar 🤷‍♂️

2021-01-21 22:41 UTC, JalonSolov commented on vlib/crypto/aes/aes.v
> +// block_size returns the block size of the checksum in bytes.
`// block_size returns the number of bytes in the checksum block.`

2021-01-21 22:41 UTC, JalonSolov commented on vlib/crypto/aes/aes_cbc.v
> +// block_size returns the block size of the checksum in bytes.
Same comment change.  :-)

2021-01-21 22:43 UTC, JalonSolov commented on vlib/crypto/aes/aes_cbc.v
>  pub fn (mut x AesCbc) decrypt_blocks(mut dst []byte, src []byte) {
Slow to allocate a new block and return it, rather than just using a block already allocated by the caller... which may be part of a larger block of memory, etc.

2021-01-22 07:28 UTC, spytheman commented on vlib/crypto/aes/aes.v
> +// block_size returns the block size of the checksum in bytes.
I think @Larpon's variant is best.

2021-01-22 07:28 UTC, spytheman commented on vlib/crypto/aes/aes_cbc.v
> +// block_size returns the block size of the checksum in bytes.
The comment is clear imho.

2021-01-22 07:29 UTC, spytheman commented on vlib/crypto/aes/aes_cbc.v
>  pub fn (mut x AesCbc) decrypt_blocks(mut dst []byte, src []byte) {
For performance, yes.

2021-01-22 08:33 UTC, danieldaeschle commented on vlib/crypto/aes/aes_cbc.v
>  pub fn (mut x AesCbc) decrypt_blocks(mut dst []byte, src []byte) {
Maybe document this?

2021-01-22 09:59 UTC, Larpon commented on vlib/crypto/aes/aes_cbc.v
> +// block_size returns the block size of the checksum in bytes.
lol

2021-01-22 10:23 UTC, Larpon commented on vlib/crypto/aes/aes_cbc.v
>  pub fn (x &AesCbc) encrypt_blocks(mut dst_ []byte, src_ []byte) {
I'll do this in another PR

2021-01-22 10:23 UTC, Larpon commented on vlib/crypto/aes/aes_cbc.v
>  pub fn (mut x AesCbc) decrypt_blocks(mut dst []byte, src []byte) {
I've added a doc note

2021-01-22 10:25 UTC, Larpon commented on vlib/crypto/md5/md5.v
> +// sum returns a copy of the generated sum of the bytes in `b_in`.
Changed in f106652

2021-01-22 10:28 UTC, spytheman commented on vlib/crypto/aes/aes.v
> +// Please note: `dst` and `src` is both mutable for performance reasons.
`are both`

2021-01-22 10:43 UTC, Larpon commented on vlib/crypto/aes/aes.v
> +// Please note: `dst` and `src` is both mutable for performance reasons.
Fixed in 44770fb

2021-01-22 15:32 UTC, Larpon commented
Ready for merge

2021-01-23 12:33 UTC, merged