all: implement interface fields
vlang/v pull request #8259
Opened 2021-01-21 17:36 UTC by spaceface777

WIP because cgen does not work yet- I'm still not sure what the best way of implementing this is. Ideas are welcome :)

2021-01-21 19:51 UTC, spytheman commented
Please run vfmt on vlib/v/checker and vlib/v/gen .

2021-01-22 13:03 UTC, danieldaeschle commented on CHANGELOG.md
> +- Allow interfaces to include fields, not just methods.
`Interfaces are able to define fields.`

2021-01-22 13:03 UTC, danieldaeschle commented on CHANGELOG.md
> +- Allow interfaces to include fields, not just methods.
Btw.: merge master into this branch and move it to `0.2.3`

2021-01-22 13:28 UTC, danieldaeschle commented on vlib/v/checker/checker.v
> +	// TODO: copy pasta from StructDecl
._.

2021-01-22 13:30 UTC, danieldaeschle requested changes

2021-01-22 13:30 UTC, danieldaeschle commented on vlib/v/gen/cgen.v
> +					g.type_definitions.writeln('\t$styp $cname;')
why generating fields extra? you have the `_object` to access fields.

2021-01-22 13:37 UTC, spaceface777 commented on vlib/v/gen/cgen.v
> +					g.type_definitions.writeln('\t$styp $cname;')
because we do not know what type `_object` will be at runtime, and field offsets between different structs implementing an interface may be different. While the offset could be calculated at runtime, with this approach, it is only calculated once when creating the interface, not every time a field is accessed, which is better for performance. It also means that accessing fields is much simpler in the codegen (`interface->field` rather than a getter function, or whatever).

I discussed this in #v-development and with @spytheman, and we decided that if memory usage was too high we would consider alternative approaches later on, but that this way was better for an initial version.

2021-01-22 13:39 UTC, danieldaeschle commented on vlib/v/gen/cgen.v
> +					g.type_definitions.writeln('\t$styp $cname;')
ok, thanks :)

2021-01-22 18:52 UTC, danieldaeschle requested changes

2021-01-22 18:52 UTC, danieldaeschle commented on vlib/v/tests/interface_fields_test.v
> +	assert c.breed == 'what??'
Nice!  Ould you move it to its own test? (One scenario per test case)

2021-01-22 19:07 UTC, spaceface777 commented on vlib/v/tests/interface_fields_test.v
> +	assert a.breed in ['Persian', 'Labrador']
both of those were already on there :D

2021-01-22 22:29 UTC, medvednikov commented on vlib/v/checker/checker.v
> +	// TODO: copy pasta from StructDecl
yeah not nice

2021-01-22 22:38 UTC, spaceface777 commented on vlib/v/checker/checker.v
> +	// TODO: copy pasta from StructDecl
I know (that's why I added the comment), but they're different ast nodes with different fields, and with some different checks, so it's not as simple as just extracting that to a new function.

I feel like this can be cleaned up later.

2021-01-22 22:47 UTC, danieldaeschle commented on vlib/v/checker/checker.v
> +	// TODO: copy pasta from StructDecl
how difficult is it to do it directly?

2021-01-22 22:47 UTC, danieldaeschle commented on vlib/v/checker/checker.v
> +					// TODO: mutability checks on interface fields?
yes please!

2021-01-22 22:47 UTC, danieldaeschle commented on vlib/v/checker/checker.v
> +					// TODO: mutability checks on interface fields?
do we have a test for this scenario?

2021-01-22 22:53 UTC, danieldaeschle requested changes

2021-01-22 22:53 UTC, danieldaeschle commented on vlib/v/fmt/fmt.v
> +		// TODO: alignment, comments, etc.
please add tests for vfmt as well!

2021-01-22 22:53 UTC, danieldaeschle commented on vlib/v/fmt/fmt.v
> +		if !ft.contains('C.') && !ft.contains('JS.') && !ft.contains('fn (') {
this looks hacky :D
is there no other way?

2021-01-22 22:53 UTC, danieldaeschle commented on vlib/v/parser/struct.v
> +			ts = p.table.get_type_symbol(typ) // removing causes memory bug visible by `v -silent test-fmt`
only in tcc?

2021-01-22 22:53 UTC, danieldaeschle commented on vlib/v/table/types.v
> +pub fn (t &TypeSymbol) find_field(name string) ?Field {
good job! :)

2021-01-22 22:53 UTC, danieldaeschle commented on vlib/v/tests/interface_fields_test.v
> +	mutate_interface(mut c)
you moved out the mutate stuff to `mutate_interface`. what i meant was moving mutating asserts also into it's own `test_` function. It's cleaner to have only one scenario per `test_`/test function.

2021-01-22 22:53 UTC, danieldaeschle commented on vlib/v/tests/interface_fields_test.v
> +	mutate_interface(mut c)
e.g. `test_interface_field_mutation()`
`test_interface_field_access()`

2021-01-22 23:00 UTC, spaceface777 commented on vlib/v/checker/checker.v
> +	// TODO: copy pasta from StructDecl
Not too bad I guess, but I wanted to get the implementation of before cleaning it up.

2021-01-22 23:01 UTC, spaceface777 commented on vlib/v/checker/checker.v
> +					// TODO: mutability checks on interface fields?
Well, interface fields are always pub mut currently

2021-01-22 23:02 UTC, spaceface777 commented on vlib/v/checker/checker.v
> +					// TODO: mutability checks on interface fields?
Interface methods have too, until very recently afaik, so again, I'd do this in a different PR.

2021-01-22 23:03 UTC, spaceface777 commented on vlib/v/parser/struct.v
> +			ts = p.table.get_type_symbol(typ) // removing causes memory bug visible by `v -silent test-fmt`
That was there already, it's not mine.

2021-01-22 23:04 UTC, spaceface777 commented on vlib/v/fmt/fmt.v
> +		if !ft.contains('C.') && !ft.contains('JS.') && !ft.contains('fn (') {
Again, that's how StructDecl does it, I adapted it from there.

2021-01-22 23:10 UTC, danieldaeschle commented on vlib/v/parser/struct.v
> +			ts = p.table.get_type_symbol(typ) // removing causes memory bug visible by `v -silent test-fmt`
ah ok, could you double check it?

2021-01-22 23:18 UTC, spaceface777 commented on vlib/v/tests/interface_fields_test.v
> +	mutate_interface(mut c)
Can you push that / any new tests you'd like to include straight to my branch? I feel like that'd make things easier.

2021-01-22 23:19 UTC, spaceface777 commented on vlib/v/fmt/fmt.v
> +		// TODO: alignment, comments, etc.
Well, alignment / comments / etc. don't work yet, this was just the bare minimum for CI to pass.

2021-01-22 23:20 UTC, spaceface777 commented on vlib/v/fmt/fmt.v
> +		// TODO: alignment, comments, etc.
This isn't a vfmt PR, I think this should all be done in a different one.

2021-01-23 00:14 UTC, elimisteve commented on vlib/v/tests/interface_fields_test.v
> +}
@spaceface777 Great work! :tada: I've missed having this feature in Go for 10 years... but now it's (about to be) in V! https://github.com/vlang/v/issues/3868

2021-01-23 06:28 UTC, spytheman commented on vlib/v/gen/cgen.v
> -		cast_functions.write('// Casting functions for interface "$interface_name"')
This should stay here, putting it in the loop produces:
```c
// Casting functions for interface "main__Animal"
static inline main__Animal I_main__Cat_to_Interface_main__Animal(main__Cat* x) {
static main__Animal* I_main__Cat_to_Interface_main__Animal_ptr(main__Cat* x) {
// Casting functions for interface "main__Animal"
static inline main__Animal I_main__Dog_to_Interface_main__Animal(main__Dog* x) {
static main__Animal* I_main__Dog_to_Interface_main__Animal_ptr(main__Dog* x) {
```

If it is in the loop, it may be made more specific, like:
```c
// Casting functions for converting "main__Cat" to interface "main__Animal" .
```

2021-01-23 06:38 UTC, spytheman commented on vlib/v/gen/cgen.v
> +		if ityp.methods.len > 0 {
Good catch.

2021-01-23 06:38 UTC, spaceface777 commented on vlib/v/gen/cgen.v
> -		cast_functions.write('// Casting functions for interface "$interface_name"')
Ah yes, thanks - I'm not actually sure why I moved it :thinking:

2021-01-23 06:39 UTC, spaceface777 commented on vlib/v/gen/cgen.v
> -		cast_functions.write('// Casting functions for interface "$interface_name"')
Should I move it back out, or make the change you proposed?

2021-01-23 06:40 UTC, spytheman commented on vlib/v/parser/struct.v
> +			ts = p.table.get_type_symbol(typ) // removing causes memory bug visible by `v -silent test-fmt`
That is out of scope for this PR.

2021-01-23 06:44 UTC, spaceface777 commented on vlib/v/gen/cgen.v
> +		if ityp.methods.len > 0 {
msvc doesn't like empty structs/arrays :)

2021-01-23 06:47 UTC, spaceface777 commented on vlib/v/gen/cgen.v
> +		if ityp.methods.len > 0 {
This entire function is a huge mess and needs to be cleaned later- the method table shouldn't even be generated if there are no methods for better compile times

2021-01-23 06:53 UTC, spytheman commented on vlib/v/gen/cgen.v
> -		cast_functions.write('// Casting functions for interface "$interface_name"')
I've fixed it.

2021-01-23 06:54 UTC, spytheman commented on vlib/v/gen/cgen.v
> +		if ityp.methods.len > 0 {
yes, it needs cleanup, but it is out of scope for this PR

2021-01-23 06:56 UTC, spaceface777 commented on vlib/v/gen/cgen.v
> +		if ityp.methods.len > 0 {
Indeed- I'm seeing a trend here :p

2021-01-23 06:57 UTC, spytheman commented
Very good work @spaceface777 !

2021-01-23 06:57 UTC, merged

2021-01-23 07:00 UTC, spaceface777 commented
Thank you (and @shadowninja55) for helping :)

2021-01-23 07:14 UTC, donnisnoni commented
Great work @spaceface777 !!