checker: improve errors with compile-time field access
vlang/v pull request #8373
Opened 2021-01-27 14:49 UTC by ntrel

instead of an error saying we can only use it when iterating T.fields:
* Add 'unknown `$for` variable' error
* Add 'unsupported expression' error (in future it could be supported)

Also do not allow compile-time field access: 
* outside `$for` block 
* after `$if` test inside `$for` block (currently `$if` is required - #8369).

2021-01-27 17:06 UTC, danieldaeschle requested changes

2021-01-27 17:06 UTC, danieldaeschle commented on vlib/v/checker/tests/comptime_field_selector_not_name_err.out
> +   12 |             _ = t.$fv.name
underline is wrong.

2021-01-27 17:06 UTC, danieldaeschle commented on vlib/v/checker/tests/comptime_field_selector_not_name_err.out
> +      |              ~~~~
maybe `f` should be underlined?

2021-01-28 17:08 UTC, ntrel commented
@danieldaeschle I fixed the error positions, and reordered the error messages.

2021-01-28 23:45 UTC, merged