all: support map[f32]string and map[f64]string (float map keys) too
vlang/v pull request #8556
Opened 2021-02-04 19:17 UTC by spytheman

With this PR:
```v
m64 := { 3.14: 'pi' }
println(m64)
```
works.

2021-02-04 19:22 UTC, shadowninja55 commented
perhaps change the message of line 83 of `parse_type.v`? `p.error_with_pos('maps only support string, integer, rune or voidptr keys for now (not `$s`)',`

2021-02-04 19:31 UTC, ntrel requested changes

2021-02-04 19:31 UTC, ntrel commented on vlib/v/gen/c/cgen.v
>  			key_eq_fn = '&map_eq_int_4'
Floats were deliberately left out (for the non-string keys work) because they can have different bit patterns which still compare as equal with ==. So it should use a different equality function. Maybe the hash function is ok though.

2021-02-04 19:32 UTC, spytheman commented on vlib/v/gen/c/cgen.v
>  			key_eq_fn = '&map_eq_int_4'
Because of the +-0 and the nans?

2021-02-04 19:33 UTC, spytheman commented on vlib/v/gen/c/cgen.v
>  			key_eq_fn = '&map_eq_int_4'
I'll add custom hash functions, I have not thought about them, thanks.

2021-02-04 19:42 UTC, ka-weihe commented on vlib/v/gen/c/cgen.v
>  			key_eq_fn = '&map_eq_int_4'
I think this should work fine? However, it is a bit weird to use floats as keys in a map.

2021-02-04 19:44 UTC, spytheman commented on vlib/v/gen/c/cgen.v
>  			key_eq_fn = '&map_eq_int_4'
I intend to port this: https://hg.python.org/cpython/file/1eee26b74e4b/Python/pyhash.c#l86

2021-02-04 19:46 UTC, spytheman commented on vlib/v/gen/c/cgen.v
>  			key_eq_fn = '&map_eq_int_4'
@ka-weihe it was weird to me too (I've never used floats for keys in a hash map before), but it was asked for by @shadowninja55 in the discord channel, it was easy to do, and is consistent with the rest of the language, so I think it will be a good addition.

2021-02-04 19:50 UTC, shadowninja55 commented on vlib/v/gen/c/cgen.v
>  			key_eq_fn = '&map_eq_int_4'
yeah honestly i probably wouldn't use it much either, but it's always good to support everything we can.

2021-02-04 20:04 UTC, ka-weihe approved these changes

2021-02-04 20:20 UTC, ntrel commented on vlib/v/gen/c/cgen.v
>  			key_eq_fn = '&map_eq_int_4'
If Kaspar thinks it's fine, I expect it is.

2021-02-04 20:33 UTC, ka-weihe commented on vlib/v/gen/c/cgen.v
>  			key_eq_fn = '&map_eq_int_4'
Well, it is probably not going to behave like some people expect it to... Only floats with matching bits will match.

2021-02-04 20:58 UTC, medvednikov commented
Honestly, using floats as map keys just sounds wrong.

Floats are notoriously hard to compare, and what's the use case? I'd be in favor of not allowing float keys.

2021-02-04 22:01 UTC, Larpon commented
I use them for caching common pre-calculated values on a timeline in my current game. Float keys have their usage in the real world - although it's surely less common as mentioned. They can be good for caching certain value ranges or lookups where you know how to cut the decimals cutting overhead for string conversions.

2021-02-04 22:59 UTC, merged

2021-02-04 22:59 UTC, medvednikov commented
ok, sounds useful

2021-02-06 12:43 UTC, dumblob commented
Yes, having float keys in maps **is** useful. Thanks for supporting this!

**But** unfortunately currently float comparisons are [**undefined** in *V*](https://github.com/vlang/v/issues/5180#issuecomment-675732199 ) and from there follows, that **withdrawal** of values from such a map is also **undefined**.

It's maybe time to finally tackle this...