all: allow using alias as keys in map (only number, rune, pointers types for now)
vlang/v pull request #8589
Opened 2021-02-05 16:10 UTC by Delta456

Fixes https://github.com/vlang/v/issues/8261

2021-02-05 16:17 UTC, Delta456 commented
The CI Error is not related to my PR.

2021-02-05 16:35 UTC, ntrel requested changes

2021-02-05 16:35 UTC, ntrel commented on vlib/v/parser/parse_type.v
> +	is_alias := p.table.get_final_type_symbol(key_type).is_primitive()
I don't think this is a correct way to detect an alias. And below we should still check it's an alias of a supported type, not just an alias of a primitive type. Last time I checked, we only supported voidptr, not the other C pointer types that is_primitive returns true for.

2021-02-05 17:09 UTC, Delta456 commented on vlib/v/parser/parse_type.v
> +	is_alias := p.table.get_final_type_symbol(key_type).is_primitive()
The check is now `is_alias := p.table.get_type_symbol(key_type).kind == .alias` as said.

2021-02-06 13:25 UTC, ntrel commented on vlib/v/parser/parse_type.v
> +		|| ((key_type.is_int() || key_type.is_float() || is_alias)&& !key_type.is_ptr())) {
This doesn't check that the underlying alias type is a supported key type.

2021-02-07 12:23 UTC, Delta456 commented on vlib/v/parser/parse_type.v
> +		|| ((key_type.is_int() || key_type.is_float() || is_alias)&& !key_type.is_ptr())) {
Done

2021-02-07 12:25 UTC, ka-weihe approved these changes

2021-02-07 22:10 UTC, medvednikov commented
Conflicting files
vlib/v/parser/parse_type.v

2021-02-08 06:01 UTC, Delta456 commented on vlib/v/parser/parse_type.v
> +		|| ((key_type.is_int() || key_type.is_float() || is_alias) && !key_type.is_ptr())) {
This should be valid format instead of  `((key_type.is_int() || key_type.is_float() || is_alias)&& !key_type.is_ptr()))`. CC @serkonda7

2021-02-08 09:02 UTC, serkonda7 commented on vlib/v/parser/parse_type.v
> +		|| ((key_type.is_int() || key_type.is_float() || is_alias) && !key_type.is_ptr())) {
There is a space missing before `&&`

2021-02-08 09:09 UTC, Delta456 commented on vlib/v/parser/parse_type.v
> +		|| ((key_type.is_int() || key_type.is_float() || is_alias) && !key_type.is_ptr())) {
I was talking about the space after `)` which wasn't formatted like that but it works now 🤔

2021-02-08 17:51 UTC, merged