fmt: keep one empty line in struct decl
vlang/v pull request #8782
Opened 2021-02-16 13:10 UTC by zakuro9715

2021-02-16 20:27 UTC, serkonda7 requested changes

2021-02-16 20:27 UTC, serkonda7 commented on test.sh
> +#!/bin/sh
I think you forgot to remove this file

2021-02-16 22:41 UTC, zakuro9715 commented on test.sh
> +#!/bin/sh
Oops. ty :)

2021-02-17 04:45 UTC, medvednikov commented
Not a fan of newlines, but I'm in the minority :)

2021-02-17 04:45 UTC, merged