vfmt: keep `mut:` in interface declarations
vlang/v pull request #9053
Opened 2021-03-02 08:05 UTC by spytheman

Fixes vfmt eating `mut:` from:
```v
interface Toto {
   a int
mut:
   b int
   f()
}
```

2021-03-02 09:11 UTC, serkonda7 requested changes
We have a bigger problem with interface handling here.
Take a look at the fields and methods initial order. It's completely destroyed by fmt as the fields are written first and the methods afterwards because fmt does not take their positions into account.

Therefore this solution for keeping mut is dangerous as the method is set to be mutable too.

2021-03-02 11:29 UTC, medvednikov commented
It's fine to list fields first.

Just have to keep correct access mods.

2021-03-02 12:14 UTC, serkonda7 commented
@medvednikov it isn't possible to keep the access modifiers correct, if the order of interface elements is changed.

2021-03-03 09:06 UTC, spytheman commented
what is a mutable method?

2021-03-03 09:16 UTC, spytheman commented
I think only fields can be mutable, thus the methods are not affected by the `mut:` reordering, and fields are kept in the same order as the parser saw them, thus I do not understand the problem ?

2021-03-03 09:43 UTC, serkonda7 commented
If methods are not affected by mut this is fine.
But can interfaces have a pub modifirr too? Then it would be problematic again because methods can be public or private.

2021-03-03 16:04 UTC, rcqls commented
BTW, in my example, only field was mutable.

2021-03-04 10:46 UTC, spytheman commented
@spaceface777 what do you think?
will that cause problems for methods?

2021-03-04 10:52 UTC, spaceface777 commented
> I think (I may be wrong) that only fields can be mutable, thus the methods are not affected by the `mut:` reordering, and fields are kept in the same order as the parser has seen them, thus I do not understand the problem ?

this is true, I just tested it - with this PR methods are always placed at the bottom, and the mut_pos is ok, and currently methods are not affected at all by the mut: specifier, so it does not make a difference if they are always placed at the bottom.

2021-03-04 10:54 UTC, spaceface777 commented
although, now that I think about it: an
```
interface Bar {
mut:
   my_method()
}
``` may be an interesting new feature, where the receiver of the method implementing that interface must be mutable.

The inverse could then apply as well - if a method was NOT listed under the `mut:` section, then the original method must NOT mutate its receiver.

2021-03-04 10:58 UTC, serkonda7 approved these changes

2021-03-04 13:26 UTC, spytheman commented
> However, none of this exists right now, and thus does not affect this PR (for now).

I better merge this then, before it is implemented 😆 ...

2021-03-04 13:30 UTC, merged