cmd/tools/vdoc: support `v doc -os os module`and show docs according to the plaform
vlang/v pull request #9474
Opened 2021-03-26 08:40 UTC by Delta456

This PR adds support for viewing docs according to the platform and functionality to view docs for other OS via `v doc -os os module`. Previously it used to show docs for `_default.c.v` files so this PR also fixed that.

Screenshots:
![image](https://user-images.githubusercontent.com/28479139/112604817-98f05000-8e3c-11eb-9f1e-e35bd0bc07d6.png)

![image](https://user-images.githubusercontent.com/28479139/112604976-cc32df00-8e3c-11eb-8b8f-39f6488b9f47.png)

![image](https://user-images.githubusercontent.com/28479139/112605017-d8b73780-8e3c-11eb-95b2-074a6203f0e9.png)

![image](https://user-images.githubusercontent.com/28479139/112605107-f1275200-8e3c-11eb-98c4-dc334decb5db.png)

**NOTE**: `v doc -os cross module` is not yet supported due to a parser issue which cannot be tackled right now :/

2021-03-26 09:31 UTC, nedpals commented on vlib/v/pref/os.v
> +	all
@Delta456 Should we comment the `Platform.cross` and `OS.all` enums (and it's related code) for now while the issue is still present? What do you think?

2021-03-26 14:27 UTC, Delta456 commented on vlib/v/pref/os.v
> +	all
We don't need `.all` for getting the common symbols?

2021-03-26 14:56 UTC, Delta456 commented on vlib/v/pref/os.v
> +	all
Comment added

2021-03-26 14:57 UTC, nedpals approved these changes

2021-03-26 18:00 UTC, danieldaeschle requested changes

2021-03-26 18:16 UTC, Delta456 commented on vlib/v/doc/doc.v
> +	mut plf := platform_from_string(suffix) or { Platform.cross }
How about `platform_`?

2021-03-26 18:30 UTC, danieldaeschle commented on vlib/v/doc/doc.v
> +	mut plf := platform_from_string(suffix) or { Platform.cross }
ist platform a reseved word? looks ok.

2021-03-27 08:29 UTC, Delta456 commented on vlib/v/doc/doc.v
> +	mut plf := platform_from_string(suffix) or { Platform.cross }
Done

2021-03-27 08:50 UTC, merged