json2: trim spaces from json string before parsing
vlang/v pull request #9496
Opened 2021-03-28 14:10 UTC by atakanyenel

There is an error discovered in #9490 where json2 cannot parse strings if the first character is not a bracket. This PR will fix that by applying `trim_space` to the string before `raw_decode`.

Fixes #9490

2021-03-28 14:48 UTC, JalonSolov commented
Is the problem because the first character isn't a bracket, or because the first character is whitespace?
```
"my string"
```
is perfectly valid JSON, which doesn't start with a bracket.

2021-03-28 14:51 UTC, atakanyenel commented
You are right. Both the wording in this PR and the bug is wrong. There are tests for normal strings and `[]` passing which are valid jsons. I will word it as first char is a whitespace/newline.

2021-03-28 22:44 UTC, nedpals commented
It would be better to do this inside the json2 scanner rather than this so it would scan the string only once.

2021-03-28 22:45 UTC, nedpals requested changes
It would be better to do this inside the json2 scanner rather than this so it would only scan the string once.

2021-03-29 12:49 UTC, nedpals commented
@atakanyenel Is it okay to close this PR? I have an appropriate solution to this issue

2021-03-29 13:49 UTC, JalonSolov commented
Closing in favor of #9508

2021-03-29 13:49 UTC, closed without merging