checker: do not allow module aliases started with '_' (underscore)
vlang/v pull request #9588
Opened 2021-04-04 10:01 UTC by caiertl

Fixes #9587

2021-04-04 11:02 UTC, spaceface777 requested changes
Good work, thanks! just a few minor improvements.

2021-04-04 11:02 UTC, spaceface777 commented on vlib/v/checker/checker.v
> +	if imp.alias.starts_with('_') {
check out the existing [`check_valid_snake_case`](https://github.com/vlang/v/blob/337e447cfbbba2f990bae38ea55dfb0674f4db31/vlib/v/checker/checker.v#L267-L275) method :)

2021-04-04 19:01 UTC, caiertl commented on vlib/v/checker/checker.v
> +	if imp.alias.starts_with('_') {
Thank you! I've applied your suggestion.

2021-04-04 19:06 UTC, spaceface777 approved these changes

2021-04-05 18:59 UTC, LouisSchmieder approved these changes

2021-04-09 10:14 UTC, merged