builtin: fix termux println
vlang/v pull request #9829
Opened 2021-04-20 19:17 UTC by treffner

Fix for missing v output on termux/android.
https://github.com/vlang/v/issues/9662

This commit introduced the regression
https://github.com/vlang/v/commit/824790a2bdd35337488d20e2dbf9cfa31434d53d

2021-04-20 20:06 UTC, Larpon requested changes
@spytheman or @spaceface777 might have ideas. Maybe it's time to do something about the printf hi-jack?

2021-04-20 20:06 UTC, Larpon commented on vlib/builtin/builtin.c.v
> -	$if android {
I haven't got time to test this unfortunately but this will probably kill logcat output on normal Android apps since we currently redefine printf to capture the output.

2021-04-20 20:38 UTC, spaceface777 commented on vlib/builtin/builtin.c.v
> -	$if android {
Maybe we could wrap the custom println impl under `$if android && apk {}` ?

2021-04-20 20:45 UTC, Larpon commented on vlib/builtin/builtin.c.v
> -	$if android {
That would work for now - good thinking!

2021-04-20 20:48 UTC, Larpon commented on vlib/builtin/builtin.c.v
> -	$if android {
@treffner can you try adding simply the ` && apk {` as spaceface mentioned above and see if that works for you?

2021-04-20 20:54 UTC, treffner commented on vlib/builtin/builtin.c.v
> -	$if android {
Yes, will try tomorrow.

2021-04-21 05:08 UTC, treffner commented on vlib/builtin/builtin.c.v
> -	$if android {
That gives:
vlib/builtin/builtin.c.v:211:17: error: undefined ident: `apk`
  211 |     $if android && apk {

So I guess we need to check somehow if we are in an apk or not.

2021-04-21 05:10 UTC, treffner commented on vlib/builtin/builtin.c.v
> -	$if android {
But shouldn't such hi-jacking happen in the logcat module and not here where it should be a normal output. I guess the other print functions like eprint or print are also affected.

2021-04-21 07:05 UTC, Larpon commented on vlib/builtin/builtin.c.v
> -	$if android {
Yes it's a bit hacky this way - but if I remember correct there was other issues like having to include `android.h` from the (large) SDK and something else I can't recall right now.

2021-04-21 15:15 UTC, treffner commented on vlib/builtin/builtin.c.v
> -	$if android {
I try to get vab to work. Maybe I can figure this out.

2021-04-27 20:14 UTC, treffner commented on vlib/builtin/builtin.c.v
> -	$if android {
I've added another commit to resolve the issue.
But, I was unable to test vab - it does not find some tooling. Can someone check if this does not break vab?

2021-04-27 20:48 UTC, Gladear commented on vlib/builtin/builtin.c.v
> -	$if android {
I you look at the global diff now, the PR basically didn't change anything 😕

2021-04-28 04:24 UTC, treffner commented on vlib/builtin/builtin.c.v
> -	$if android {
I think this is a good thing. Fixing an issue with basically changing a single if.
The diff should look like:

```
-       } $else $if ios {
+}
+        $if ios {
```

I can try to squash the commits if that helps.

If this gets merged I will look into eprintln as well.

2021-04-28 06:11 UTC, merged